export const recurrence_relationsData = {
    mainTopic: "Recurrence Relations",
    lessonVideoId: "Y3eGTMlMgNs",
    subTopics: [
        {
            topicName: "Practice Questions",
            questions: [
                {
                    question: `A sequence is generated by the recurrence relation \\(u_{n+1}=ku_n+4,\\) where \\(k\\) is a constant. Given \\(u_0=-1\\) and \\(u_1=7,\\) find the value of \\(k\\) and the value of \\(u_{3}.\\)`,
                    answer: `\\(k = -3, \\quad u_3 = 55\\)`,
                    videoId: "YeKJFgMHBYw",
                    timestamp: "27s"
                },
                {
                    question: `A sequence is defined by the recurrence relation \\(u_{n+1}=mu_n+c,\\) where \\(m\\) and \\(c\\) are constants. The first three terms of the sequence are \\(12,\\) \\(20\\) and \\(26.\\) Find the values of \\(m\\) and \\(c.\\) Hence find the value of the fourth term in the sequence.`,
                    answer: `\\(m = \\frac{3}{4}, \\quad c = 11, \\quad u_4 = \\frac{61}{2}\\)`,
                    videoId: "YeKJFgMHBYw",
                    timestamp: "2m54s"
                },
                {
                    question: `A sequence is generated by the recurrence relation \\(u_{n+1}=mu_n-3,\\) where \\(m\\) is a positive integer. Given \\(u_2=11\\) and \\(u_4=35,\\) find the value of \\(m\\) and the value of \\(u_{3}.\\)`,
                    answer: `\\(m = 2, \\quad u_3 = 19\\)`,
                    videoId: "YeKJFgMHBYw",
                    timestamp: "5m53s"
                },
                {
                    question: `A sequence is defined by the recurrence relation \\(u_{n+1}=\\frac{2}{3} u_n+4,\\) with \\(u_1=6.\\) Explain why this sequence approaches a limit as \\(n \\to \\infty\\) and calculate this limit.`,
                    answer: `A limit exists because \\(-1 < \\frac{2}{3} < 1\\). The limit \\(L = 12\\).`,
                    videoId: "YeKJFgMHBYw",
                    timestamp: "8m17s"
                },
                {
                    question: `The population of Common Blue butterflies in a woodland area is observed to be declining by \\(3.5\\%\\) per year. To increase the population, scientists plan to release \\(500\\) of this species within the woodland at the end of June each year. Let \\(u_n\\) represent the population at the beginning of July, \\(n\\) years after the first annual reintroduction. It is known that \\(u_n\\) and \\(u_{n+1}\\) satisfy the recurrence relation \\(u_{n+1}=au_{n}+b.\\)<br><b>(a)</b>&nbsp;&nbsp;State the values of \\(a\\) and \\(b.\\)<br><b>(b)</b>&nbsp;&nbsp;Explain whether or not the population will stabilise in the long term.<br><b>(c)</b>&nbsp;&nbsp;The population at the beginning of the reintroduction programme was estimated at \\(10,000.\\) Explain whether or not the population will ever exceed \\(15,000.\\)`,
                    answer: `(a) \\(a = 0.965, \\ b = 500\\)<br>(b) Stabilises because \\(-1 < 0.965 < 1\\)<br>(c) No, because the limit is approximately \\(14,286\\).`,
                    videoId: "YeKJFgMHBYw",
                    timestamp: "9m24s"
                },
                {
                    question: `Sequences may be generated by recurrence relations of the form \\(u_{n+1}=ku_n-5,\\) \\(u_0=20,\\) where \\(k \\in \\mathbb{R}.\\)<br><b>(a)</b>&nbsp;&nbsp;Show that \\(u_2=20k^2-5k-5\\).<br><b>(b)</b>&nbsp;&nbsp;Find the range of values of \\(k\\) for which \\(u_2 < u_0.\\)`,
                    answer: `(b) \\(-1 < k < \\frac{5}{4}\\)`,
                    videoId: "YeKJFgMHBYw",
                    timestamp: "12m58s"
                },
                {
                    question: `Sequences may be defined by the linear recurrence relation \\(u_{n+1}=(3-k)u_n-2.\\) Find the range of values of \\(k\\) for which such a sequence converges to a limit.`,
                    answer: `\\(2 < k < 4\\)`,
                    videoId: "YeKJFgMHBYw",
                    timestamp: "16m5s"
                },
                {
                    question: `<small><strong><span style="white-space: nowrap;">2016 P1 Q3</span></strong></small><br>A sequence is defined by the recurrence relation \\(u_{n+1}=\\frac{1}{3} u_n+10\\) with \\(u_3=6.\\)<br><b>(a)</b>&nbsp;&nbsp;Find the value of \\(u_4.\\)<br><b>(b)</b>&nbsp;&nbsp;Explain why this sequence approaches a limit as \\(n \\to \\infty.\\)<br><b>(c)</b>&nbsp;&nbsp;Calculate this limit.`,
                    answer: `(a) \\(u_4 = 12\\)<br>(b) Limit exists as \\(-1 < \\frac{1}{3} < 1\\)<br>(c) Limit \\(= 15\\)`,
                    videoId: "YeKJFgMHBYw",
                    timestamp: "17m47s"
                },
                {
                    question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q9</span></strong></small><br>A sequence is generated by the recurrence relation \\(u_{n+1}=m\\,u_n+6\\) where \\(m\\) is a constant.<br><b>(a)</b>&nbsp;&nbsp;Given that \\(u_1=28\\) and \\(u_2=13,\\) find the value of \\(m.\\)<br><b>(b)</b>&nbsp;&nbsp;(i) Explain why this sequence approaches a limit as \\(n \\to \\infty.\\)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ii) Calculate this limit.`,
                    answer: `(a) \\(m = \\frac{1}{4}\\)<br>(b) (i) Limit exists as \\(-1 < \\frac{1}{4} < 1\\)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ii) Limit \\(= 8\\)`,
                    videoId: "YeKJFgMHBYw",
                    timestamp: "19m37s"
                },
                {
                    question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q4</span></strong></small><br>A sequence is defined by the recurrence relation \\(u_{n+1}=mu_n+c,\\) where the first three terms of the sequence are \\(6,\\) \\(9\\) and \\(11.\\)<br><b>(a)</b>&nbsp;&nbsp;Find the values of \\(m\\) and \\(c.\\)<br><b>(b)</b>&nbsp;&nbsp;Hence, calculate the fourth term of the sequence.`,
                    answer: `(a) \\(m = \\frac{2}{3}, \\ c = 5\\)<br>(b) \\(u_4 = \\frac{37}{3}\\)`,
                    videoId: "YeKJFgMHBYw",
                    timestamp: "21m16s"
                },
                {
                    question: `<small><strong><span style="white-space: nowrap;">2021 P1 Q13</span></strong></small><br>A sequence is generated by the recurrence relation \\(u_{n+1}=\\frac{2}{3}u_n+8,\\) \\(u_7=20.\\)<br><b>(a)</b>&nbsp;&nbsp;Determine the value of \\(u_5.\\)<br><b>(b)</b>&nbsp;&nbsp;Determine the limit of this sequence.`,
                    answer: `(a) \\(u_5 = 15\\)<br>(b) Limit \\(= 24\\)`,
                    videoId: "YeKJFgMHBYw",
                    timestamp: "23m8s"
                },
                {
                    question: `<small><strong><span style="white-space: nowrap;">2021 P2 Q12</span></strong></small><br>A sequence of real numbers is such that the terms of the sequence satisfy the recurrence relation \\(u_{n+1}=9u_n-440\\) and \\(u_{n+1} > u_n\\) for all values of \\(n.\\) The difference between two particular terms, \\(u_{k+1}\\) and \\(u_k,\\) is \\(1000.\\) Determine, algebraically, the value of \\(u_k.\\)`,
                    answer: `\\(u_k = 180\\)`,
                    videoId: "YeKJFgMHBYw",
                    timestamp: "25m7s"
                },
                {
                    question: `<small><strong><span style="white-space: nowrap;">2024 P1 Q2</span></strong></small><br>A sequence is defined by the recurrence relation \\(u_{n+1}=\\frac{1}{5} u_n+12\\) with \\(u_1=20.\\)<br><b>(a)</b>&nbsp;&nbsp;Calculate the value of \\(u_2.\\)<br><b>(b)</b>&nbsp;&nbsp;(i) Explain why this sequence approaches a limit as \\(n \\to \\infty.\\)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ii) Calculate this limit.`,
                    answer: `(a) \\(u_2 = 16\\)<br>(b) (i) Limit exists as \\(-1 < \\frac{1}{5} < 1\\)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ii) Limit \\(= 15\\)`,
                    videoId: "YeKJFgMHBYw",
                    timestamp: "26m30s"
                }
            ]
        },
        {
            topicName: "Resources",
            type: "resources",
            items: [
                { name: "Cheat Sheet", link: "resources/higher/recurrence_relations_cheatsheet.html" },
                { name: "Checklist", link: "resources/higher/recurrence_relations_checklist.html" }
            ]
        }
    ]
};
