export const pastpaper2017 = {
    year: 2017,
    papers: [
        {
            paperNumber: 1,
            questions: [
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q1</span></strong></small><p>Given that \\(f(x)=x^{2}+3x\\), evaluate \\(f(-5).\\)</p>`, answer: `10`, videoId: "RgoTxLmU1Pc", timestamp: "0s", topics: ["Function notation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q2</span></strong></small><p>The number of calls received by the police was recorded over 10 days. The results are shown below:<br><span class="text-xl font-mono">198&nbsp;&nbsp;216&nbsp;&nbsp;218&nbsp;&nbsp;230&nbsp;&nbsp;232&nbsp;&nbsp;247&nbsp;&nbsp;248&nbsp;&nbsp;250&nbsp;&nbsp;265&nbsp;&nbsp;267</span><br>Find the semi-interquartile range of this data.</p>`, answer: `16`, videoId: "RgoTxLmU1Pc", timestamp: "33s", topics: ["Median/Quartiles/Interquartile Range"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q3</span></strong></small><p>Evaluate \\(1\\frac{5}{6}\\div\\frac{3}{4}.\\)<br>Give your answer in its simplest form.</p>`, answer: `\\(\\frac{22}{9}\\)`, videoId: "RgoTxLmU1Pc", timestamp: "620s", topics: ["Fractions and mixed numbers"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q4</span></strong></small><p>Expand and simplify \\((2x+3)(x^{2}-4x+1).\\)</p>`, answer: `\\(2x^{3}-5x^{2}-10x+3\\)`, videoId: "RgoTxLmU1Pc", timestamp: "687s", topics: ["Expanding brackets"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q5</span></strong></small><p>The diagram shows a square-based pyramid placed on top of a cube, relative to the coordinate axes.</p><img src="/img/N5_Past_Papers/2017/2017_P1_Q5.png" alt="Square-based pyramid on cube"><p>The height of the pyramid is half of the height of the cube.<br>A is the point \\((6,0,0).\\)<br>The point C is directly above the centre of the base.<br>Write down the coordinates of B and C.</p>`, answer: `B(0,6,6), C(3,3,9)`, videoId: "RgoTxLmU1Pc", timestamp: "731s", topics: ["3d Coordinates"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q6</span></strong></small><p>The diagram shows the straight line joining points A and B.<br>A is \\((-1,6)\\) and B is \\((3,-2).\\)</p><img src="/img/N5_Past_Papers/2017/2017_P1_Q6.png" alt="Straight line joining points A and B"><p>Find the equation of the line AB.<br>Give the equation in its simplest form.</p>`, answer: `\\(y=-2x+4\\)`, videoId: "RgoTxLmU1Pc", timestamp: "845s", topics: ["Straight Line Equation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q7</span></strong></small><p>In triangle DEF:<br>DE = 8 cm, EF = 12 cm, \\(\\sin E = \\frac{2}{3}.\\)</p><img src="/img/N5_Past_Papers/2017/2017_P1_Q7.png" alt="Triangle DEF"><p>Calculate the area of triangle DEF.</p>`, answer: `32 cm²`, videoId: "RgoTxLmU1Pc", timestamp: "914s", topics: ["Area of a Triangle"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q8</span></strong></small><p>Solve, algebraically, the inequality \\(19+x>15+3(x-2).\\)</p>`, answer: `\\(x<5\\)`, videoId: "RgoTxLmU1Pc", timestamp: "1020s", topics: ["Linear equations and inequations"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q9</span></strong></small><p>In the diagram:<br>ABE is a tangent to the circle centre O.<br>Angle DBE is \\(58^{\\circ}.\\)</p><img src="/img/N5_Past_Papers/2017/2017_P1_Q9.png" alt="Circle with tangent"><p>Calculate the size of angle CAB.</p>`, answer: `26°`, videoId: "RgoTxLmU1Pc", timestamp: "1107s", topics: ["Angles in diagrams involving circles"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q10</span></strong></small><p>Change the subject of the formula \\(F=\\frac{t^{2}+4b}{c}\\) to \\(b.\\)</p>`, answer: `\\(b=\\frac{Fc-t^{2}}{4}\\)`, videoId: "RgoTxLmU1Pc", timestamp: "1220s", topics: ["Changing the subject of a formula"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q11</span></strong></small><p>Express \\(\\frac{3}{a^{2}}-\\frac{2}{a}\\), \\(a\\ne0\\), as a single fraction in its simplest form.</p>`, answer: `\\(\\frac{3-2a}{a^{2}}\\)`, videoId: "RgoTxLmU1Pc", timestamp: "1260s", topics: ["Add or subtract Algebraic Fractions"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q12</span></strong></small><p>Gym members are asked to give a rating on a scale of 1 to 6.<br>The ratings given by five members were:<br><span class="text-xl font-mono">1&nbsp;&nbsp;4&nbsp;&nbsp;6&nbsp;&nbsp;3&nbsp;&nbsp;6</span><br>In its simplest form, the standard deviation of these ratings can be written as \\(\\frac{a\\sqrt{b}}{2}.\\)<br>Find the values of \\(a\\) and \\(b.\\)</p>`, answer: `\\(a=3, b=2\\)`, videoId: "RgoTxLmU1Pc", timestamp: "1368s", topics: ["Standard Deviation", "Simplifying surds"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q13</span></strong></small><p>The graph shows two straight lines with equations \\(3x-y=2\\) and \\(x+3y=19.\\)<br>The lines intersect at the point P.</p><img src="/img/N5_Past_Papers/2017/2017_P1_Q13.png" alt="Two intersecting lines"><p>Find, algebraically, the coordinates of P.</p>`, answer: `(2.5, 5.5)`, videoId: "RgoTxLmU1Pc", timestamp: "1525s", topics: ["Simultaneous equations"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q14</span></strong></small><p>The graph shows a parabola with equation of the form \\(y=(x+a)^{2}+b.\\)<br>The equation of the axis of symmetry of the parabola is \\(x=-5.\\)</p><img src="/img/N5_Past_Papers/2017/2017_P1_Q14.png" alt="Parabola"><p><b>(a)</b>&nbsp;&nbsp;State the value of \\(a.\\)<br><br><b>(b)</b>&nbsp;&nbsp;The point \\((-3,8)\\) lies on the parabola. Calculate the value of \\(b.\\)</p>`, answer: `(a) \\(a=5\\), (b) \\(b=4\\)`, videoId: "RgoTxLmU1Pc", timestamp: "1695s", topics: ["Parabola Equation from Graph", "Turning Points and Axis of Symmetry"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q15</span></strong></small><p>In the diagram:<br>TS is parallel to QR.<br>TS = 5 cm, QR = 7 cm, SR = 2.6 cm.<br>The length of PS is \\(x\\) cm.</p><img src="/img/N5_Past_Papers/2017/2017_P1_Q15.png" alt="Similar triangles"><p>Calculate the value of \\(x.\\)</p>`, answer: `6.5`, videoId: "RgoTxLmU1Pc", timestamp: "1793s", topics: ["Similar lengths"] },
            ]
        },
        {
            paperNumber: 2,
            questions: [
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q1</span></strong></small><p>Find \\(|\\mathbf{v}|\\), the magnitude of vector \\(\\mathbf{v}=\\begin{pmatrix}18\\\\ -14\\\\ 3\\end{pmatrix}.\\)</p>`, answer: `23`, videoId: "ikwN7yZqPE8", timestamp: "0s", topics: ["Magnitude"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q2</span></strong></small><p>A necklace is valued at £1200.<br>Its value is expected to increase by 4.5% per year over the next 3 years.<br>Calculate the expected value of the necklace after this time.<br>Give your answer to the nearest pound.</p>`, answer: `£1369`, videoId: "ikwN7yZqPE8", timestamp: "49s", topics: ["Appreciation and Depreciation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q3</span></strong></small><p>A piece of land is in the shape of a triangle as shown.<br>PQ = 250 m, PR = 180 m, angle QPR = \\(147^{\\circ}.\\)<br>The owner wishes to build a fence along the side QR.</p><img src="/img/N5_Past_Papers/2017/2017_P2_Q3.png" alt="Triangular piece of land"><p>Calculate the length of the fence.</p>`, answer: `413 m`, videoId: "ikwN7yZqPE8", timestamp: "131s", topics: ["Cosine rule: calculate length"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q4</span></strong></small><p>Solve the equation \\(2x^{2}+5x-4=0.\\)<br>Give your answers correct to one decimal place.</p>`, answer: `\\(x=0.6, x=-3.1\\)`, videoId: "ikwN7yZqPE8", timestamp: "239s", topics: ["Quadratic formula"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q5</span></strong></small><p>A theatre group sold 4830 tickets for their show.<br>This was 15% more than they sold last year.<br>How many tickets did they sell last year?</p>`, answer: `4200`, videoId: "ikwN7yZqPE8", timestamp: "404s", topics: ["Reversing a percentage change"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q6</span></strong></small><p>A spherical sweet is made by coating a caramel sphere evenly with chocolate.<br>The diameter of the sweet is 24 mm and the thickness of the chocolate coating is 3 mm.</p><img src="/img/N5_Past_Papers/2017/2017_P2_Q6.png" alt="Spherical sweet cross-section"><p>Calculate the volume of the chocolate coating.<br>Give your answer correct to 3 significant figures.</p>`, answer: `4180 mm³`, videoId: "ikwN7yZqPE8", timestamp: "458s", topics: ["Volume - composite shape"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q7</span></strong></small><p>Triangles A and B are shown below.</p><img src="/img/N5_Past_Papers/2017/2017_P2_Q7(1).png" alt="Separate triangles A and B"><p>The triangles are placed together to form the larger triangle shown below.</p><img src="/img/N5_Past_Papers/2017/2017_P2_Q7(2).png" alt="Joined triangle"><p>Is this larger triangle right-angled?<br>Justify your answer.</p>`, answer: `No, since \\(8^{2}+19^{2}\\ne22^{2}\\) (425 is not 484).`, videoId: "ikwN7yZqPE8", timestamp: "620s", topics: ["Pythagoras converse"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q8</span></strong></small><p>In the diagram below, \\(\\vec{RQ}\\) and \\(\\vec{PQ}\\) represent the vectors \\(\\mathbf{c}\\) and \\(\\mathbf{d}\\) respectively.</p><img src="/img/N5_Past_Papers/2017/2017_P2_Q8_1.png" alt="Vector diagram PQ R"><p><b>(a)</b>&nbsp;&nbsp;Express \\(\\vec{PR}\\) in terms of \\(\\mathbf{c}\\) and \\(\\mathbf{d}.\\)<br><br>The line QP is extended to T.</p><img src="/img/N5_Past_Papers/2017/2017_P2_Q8_2.png" alt="Vector diagram extended to T"><p>\(\\bullet \\quad \\text{TP = PQ}\)<br>\(\\bullet \\quad \\text{V is the midpoint of PR}\)<br><b>(b)</b>&nbsp;&nbsp;Express \\(\\vec{TV}\\) in terms of \\(\\mathbf{c}\\) and \\(\\mathbf{d}.\\) Give your answer in simplest form.</p>`, answer: `(a) \\(\\mathbf{d}-\\mathbf{c}\\), (b) \\(\\frac{3}{2}\\mathbf{d}-\\frac{1}{2}\\mathbf{c}\\)`, videoId: "ikwN7yZqPE8", timestamp: "704s", topics: ["Vector pathways"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q9</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Factorise \\(4x^{2}-25.\\)<br><br><b>(b)</b>&nbsp;&nbsp;Hence simplify \\(\\frac{4x^{2}-25}{2x^{2}-x-10}.\\)</p>`, answer: `(a) \\((2x-5)(2x+5)\\), (b) \\(\\frac{2x+5}{x+2}\\)`, videoId: "ikwN7yZqPE8", timestamp: "819s", topics: ["Factorising", "Simplifying algebraic fraction"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q10</span></strong></small><p>In the diagram below D, E and F represent the positions of Dunbridge, Earlsford and Fairtown respectively.<br>Dunbridge is 15 km west of Earlsford.<br>From Dunbridge, the bearing of Fairtown is \\(126^{\\circ}.\\)<br>From Earlsford the bearing of Fairtown is \\(230^{\\circ}.\\)</p><img src="/img/N5_Past_Papers/2017/2017_P2_Q10.png" alt="Map with bearings"><p>Calculate the distance between Dunbridge and Fairtown.</p>`, answer: `9.9 km`, videoId: "ikwN7yZqPE8", timestamp: "997s", topics: ["Sine rule: calculate length", "Bearings in Trigonometry questions"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q11</span></strong></small><p>A straight line has equation \\(3x-5y-10=0.\\)<br>Find the gradient of this line.</p>`, answer: `\\(\\frac{3}{5}\\)`, videoId: "ikwN7yZqPE8", timestamp: "1260s", topics: ["Straight Line Equation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q12</span></strong></small><p>Express \\(\\frac{1}{\\sqrt[3]{x}}\\) in the form \\(x^{n}.\\)</p>`, answer: `\\(x^{-\\frac{1}{3}}\\)`, videoId: "ikwN7yZqPE8", timestamp: "1335s", topics: ["Rewriting fraction or negative index in the form ax^n"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q13</span></strong></small><p>Two identical shapes are used to form a logo.<br>Each shape is part of a circle.<br>The circles have centres \\(C_1\\) and \\(C_2.\\)<br>The radius of each circle is 14 cm.<br>The logo has half-turn symmetry about the mid-point of AB.<br>AB is 48 cm long.</p><img src="/img/N5_Past_Papers/2017/2017_P2_Q13.png" alt="Logo formed by two circles"><p>Calculate the height of the logo.</p>`, answer: `42.4 cm`, videoId: "ikwN7yZqPE8", timestamp: "1375s", topics: ["Pythagoras in circle diagrams"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q14</span></strong></small><p>The diagram shows part of a circle, centre O.<br>The radius of the circle is 6.4 cm.<br>Major arc AB has length 31.5 cm.</p><img src="/img/N5_Past_Papers/2017/2017_P2_Q14.png" alt="Circle with major arc"><p>Calculate the size of the reflex angle AOB.</p>`, answer: `282°`, videoId: "ikwN7yZqPE8", timestamp: "1501s", topics: ["Arc length"] },
                { question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q15</span></strong></small><p>A wind turbine has three blades.<br>The height, \\(h\\) metres, of the tip of blade A above the ground is given by \\(h=40+23\\cos x^{\\circ}\\), \\(0\\le x<360.\\)</p><img src="/img/N5_Past_Papers/2017/2017_P2_Q15.png" alt="Wind turbine blade"><p><b>(a)</b>&nbsp;&nbsp;Calculate the height of the tip of blade A after it has turned through an angle of \\(60^{\\circ}.\\)<br><br><b>(b)</b>&nbsp;&nbsp;Find the minimum height of the tip of blade A above the ground.<br><br><b>(c)</b>&nbsp;&nbsp;Calculate the values of \\(x\\) for which the tip of blade A is 61 metres above the ground.</p>`, answer: `(a) 51.5 metres, (b) 17 metres, (c) \\(24.1^{\\circ}, 335.9^{\\circ}\\)`, videoId: "ikwN7yZqPE8", timestamp: "1661s", topics: ["Trigonometric equation"] }
            ]
        }
    ]
};