export const pastpaper2014 = {
    year: 2014,
    papers: [
        {
            paperNumber: 1,
            questions: [
                { question: `<small><strong><span style="white-space: nowrap;">2014 P1 Q1</span></strong></small><br>Evaluate \\(\\frac{5}{12} \\times 2\\frac{2}{9}.\\)<br>Give the answer in simplest form.`, answer: `\\(\\frac{25}{27}\\)`, videoId: "mwZNKXHvY5U", timestamp: "0s", topics: ["Fractions and mixed numbers"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P1 Q2</span></strong></small><p>Multiply out the brackets and collect like terms: \\((2x-5)(3x+1)\\)</p>`, answer: `\\(6x^2-13x-5\\)`, videoId: "mwZNKXHvY5U", timestamp: "96s", topics: ["Expanding brackets"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P1 Q3</span></strong></small><p>Express \\(x^2-14x+44\\) in the form \\(\\left(x-a\\right)^2+b\\)</p>`, answer: `\\((x-7)^2-5\\)`, videoId: "mwZNKXHvY5U", timestamp: "146s", topics: ["Completing the square"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P1 Q4</span></strong></small><br>Find the resultant vector<br>\\(2\\mathbf{u}-\\mathbf{v}\\)<br>when \\(\\mathbf{u}=\\begin{pmatrix}-2\\\\ 3\\\\ 5\\end{pmatrix}\\) and \\(\\mathbf{v}=\\begin{pmatrix}0\\\\ -4\\\\ 7\\end{pmatrix}\\).<br>Express your answer in component form.`, answer: `\\(\\begin{pmatrix}-4\\\\ 10\\\\ 3\\end{pmatrix}\\)`, videoId: "mwZNKXHvY5U", timestamp: "196s", topics: ["Adding and Subtracting vector components"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P1 Q5</span></strong></small><p>In triangle KLM<br>&bull;&nbsp;&nbsp;KM = 18 centimetres<br>&bull;&nbsp;&nbsp;sin K = 0·4<br>&bull;&nbsp;&nbsp;sin L = 0·9</p><img src="/img/N5_Past_Papers/2014/2014_P1_Q5.png" alt="Triangle KLM with side KM, sin K, and sin L"><p>Calculate the length of LM.</p>`, answer: `8 cm`, videoId: "mwZNKXHvY5U", timestamp: "250s", topics: ["Sine rule: calculate length"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P1 Q6</span></strong></small><p>McGregor's Burgers sells fast food. The graph shows the relationship between the amount of fat, \\(F\\) grams, and the number of calories, \\(C\\), in some of their sandwiches.</p><img src="/img/N5_Past_Papers/2014/2014_P1_Q6.png" alt="Scattergraph of sandwich fat vs calories"><p>A line of best fit has been drawn.<br>Point A represents a sandwich which has 5 grams of fat and 200 calories.<br>Point B represents a sandwich which has 25 grams of fat and 500 calories.<br><br><b>(a)</b>&nbsp;&nbsp;Find the equation of the line of best fit in terms of \\(F\\) and \\(C.\\)<br><br><b>(b)</b>&nbsp;&nbsp;A Super Deluxe sandwich contains 40 grams of fat. Use your answer to part (a) to estimate the number of calories this sandwich contains.</p>`, answer: `(a) \\(C=15F+125\\), (b) 725 calories`, videoId: "mwZNKXHvY5U", timestamp: "412s", topics: ["Scatter Graph", "Straight Line Equation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P1 Q7</span></strong></small><p>The diagram below shows part of the graph of \\(y=ax^2\\).</p><img src="/img/N5_Past_Papers/2014/2014_P1_Q7.png" alt="Parabola passing through point (-3, 45)"><p>The point \\((-3,45)\\) lies on the graph.<br>Find the value of \\(a\\).</p>`, answer: `\\(a=5\\)`, videoId: "mwZNKXHvY5U", timestamp: "612s", topics: ["Parabola Equation from Graph"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P1 Q8</span></strong></small><br>Express \\( \\sqrt{40}+4\\sqrt{10}+\\sqrt{90} \\)<br>as a surd in its simplest form.`, answer: `\\(9\\sqrt{10}\\)`, videoId: "mwZNKXHvY5U", timestamp: "669s", topics: ["Simplifying surds"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P1 Q9</span></strong></small><br>480 000 tickets were sold for a tennis tournament last year. This represents 80% of all the available tickets.<br>Calculate the total number of tickets that were available for this tournament.`, answer: `600,000 tickets`, videoId: "mwZNKXHvY5U", timestamp: "732s", topics: ["Reversing a percentage change"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P1 Q10</span></strong></small><p>The graph of \\(y=a\\sin(x+b)^\\circ\\), \\(0\\le x\\le360\\), is shown below.</p><img src="/img/N5_Past_Papers/2014/2014_P1_Q10.png" alt="Graph of y=a sin(x+b) degrees"><p>Write down the values of \\(a\\) and \\(b\\).</p>`, answer: `\\(a=3\\), \\(b=-40\\)`, videoId: "mwZNKXHvY5U", timestamp: "801s", topics: ["Identify equation of trigonometric graph"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P1 Q11</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;A straight line has equation \\(4x+3y=12\\).<br>Find the gradient of this line.<br><br><b>(b)</b>&nbsp;&nbsp;Find the coordinates of the point where this line crosses the <span style="white-space: nowrap;">\\(x\\)-axis.</span></p>`, answer: `(a) \\(m=-\\frac{4}{3}\\), (b) \\((3,0)\\)`, videoId: "mwZNKXHvY5U", timestamp: "840s", topics: ["Coordinate Geometry with straight line equation", "Straight Line Equation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P1 Q12</span></strong></small><p>The diagram below shows a circle, centre C.</p><img src="/img/N5_Past_Papers/2014/2014_P1_Q12.png" alt="Circle with chord PQ and radius CB"><p>The radius of the circle is 15 centimetres.<br>A is the mid-point of chord PQ.<br>The length of AB is 27 centimetres.<br>Calculate the length of PQ.</p>`, answer: `18 cm`, videoId: "mwZNKXHvY5U", timestamp: "904s", topics: ["Pythagoras in circle diagrams"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P1 Q13</span></strong></small><p>The diagram below shows the path of a small rocket which is fired into the air. The height, \\(h\\) metres, of the rocket after \\(t\\) seconds is given by \\(h(t)=16t-t^2.\\)</p><img src="/img/N5_Past_Papers/2014/2014_P1_Q13.png" alt="Rocket trajectory diagram"><p><b>(a)</b>&nbsp;&nbsp;After how many seconds will the rocket first be at a height of 60 metres?<br><br><b>(b)</b>&nbsp;&nbsp;Will the rocket reach a height of 70 metres? Justify your answer.</p>`, answer: `(a) 6 seconds, (b) No, because its maximum height is 64 metres`, videoId: "mwZNKXHvY5U", timestamp: "1047s", topics: ["Quadratic equation by factorising"] }
            ]
        },
        {
            paperNumber: 2,
            questions: [
                { question: `<small><strong><span style="white-space: nowrap;">2014 P2 Q1</span></strong></small><br>There are 964 pupils on the roll of Aberleven High School. It is forecast that the roll will decrease by 15% per year.<br>What will be the expected roll after 3 years? Give your answer to the nearest ten.`, answer: `590 pupils`, videoId: "s4Fu-SgBgV8", timestamp: "0s", topics: ["Appreciation and Depreciation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P2 Q2</span></strong></small><p>The diagram shows a cube placed on top of a cuboid, relative to the coordinate axes.</p><img src="/img/N5_Past_Papers/2014/2014_P2_Q2.png" alt="Cube on top of a cuboid in 3D coordinates"><p>A is the point (8,4,6).<br>Write down the coordinates of B and C.</p>`, answer: `B(8,4,10), C(4,0,10)`, videoId: "s4Fu-SgBgV8", timestamp: "62s", topics: ["3d Coordinates"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P2 Q3</span></strong></small><p>Two groups of people go to a theatre.<br>Bill buys tickets for 5 adults and 3 children. The total cost of his tickets is £158·25.<br><b>(a)</b>&nbsp;&nbsp;Write down an equation to illustrate this information.<br><br>Ben buys tickets for 3 adults and 2 children. The total cost of his tickets is £98.<br><b>(b)</b>&nbsp;&nbsp;Write down an equation to illustrate this information.<br><br><b>(c)</b>&nbsp;&nbsp;Calculate the cost of a ticket for an adult and the cost of a ticket for a child.</p>`, answer: `(a) \\(5a+3c=158.25\\), (b) \\(3a+2c=98\\), (c) Adult £22.50, Child £15.25`, videoId: "s4Fu-SgBgV8", timestamp: "158s", topics: ["Simultaneous equations"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P2 Q4</span></strong></small><p>A runner has recorded her times, in seconds, for six different laps of a running track:<br><span class="text-xl font-mono">53&nbsp;&nbsp;57&nbsp;&nbsp;58&nbsp;&nbsp;60&nbsp;&nbsp;55&nbsp;&nbsp;56</span><br><br><b>(a)</b>&nbsp;&nbsp;(i) Calculate the mean of these lap times.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ii) Calculate the standard deviation of these lap times.<br><br><b>(b)</b>&nbsp;&nbsp;She changes her training routine hoping to improve her consistency. After this change, she records her times for another six laps. The mean is 55 seconds and the standard deviation 3·2 seconds. Has the new training routine improved her consistency? Give a reason for your answer.</p>`, answer: `(a)(i) 56.5 seconds, (ii) 2.4 seconds, (b) No, standard deviation is greater`, videoId: "s4Fu-SgBgV8", timestamp: "441s", topics: ["Standard Deviation", "Comparing Calculated Statistics"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P2 Q5</span></strong></small><p>A supermarket sells cylindrical cookie jars which are mathematically similar.</p><img src="/img/N5_Past_Papers/2014/2014_P2_Q5.png" alt="Two cylindrical cookie jars"><p>The smaller jar has a height of 15 centimetres and a volume of 750 cubic centimetres.<br>The larger jar has a height of 24 centimetres.<br>Calculate the volume of the larger jar.</p>`, answer: `3072 cm³`, videoId: "s4Fu-SgBgV8", timestamp: "707s", topics: ["Similar areas/volumes"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P2 Q6</span></strong></small><p>The diagram below shows the position of three towns.<br>Lowtown is due west of Midtown.</p><img src="/img/N5_Past_Papers/2014/2014_P2_Q6.png" alt="Triangle showing Lowtown, Midtown and Hightown"><p>The distance from<br>&bull;&nbsp;&nbsp;Lowtown to Midtown is 75 kilometres.<br>&bull;&nbsp;&nbsp;Midtown to Hightown is 110 kilometres.<br>&bull;&nbsp;&nbsp;Hightown to Lowtown is 85 kilometres.<br><br>Is Hightown directly north of Lowtown? Justify your answer.</p>`, answer: `No, since \\(110^2 \\neq 85^2+75^2\\) (it is not right angled)`, videoId: "s4Fu-SgBgV8", timestamp: "806s", topics: ["Pythagoras converse"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P2 Q7</span></strong></small><p>An ornament is in the shape of a cone with diameter 8 centimetres and height 15 centimetres.</p><img src="/img/N5_Past_Papers/2014/2014_P2_Q7.png" alt="Cone with hemisphere cutout at bottom"><p>The bottom contains a hemisphere made of copper with diameter 7·4 centimetres.<br>The rest is made of glass.<br><br>Calculate the volume of the glass part of the ornament.<br>Give your answer correct to 2 significant figures.</p>`, answer: `150 cm³`, videoId: "s4Fu-SgBgV8", timestamp: "920s", topics: ["Volume - composite shape"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P2 Q8</span></strong></small><br>Simplify \\( \\large\\frac{n^5 \\times 10n}{2n^2}\\).`, answer: `\\(5n^4\\)`, videoId: "s4Fu-SgBgV8", timestamp: "1109s", topics: ["Laws of indices"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P2 Q9</span></strong></small><p>Express \\(\\large\\frac{7}{x+5}-\\frac{3}{x}\\normalsize\\)&nbsp;&nbsp;&nbsp;&nbsp;\\(\\small x\\neq-5,\\ x\\neq0\\)<br>as a single fraction in its simplest form.</p>`, answer: `\\(\\frac{4x-15}{x(x+5)}\\)`, videoId: "s4Fu-SgBgV8", timestamp: "1153s", topics: ["Add or subtract Algebraic Fractions"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P2 Q10</span></strong></small><p>In a race, boats sail round three buoys represented by A, B, and C in the diagram below.</p><img src="/img/N5_Past_Papers/2014/2014_P2_Q10.png" alt="Boats sailing around buoys A, B, C"><p>B is 8 kilometres from A on a bearing of 060°.<br>C is 11 kilometres from B.<br>A is 13 kilometres from C.<br><br><b>(a)</b>&nbsp;&nbsp;Calculate the size of angle ABC.<br><br><b>(b)</b>&nbsp;&nbsp;Hence find the size of the shaded angle.</p>`, answer: `(a) 84.8°, (b) 155.2°`, videoId: "s4Fu-SgBgV8", timestamp: "1207s", topics: ["Cosine rule: calculate angle", "Bearings in Trigonometry questions"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P2 Q11</span></strong></small><p>Change the subject of the formula<br>\\(s=ut+\\large\\frac{1}{2}\\normalsize at^2\\) to \\(a.\\)</p>`, answer: `\\(a = \\frac{2(s-ut)}{t^2}\\)`, videoId: "s4Fu-SgBgV8", timestamp: "1471s", topics: ["Changing the subject of a formula"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P2 Q12</span></strong></small><p>Solve the equation \\(11\\cos x^\\circ - 2 = 3\\), for \\(0 \\le x \\le 360.\\)</p>`, answer: `\\(x=63.0^\\circ\\) or \\(x=297.0^\\circ\\) (to 1 d.p.)`, videoId: "s4Fu-SgBgV8", timestamp: "1539s", topics: ["Trigonometric equation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2014 P2 Q13</span></strong></small><p>The picture shows the entrance to a tunnel which is in the shape of part of a circle.</p><img src="/img/N5_Past_Papers/2014/2014_P2_Q13(1).png" alt="Tunnel cross-section - circular sector"><p>The diagram below represents the cross-section of the tunnel.<br>&bull;&nbsp;&nbsp;The centre of the circle is O.<br>&bull;&nbsp;&nbsp;MN is a chord of the circle.<br>&bull;&nbsp;&nbsp;Angle MON is 50°.<br>&bull;&nbsp;&nbsp;The radius of the circle is 7 metres.</p><img src="/img/N5_Past_Papers/2014/2014_P2_Q13(2).png" alt="Tunnel cross-section showing angle MON"><p>Calculate the area of the cross-section of the tunnel.</p>`, answer: `151.3 m²`, videoId: "s4Fu-SgBgV8", timestamp: "1640s", topics: ["Area of a Triangle", "Sector area"] }
            ]
        }
    ]
};