export const pastpaper2019 = {
    year: 2019,
    papers: [
        {
            paperNumber: 1,
            questions: [
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q1</span></strong></small><p>Given that \\(f(x)=5x^{3}\\), evaluate \\(f(-2).\\)</p>`, answer: `-40`, videoId: "0ZcNrPB1w3s", timestamp: "0s", topics: ["Function notation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q2</span></strong></small><p>Evaluate \\(\\frac{3}{8} \\times 1\\frac{5}{7}.\\)<br>Give your answer in its simplest form.</p>`, answer: `\\(\\frac{9}{14}\\)`, videoId: "0ZcNrPB1w3s", timestamp: "31s", topics: ["Fractions and mixed numbers"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q3</span></strong></small><p>Expand and simplify \\((x+5)(2x^{2}-7x-3).\\)</p>`, answer: `\\(2x^{3}+3x^{2}-38x-15\\)`, videoId: "0ZcNrPB1w3s", timestamp: "77s", topics: ["Expanding brackets"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q4</span></strong></small><p>The diagram below shows a sector of a circle, centre C.</p><img src="/img/N5_Past_Papers/2019/2019_P1_Q4.png" alt="Sector of a circle with angle 240 degrees and radius 30cm"><p>The radius of the circle is 30 centimetres.<br>Calculate the length of the major arc AB.<br>Take \\(\\pi=3\\cdot14.\\)</p>`, answer: `125.6 cm`, videoId: "0ZcNrPB1w3s", timestamp: "147s", topics: ["Arc length"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q5</span></strong></small><p>The midday temperatures in Grantford were recorded over a nine day period.<br>The temperatures, in °C, were<br><span class="text-xl font-mono">4&nbsp;&nbsp;7&nbsp;&nbsp;4&nbsp;&nbsp;3&nbsp;&nbsp;6&nbsp;&nbsp;10&nbsp;&nbsp;9&nbsp;&nbsp;5&nbsp;&nbsp;3</span><br><br><b>(a)</b>&nbsp;&nbsp;Calculate the median and semi-interquartile range for these temperatures.<br><br>Over the same nine day period the midday temperatures in Endoch were also recorded.<br>The median temperature was 8 °C, and the semi-interquartile range was 1.5 °C.<br><br><b>(b)</b>&nbsp;&nbsp;Make two valid comments comparing the midday temperatures of Grantford and Endoch during this period.</p>`, answer: `(a) Median = 5, SIQR = 2.25<br>(b) On average Endoch was warmer. Temperatures in Endoch were more consistent.`, videoId: "0ZcNrPB1w3s", timestamp: "293s", topics: ["Median/Quartiles/Interquartile Range", "Comparing Calculated Statistics"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q6</span></strong></small><p>The fuel consumption of a group of cars is recorded.<br>The scattergraph shows the relationship between the fuel consumption, \\(F\\) kilometres per litre, and the engine size, \\(E\\) litres, of the cars.</p><img src="/img/N5_Past_Papers/2019/2019_P1_Q6.png" alt="Scattergraph showing fuel consumption vs engine size"><p>A line of best fit has been drawn.<br><br><b>(a)</b>&nbsp;&nbsp;Find the equation of the line of best fit in terms of \\(F\\) and \\(E.\\) Give the equation in its simplest form.<br><br>Amaar’s car has an engine size of 1.1 litres.<br><b>(b)</b>&nbsp;&nbsp;Use your equation from part (a) to estimate how many kilometres per litre he should expect to get.</p>`, answer: `(a) \\(F=-3E+18.5\\), (b) 15.2`, videoId: "0ZcNrPB1w3s", timestamp: "519s", topics: ["Scatter Graph", "Straight Line Equation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q7</span></strong></small><p>The area of a trapezium is given by the formula<br>\\(A=\\frac{1}{2}h(x+y).\\)<br>Make \\(x\\) the subject of the formula.</p>`, answer: `\\(x=\\frac{2A}{h}-y\\)`, videoId: "0ZcNrPB1w3s", timestamp: "744s", topics: ["Changing the subject of a formula"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q8</span></strong></small><p>John bought 7 bags of cement and 3 bags of gravel.<br>The total weight of these bags was 215 kilograms.<br><b>(a)</b>&nbsp;&nbsp;Write down an equation to illustrate this information.<br><br>Shona bought 5 bags of cement and 4 bags of gravel.<br>The total weight of her bags was 200 kilograms.<br><b>(b)</b>&nbsp;&nbsp;Write down an equation to illustrate this information.<br><br><b>(c)</b>&nbsp;&nbsp;Calculate the weight of one bag of cement and the weight of one bag of gravel.</p>`, answer: `(a) \\(7c+3g=215\\), (b) \\(5c+4g=200\\), (c) Cement 20 kg, Gravel 25 kg`, videoId: "0ZcNrPB1w3s", timestamp: "833s", topics: ["Simultaneous equations"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q9</span></strong></small><p>The graph shows a parabola.</p><img src="/img/N5_Past_Papers/2019/2019_P1_Q9.png" alt="Parabola with turning point (4,20)"><p>The maximum turning point has coordinates (4, 20) as shown in the diagram.<br><br><b>(a)</b>&nbsp;&nbsp;Write down the equation of the axis of symmetry of the graph.<br><br>The equation of the parabola is of the form \\(y=b-(x+a)^{2}.\\)<br><b>(b)</b>&nbsp;&nbsp;State the values of (i) \\(a\\) and (ii) \\(b.\\)</p>`, answer: `(a) \\(x=4\\)<br>(b) (i) \\(a=-4\\), (ii) \\(b=20\\)`, videoId: "0ZcNrPB1w3s", timestamp: "966s", topics: ["Turning Points and Axis of Symmetry", "Parabola Equation from Graph"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q10</span></strong></small><p>In triangle PQR, \\(\\overrightarrow{PR}=\\begin{pmatrix}6\\\\ -4\\end{pmatrix}\\) and \\(\\overrightarrow{RQ}=\\begin{pmatrix}-1\\\\ 8\\end{pmatrix}.\\)</p><img src="/img/N5_Past_Papers/2019/2019_P1_Q10.png" alt="Triangle PQR vector diagram"><p><b>(a)</b>&nbsp;&nbsp;Express \\(\\overrightarrow{PQ}\\) in component form.<br><br>M is the midpoint of PR.<br><b>(b)</b>&nbsp;&nbsp;Express \\(\\overrightarrow{MQ}\\) in component form.</p>`, answer: `(a) \\(\\begin{pmatrix}5\\\\ 4\\end{pmatrix}\\), (b) \\(\\begin{pmatrix}2\\\\ 6\\end{pmatrix}\\)`, videoId: "0ZcNrPB1w3s", timestamp: "1009s", topics: ["Vector pathways", "Adding and Subtracting vector components"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q11</span></strong></small><p>Pam is designing a company logo.<br>She starts by drawing a regular pentagon ABCDE.<br>The vertices of the pentagon lie on the circumference of a circle with centre O.</p><img src="/img/N5_Past_Papers/2019/2019_P1_Q11_1.png" alt="Regular pentagon in a circle"><p>She then adds to the design as shown in the diagram below.</p><img src="/img/N5_Past_Papers/2019/2019_P1_Q11_2.png" alt="Pentagon with diameter AF added"><p>AF is a diameter of the circle.<br>Calculate the size of angle OFB.</p>`, answer: `36°`, videoId: "0ZcNrPB1w3s", timestamp: "1121s", topics: ["Angles in regular polygons", "Angles in diagrams involving circles"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q12</span></strong></small><p>Express \\(\\frac{\\sqrt{2}}{\\sqrt{40}}\\) as a fraction with a rational denominator.<br>Give your answer in its simplest form.</p>`, answer: `\\(\\frac{\\sqrt{5}}{10}\\)`, videoId: "0ZcNrPB1w3s", timestamp: "1214s", topics: ["Rationalising the denominator"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q13</span></strong></small><p>Part of the graph of \\(y=3\\cos(x+45)^{\\circ}\\) is shown in the diagram.</p><img src="/img/N5_Past_Papers/2019/2019_P1_Q13.png" alt="Graph of y=3cos(x+45)"><p>The graph has a minimum turning point at A.<br>State the coordinates of A.</p>`, answer: `(135, -3)`, videoId: "0ZcNrPB1w3s", timestamp: "1260s", topics: ["Identify equation of trigonometric graph"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q14</span></strong></small><p>Solve the equation \\(\\frac{x}{2}-1=\\frac{3-x}{5}.\\)</p>`, answer: `\\(x=\\frac{16}{7}\\)`, videoId: "0ZcNrPB1w3s", timestamp: "1311s", topics: ["Linear equations and inequations"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q15</span></strong></small><p>A ball is kicked from a clifftop.</p><img src="/img/N5_Past_Papers/2019/2019_P1_Q15_1.png" alt="Ball kicked from cliff"><p>The height, \\(h\\) metres, of the ball relative to the clifftop after \\(t\\) seconds is given by \\(h=12t-5t^{2}.\\)<br><b>(a)</b>&nbsp;&nbsp;Calculate the height of the ball above the clifftop after 2 seconds.<br><br>The graph below represents the height, \\(h\\) metres, of the ball relative to the clifftop after \\(t\\) seconds.</p><img src="/img/N5_Past_Papers/2019/2019_P1_Q15_2.png" alt="Graph of ball height"><p>The sea is 17 metres below the clifftop.<br><b>(b)</b>&nbsp;&nbsp;After how many seconds will the ball hit the sea?</p>`, answer: `(a) 4 metres, (b) 3.4 seconds`, videoId: "0ZcNrPB1w3s", timestamp: "1377s", topics: ["Quadratic equation by factorising"] }
            ]
        },
        {
            paperNumber: 2,
            questions: [
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q1</span></strong></small><p>A charity distributed 80 000 emergency packages during 2018.<br>This number is expected to increase by 15% each year.<br>Calculate how many emergency packages the charity expects to distribute in 2021.</p>`, answer: `121 670`, videoId: "mH8kVu6QMjU", timestamp: "0s", topics: ["Appreciation and Depreciation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q2</span></strong></small><p>Find \\(|\\mathbf{p}|\\), the magnitude of vector \\(\\mathbf{p}=\\begin{pmatrix}6\\\\ 27\\\\ -18\\end{pmatrix}.\\)</p>`, answer: `33`, videoId: "mH8kVu6QMjU", timestamp: "66s", topics: ["Magnitude"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q3</span></strong></small><p>The diagram shows triangle PQR.</p><img src="/img/N5_Past_Papers/2019/2019_P2_Q3.png" alt="Triangle PQR"><p>&bull;&nbsp;&nbsp;PR = 45 centimetres<br>&bull;&nbsp;&nbsp;PQ = 70 centimetres<br>&bull;&nbsp;&nbsp;Angle QPR = 129°<br>Calculate the area of triangle PQR.</p>`, answer: `1224 cm²`, videoId: "mH8kVu6QMjU", timestamp: "97s", topics: ["Area of a Triangle"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q4</span></strong></small><p>A sesame seed weighs \\(3\\cdot6\\times10^{-6}\\) kilograms.<br>The weight of a poppy seed is 8% of the weight of a sesame seed.<br>Calculate the weight of a poppy seed in kilograms.<br>Give your answer in scientific notation.</p>`, answer: `\\(2\\cdot88 \\times 10^{-7}\\) kg`, videoId: "mH8kVu6QMjU", timestamp: "157s", topics: ["Scientific notation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q5</span></strong></small><p>The diagram shows a cone with diameter 6 units and height 8 units.</p><img src="/img/N5_Past_Papers/2019/2019_P2_Q5.png" alt="Cone relative to coordinate axes"><p>&bull;&nbsp;&nbsp;The x-axis and the y-axis are tangents to the base<br>&bull;&nbsp;&nbsp;A is the point of contact between the base and the x-axis<br>&bull;&nbsp;&nbsp;B is directly above the centre of the base<br>Write down the coordinates of A and B.</p>`, answer: `A(3,0,0), B(3,3,8)`, videoId: "mH8kVu6QMjU", timestamp: "240s", topics: ["3d Coordinates"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q6</span></strong></small><p>Solve the equation \\(3x^{2}+9x-2=0.\\)<br>Give your answers correct to 1 decimal place.</p>`, answer: `\\(x=0.2, x=-3.2\\)`, videoId: "mH8kVu6QMjU", timestamp: "294s", topics: ["Quadratic formula"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q7</span></strong></small><p>Triangle XYZ is shown below.</p><img src="/img/N5_Past_Papers/2019/2019_P2_Q7.png" alt="Triangle XYZ with sides 6.3, 8.5, 7.2"><p>Calculate the size of the smallest angle in triangle XYZ.</p>`, answer: `46.4°`, videoId: "mH8kVu6QMjU", timestamp: "432s", topics: ["Cosine rule: calculate angle"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q8</span></strong></small><p>A traffic bollard is in the shape of a cylinder with a hemisphere on top.<br>The bollard has<br>&bull;&nbsp;&nbsp;diameter 24 centimetres<br>&bull;&nbsp;&nbsp;height 70 centimetres.<br>Calculate the volume of the bollard.<br>Give your answer correct to 3 significant figures.</p>`, answer: `29 900 cm³`, videoId: "mH8kVu6QMjU", timestamp: "561s", topics: ["Volume - composite shape"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q9</span></strong></small><p>Georgie had her roof repaired.<br>She was charged an extra 2.5% for late payment.<br>She had to pay a total of £977.85.<br>Calculate how much she would have saved if she had paid on time.</p>`, answer: `£23.85`, videoId: "mH8kVu6QMjU", timestamp: "734s", topics: ["Reversing a percentage change"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q10</span></strong></small><p>Express \\(x^{2}+10x-15\\) in the form \\((x+p)^{2}+q.\\)</p>`, answer: `\\((x+5)^{2}-40\\)`, videoId: "mH8kVu6QMjU", timestamp: "796s", topics: ["Completing the square"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q11</span></strong></small><p>The diagram shows the course for a jet-ski race.<br>The course is indicated by markers A, B and C.</p><img src="/img/N5_Past_Papers/2019/2019_P2_Q11.png" alt="Jet-ski course diagram"><p>The total length of the course is 1500 metres.<br>&bull;&nbsp;&nbsp;B is 600 metres from A<br>&bull;&nbsp;&nbsp;C is 650 metres from A<br>&bull;&nbsp;&nbsp;C is due north of B<br>Determine whether B is due east of A.<br>Justify your answer.</p>`, answer: `Yes, since \\(600^2 + 250^2 = 650^2\\) (Converse of Pythagoras)`, videoId: "mH8kVu6QMjU", timestamp: "844s", topics: ["Pythagoras converse"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q12</span></strong></small><p>In the diagram<br>&bull;&nbsp;&nbsp;ABC is a sector of a circle, centre C<br>&bull;&nbsp;&nbsp;DEF is a sector of a circle, centre F.<br>The sectors are mathematically similar.<br>The area of the larger sector, ABC, is 2750 square centimetres.<br><b>(a)</b>&nbsp;&nbsp;Calculate the area of the smaller sector, DEF.<br><b>(b)</b>&nbsp;&nbsp;Calculate the size of angle ACB.</p>`, answer: `(a) 990 cm², (b) 126°`, videoId: "mH8kVu6QMjU", timestamp: "953s", topics: ["Sector area", "Similar areas/volumes"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q13</span></strong></small><p>Find an expression for the gradient of the line joining point A(6,9) to point B(4p,4p²).<br>Give your answer in its simplest form.</p>`, answer: `\\(\\frac{2p+3}{2}\\)`, videoId: "mH8kVu6QMjU", timestamp: "1105s", topics: ["Straight Line Equation", "Simplifying algebraic fraction"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q14</span></strong></small><p>Solve the equation \\(5\\cos x^{\\circ}+2=1\\), for \\(0\\le x<360.\\)</p>`, answer: `\\(x=101.5, 258.5\\)`, videoId: "mH8kVu6QMjU", timestamp: "1211s", topics: ["Trigonometric equation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q15</span></strong></small><p>Express \\(\\frac{4}{x-2}-\\frac{3}{x+5}\\), \\(x\\ne2, x\\ne-5\\), as a single fraction in its simplest form.</p>`, answer: `\\(\\frac{x+26}{(x-2)(x+5)}\\)`, videoId: "mH8kVu6QMjU", timestamp: "1291s", topics: ["Add or subtract Algebraic Fractions"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q16</span></strong></small><p>Simplify \\(\\frac{a^{4}\\times3a}{\\sqrt{a}}.\\)</p>`, answer: `\\(3a^{4.5}\\) or \\(3a^{\\frac{9}{2}}\\)` , videoId: "mH8kVu6QMjU", timestamp: "1401s", topics: ["Laws of indices"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q17</span></strong></small><p>Expand and simplify \\((\\sin x^{\\circ}+\\cos x^{\\circ})^{2}.\\)<br>Show your working.</p>`, answer: `\\(1+2\\sin x^{\\circ}\\cos x^{\\circ}\\)`, videoId: "mH8kVu6QMjU", timestamp: "1483s", topics: ["Trigonometric identities", "Expanding brackets"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q18</span></strong></small><p>The picture shows a cartoon snowman.</p><img src="/img/N5_Past_Papers/2019/2019_P2_Q18_1.png" alt="Cartoon snowman"><p>The diagram below represents the snowman.</p><img src="/img/N5_Past_Papers/2019/2019_P2_Q18_2.png" alt="Geometric diagram of snowman"><p>&bull;&nbsp;&nbsp;The head is a small circle, centre S, with diameter 15 centimetres<br>&bull;&nbsp;&nbsp;The body is part of a larger circle, centre T<br>&bull;&nbsp;&nbsp;The point T lies on the circumference of the small circle<br>&bull;&nbsp;&nbsp;The points A and B lie on the circumferences of both circles<br>Calculate CD, the height of the snowman.</p>`, answer: `25.6 cm`, videoId: "mH8kVu6QMjU", timestamp: "1561s", topics: ["Pythagoras in circle diagrams"] },
                { question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q19</span></strong></small><p>Katy and Mona are looking up at a hot-air balloon.<br>In the diagram below, K, M and B represent the positions of Katy, Mona and the balloon respectively.</p><img src="/img/N5_Past_Papers/2019/2019_P2_Q19.png" alt="Triangulation diagram for hot air balloon"><p>&bull;&nbsp;&nbsp;The angle of elevation of the balloon from Katy is 52°<br>&bull;&nbsp;&nbsp;The angle of elevation of the balloon from Mona is 34°<br>&bull;&nbsp;&nbsp;Katy and Mona are 350 metres apart on level ground<br>Calculate the height of the hot-air balloon above the ground.</p>`, answer: `154.6 m`, videoId: "mH8kVu6QMjU", timestamp: "1673s", topics: ["Sine rule: calculate length"] }
            ]
        }
    ]
};