export const pastpaper2015 = {
    year: 2015,
    papers: [
        {
            paperNumber: 1,
            questions: [
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q1</span></strong></small><br>Evaluate \\(6 \\frac{1}{5}-2\\frac{1}{3}.\\)`, answer: `\\(3 \\frac{13}{15}\\)`, videoId: "TKdgtBFRXJY", timestamp: "0s", topics: ["Fractions and mixed numbers"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q2</span></strong></small><p>Solve algebraically the inequality<br> \\(11-2(1+3x)\\lt 39\\)</p>`, answer: `\\(x \\gt -5\\)`, videoId: "TKdgtBFRXJY", timestamp: "67s", topics: ["Linear equations and inequations"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q3</span></strong></small><p>AC is a tangent to the circle, centre O, with point of contact B.<br>DE is a diameter of the circle and F is a point on the circumference.<br>Angle ABD is <span style="white-space: nowrap;">77&deg;</span> and angle DEF is <span style="white-space: nowrap;">64&deg;.</span></p><img src="/img/N5_Past_Papers/2015/2015_P1_Q3.png" alt="Circle with tangent and diameter"><p>Calculate the size of angle BDF.</p>`, answer: `39°`, videoId: "TKdgtBFRXJY", timestamp: "154s", topics: ["Angles in diagrams involving circles"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q4</span></strong></small><p>Multiply out the brackets and collect like terms: \\((x-4)(x^2+x-2)\\)</p>`, answer: `\\(x^3-3x^2-6x+8\\)`, videoId: "TKdgtBFRXJY", timestamp: "313s", topics: ["Expanding brackets"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q5</span></strong></small><p>The standard deviation of 1, 2, 2, 2, 8 is equal to \\(\\sqrt{a}.\\) Find the value of a.</p>`, answer: `\\(a=8\\)`, videoId: "TKdgtBFRXJY", timestamp: "394s", topics: ["Standard Deviation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q6</span></strong></small><p>Part of the graph of \\(y=a\\sin bx^\\circ\\) is shown in the diagram.</p><img src="/img/N5_Past_Papers/2015/2015_P1_Q6.png" alt="Graph of y=a sin bx"><p>State the values of \\(a\\) and \\(b.\\)</p>`, answer: `\\(a=4, b=3\\)`, videoId: "TKdgtBFRXJY", timestamp: "566s", topics: ["Identify equation of trigonometric graph"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q7</span></strong></small><p>The graph shows part of the parabola with equation of the form \\(y=(x+a)^{2}+b.\\)</p><img src="/img/N5_Past_Papers/2015/2015_P1_Q7.png" alt="Parabola with minimum turning point (2, -4)"><p>The minimum turning point \\((2,-4)\\) is shown.<br><br><b>(a)</b>&nbsp;&nbsp;State the values of (i) \\(a\\) and (ii) \\(b.\\)<br><br><b>(b)</b>&nbsp;&nbsp;Write down the equation of the axis of symmetry of the graph.</p>`, answer: `(a)(i) \\(a=-2\\), (ii) \\(b=-4\\), (b) \\(x=2\\)`, videoId: "TKdgtBFRXJY", timestamp: "628s", topics: ["Parabola Equation from Graph", "Turning Points and Axis of Symmetry"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q8</span></strong></small><p>Find the equation of the line joining the points \\((-2,5)\\) and \\((3,15).\\)<br>Give the equation in its simplest form.</p>`, answer: `\\(y=2x+9\\)`, videoId: "TKdgtBFRXJY", timestamp: "717s", topics: ["Straight Line Equation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q9</span></strong></small><p>Write the following in order of size starting with the smallest:<br>\\(\\cos 90^{\\circ}\\), \\(\\cos 100^{\\circ}\\), \\(\\cos 300^{\\circ}\\)<br><br>Justify your answer.</p>`, answer: `\\(\\cos 100^{\\circ}\\), \\(\\cos 90^{\\circ}\\), \\(\\cos 300^{\\circ}\\)`, videoId: "TKdgtBFRXJY", timestamp: "770s", topics: ["sin/cos/tan of related angles"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q10</span></strong></small><p>Ten couples took part in a dance competition. The scores in the first round were:<br><span class="text-xl font-mono">16&nbsp;&nbsp;27&nbsp;&nbsp;12&nbsp;&nbsp;18&nbsp;&nbsp;26&nbsp;&nbsp;21&nbsp;&nbsp;27&nbsp;&nbsp;22&nbsp;&nbsp;18&nbsp;&nbsp;17</span><br><br><b>(a)</b>&nbsp;&nbsp;Calculate the median and semi-interquartile range of these scores.<br><br><b>(b)</b>&nbsp;&nbsp;In the second round, the median was 26 and the semi-interquartile range was 2.5. Make two valid comparisons between the scores in the first and second rounds.</p>`, answer: `(a) Median = 19.5, SIQR = 4.5, (b) On average the second round's scores are higher. The second round's scores are more consistent.`, videoId: "TKdgtBFRXJY", timestamp: "928s", topics: ["Median/Quartiles/Interquartile Range", "Comparing Calculated Statistics"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q11</span></strong></small><p>Solve algebraically the system of equations</p><p>$$\\begin{aligned} 3x + 2y &= 17 \\\\ 2x + 5y &= 4 \\end{aligned}$$</p>`, answer: `\\(x=7, y=-2\\)`, videoId: "TKdgtBFRXJY", timestamp: "1153s", topics: ["Simultaneous equations"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q12</span></strong></small><p>Simplify \\(\\large\\frac{x^{2}-4x}{x^{2}+x-20}.\\)</p>`, answer: `\\(\\frac{x}{x+5}\\)`, videoId: "TKdgtBFRXJY", timestamp: "1291s", topics: ["Simplifying algebraic fraction", "Factorising"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q13</span></strong></small><p>Express \\(\\large\\frac{4}{\\sqrt{8}}\\) with a rational denominator.<br>Give your answer in its simplest form.</p>`, answer: `\\(\\sqrt{2}\\)`, videoId: "TKdgtBFRXJY", timestamp: "1397s", topics: ["Rationalising the denominator"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P1 Q14</span></strong></small><br>Evaluate \\( 8^{\\frac53}.\\)`, answer: `32`, videoId: "TKdgtBFRXJY", timestamp: "1466s", topics: ["Evaluating a fractional or negative index numerically"] }
            ]
        },
        {
            paperNumber: 2,
            questions: [
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q1</span></strong></small><p>A house is valued at £240 000. Its value is predicted to rise by 2.8% per annum.<br>Calculate its predicted value after 2 years.</p>`, answer: `£253,628`, videoId: "3qKFGh3k8ok", timestamp: "0s", topics: ["Appreciation and Depreciation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q2</span></strong></small><p>A function is defined as <span style="white-space: nowrap;">\\(f(x)=3x+2.\\)</span><br>Given that \\(f(a)=23\\), find <span style="white-space: nowrap;">\\(a.\\)</span></p>`, answer: `\\(a = 7\\)`, videoId: "3qKFGh3k8ok", timestamp: "85s", topics: ["Function notation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q3</span></strong></small><p>Triangle ABC is shown below.</p><img src="/img/N5_Past_Papers/2015/2015_P2_Q3.png" alt="Triangle ABC with side lengths and angle"><p>Calculate the length of AB.</p>`, answer: `0.78 km`, videoId: "3qKFGh3k8ok", timestamp: "106s", topics: ["Cosine rule: calculate length"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q4</span></strong></small><p>Find \\(|\\mathbf{u}|\\), the magnitude of vector \\(\\mathbf{u}=\\begin{pmatrix}6\\\\-13\\\\18\\end{pmatrix}.\\)</p>`, answer: `23`, videoId: "3qKFGh3k8ok", timestamp: "235s", topics: ["Magnitude"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q5</span></strong></small><p>The vectors \\(\\mathbf{p}\\) and \\(\\mathbf{q}\\) are shown in the diagram.</p><img src="/img/N5_Past_Papers/2015/2015_P2_Q5.png" alt="Vectors p and q on a grid"><p>Find the resultant vector \\(\\mathbf{p}+\\mathbf{q}.\\)<br>Express your answer in component form.</p>`, answer: `\\(\\begin{pmatrix}-1\\\\-2\\end{pmatrix}\\)`, videoId: "3qKFGh3k8ok", timestamp: "280s", topics: ["Adding and Subtracting vector components"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q6</span></strong></small><p>The Earth is approximately spherical with a radius of 6400 kilometres.</p><img src="/img/N5_Past_Papers/2015/2015_P2_Q6.png" alt="Sphere representing Earth"><p><b>(a)</b>&nbsp;&nbsp;Calculate the volume of the Earth giving your answer in scientific notation, correct to 2 significant figures.<br><br><b>(b)</b>&nbsp;&nbsp;The approximate volume of the Moon is \\(2.2\\times10^{10}\\) cubic kilometres. Calculate how many times the Earth's volume is greater than the Moon's.</p>`, answer: `(a) \\(1.1\\times10^{12}\\) km³, (b) 50`, videoId: "3qKFGh3k8ok", timestamp: "368s", topics: ["Volume - simple shape", "Scientific notation"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q7</span></strong></small><p>Express \\( \\large\\frac{5t}{s} \\normalsize \\div \\large \\frac{t}{2s^2} \\)<br>in its simplest form.</p>`, answer: `\\(10s\\)`, videoId: "3qKFGh3k8ok", timestamp: "471s", topics: ["Multiply or divide Algebraic Fractions"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q8</span></strong></small><p>James paid £297.50 for a laptop in a sale. The discount in the sale was 15%.<br>Calculate the original price of the laptop.</p>`, answer: `£350`, videoId: "3qKFGh3k8ok", timestamp: "505s", topics: ["Reversing a percentage change"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q9</span></strong></small><p>The flag at each hole on a golf course is coloured red and blue.<br>                  The diagram below represents a flag.<br>                  Triangle QRT represents the red section.<br>                  PQTS represents the blue section.</p><img src="/img/N5_Past_Papers/2015/2015_P2_Q9.png" alt="Golf flag with red and blue sections"><p>Triangles PRS and QRT are mathematically similar.<br>                  The area of triangle QRT is 400 square centimetres.<br>                  Calculate the area of PQTS, the blue section of the flag.</p>`, answer: `225 cm²`, videoId: "3qKFGh3k8ok", timestamp: "583s", topics: ["Similar lengths", "Similar areas/volumes"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q10</span></strong></small><p>The pendulum of a clock swings along an arc of a circle, centre O.</p><img src="/img/N5_Past_Papers/2015/2015_P2_Q10.png" alt="Pendulum swinging along an arc"><p>The pendulum swings through an angle of 65&deg;, travelling from A to B.<br>                  The length of the arc AB is 28.4 centimetres.<br>                  Calculate the length of the pendulum.</p>`, answer: `\\(r \\approx 25.0\\) cm`, videoId: "3qKFGh3k8ok", timestamp: "703s", topics: ["Arc length"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q11</span></strong></small><p>The top of a table is in the shape of a regular hexagon. The three diagonals of the hexagon which are shown as dotted lines in the diagram below each have length 40 centimetres.</p><img src="/img/N5_Past_Papers/2015/2015_P2_Q11.png" alt="Regular hexagon with diagonals"><p>Calculate the area of the top of the table.</p>`, answer: `\\(1039.2\\) cm²`, videoId: "3qKFGh3k8ok", timestamp: "853s", topics: ["Area of a Triangle"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q12</span></strong></small><p>The diagram below shows the circular cross-section of a milk tank.</p><img src="/img/N5_Past_Papers/2015/2015_P2_Q12.png" alt="Circular cross-section of a milk tank"><p>The radius of the circle, centre O, is <span style="white-space: nowrap;">1.2 metres.</span><br>                  The width of the surface of the milk in the tank, represented by ML in the diagram, is <span style="white-space: nowrap;">1.8 metres.</span><br>                  Calculate the depth of the milk in the tank.</p>`, answer: `1.99 metres`, videoId: "3qKFGh3k8ok", timestamp: "969s", topics: ["Pythagoras in circle diagrams"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q13</span></strong></small><p>In the diagram below P, Q and R represent the positions of Portlee, Queenstown and Rushton respectively.</p><img src="/img/N5_Past_Papers/2015/2015_P2_Q13.png" alt="Map of Portlee, Queenstown, Rushton"><p>Portlee is 25 kilometres due South of Queenstown.<br>                  From Portlee, the bearing of Rushton is 072&deg;.<br>                  From Queenstown, the bearing of Rushton is 128&deg;.<br>                  Calculate the distance between Portlee and Rushton.<br>                  Do not use a scale drawing.</p>`, answer: `23.8 km`, videoId: "3qKFGh3k8ok", timestamp: "1101s", topics: ["Sine rule: calculate length", "Bearings in Trigonometry questions"] },
                { question: `<small><strong><span style="white-space: nowrap;">2015 P2 Q14</span></strong></small><p>A rectangular picture measuring 9 centimetres by 13 centimetres is placed on a rectangular piece of card.</p><img src="/img/N5_Past_Papers/2015/2015_P2_Q14.png" alt="Rectangular picture with border x cm wide"><p>There is a border \\(x\\) centimetres wide on all sides of the picture.<br><br><b>(a)</b>&nbsp;&nbsp;(i) Write down an expression for the length of the card in terms of \\(x.\\)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ii) Hence show that \\(4x^{2}+44x-153=0.\\)<br><br><b>(b)</b>&nbsp;&nbsp;Calculate \\(x\\), the width of the border. Give your answer correct to one decimal place.</p>`, answer: `(a)(i) \\(2x+13\\), (ii) Shown, (b) \\(x=2.8\\) cm`, videoId: "3qKFGh3k8ok", timestamp: "1360s", topics: ["Create equation in geometric context", "Quadratic formula"] }
            ]
        }
    ]
};