/**
 * **Never the paper's own question** — the owner's rule, 2026-10-07: "the exam paper question never appears
 * in a draw. This should be for the exact exam paper question, if one thing changes - it can appear in a
 * draw." A teacher sets generated questions as homework, and a pupil who meets the paper's own question can
 * follow its video walkthrough to the answer.
 *
 * `paperQuestionOf` says whether a generated N5 question IS a past paper question, by the owner's finished
 * "same question" test (`../same-question.ts`): the same numbers and maths, whatever the story, the letters or
 * the order of things that can be swapped. `generateQuestion` draws again when it is (see generator.ts), so a
 * draw that is not a paper question is exactly what it was, and uses no extra randomness.
 *
 * The table (`paper-guard-keys.ts`, generated by `scripts/emit-paper-guard.mts`) holds every key the paper
 * questions' disguises produced in the harvest: every N5 card drawn, each paper question found as the
 * owner's sheets found it, and every disguise joined to it by the test. Keys are hashed, so it is small.
 */
import { PAPER_GUARD } from './paper-guard-keys';
import { sameQuestionKey, sameWorkingKey, answerFingerprint, shortHash } from '../same-question';
import type { GeneratedQuestion } from './types';

const FINGERPRINTS = new Set<string>(PAPER_GUARD.fingerprints);
const KEYS = new Map<string, string>(Object.entries(PAPER_GUARD.keys));

/** The paper label a generated question is, or null. Cheap for nearly every draw: the answer is checked first. */
export function paperQuestionOf(q: Partial<GeneratedQuestion>): string | null {
  const answer = q.finalAnswer ?? '';
  if (!FINGERPRINTS.has(shortHash(answerFingerprint(answer)))) return null;
  const lines = q.questionLines ?? [];
  const byWording = KEYS.get(shortHash(`Q:${sameQuestionKey(lines, answer)}`));
  if (byWording) return byWording;
  const w = sameWorkingKey(lines, answer, q.solutionSteps ?? []);
  return w ? KEYS.get(shortHash(w)) ?? null : null;
}

/** How many draws in a row may be a paper question before the guard gives up loudly (no card comes close). */
export const GUARD_LIMIT = 200;
