/**
 * What each mark is for, on a past paper question.
 *
 * **Generated — do not edit.** Run \`npx tsx scripts/emit-paper-steps.ts\`, and
 * \`__checks__/paper-steps.ts\` fails if this file and the marking instructions
 * disagree.
 *
 * Transcribed from the published marking instructions, one entry per mark, in
 * the scheme's own order. This is the **generic scheme** column: what the mark
 * is for, never the answer it wants. The illustrative column — the answer for
 * each mark — is deliberately not here.
 *
 * Contains information reproduced from Qualifications Scotland marking
 * instructions, on a non-commercial basis, with Qualifications Scotland
 * acknowledged as the source.
 *
 * No imports, deliberately: a pupil asking for a hint should not download the
 * 33,000-line engine to read one line of text.
 */
export const PAPER_STEPS: Record<string, string[]> = {
  "2014 P1 Q1": ["start to multiply fractions","consistent answer in simplest form"],
  "2014 P1 Q2": ["any three terms correct","fourth term correct and collect like terms"],
  "2014 P1 Q3": ["correct bracket with square","complete process"],
  "2014 P1 Q4": ["calculate \\(2\\mathbf{u}\\)","solution"],
  "2014 P1 Q5": ["correct substitution into sine rule","know how to solve","correct calculation"],
  "2014 P1 Q6": ["find gradient","substitute gradient and a point","calculate \\(c\\) / expand and state equation in simplest form","calculate value using the equation"],
  "2014 P1 Q7": ["know to substitute \\((-3, 45)\\) into \\(y = ax^2\\)","solve equation for \\(a\\)"],
  "2014 P1 Q8": ["simplify \\(\\sqrt{40}\\)","simplify \\(\\sqrt{90}\\)","state answer in simplest form"],
  "2014 P1 Q9": ["know that \\(80\\% = 480 000\\)","begin valid strategy","answer"],
  "2014 P1 Q10": ["state value of \\(a\\)","state value of \\(b\\)"],
  "2014 P1 Q11": ["start to rearrange","state gradient","know how to find x-coordinate","state coordinates"],
  "2014 P1 Q12": ["marshal facts and recognise right angle","know how to use Pythagoras","correct calculation of \\(PA^2\\)","find length of PQ"],
  "2014 P1 Q13": ["construct an equation","rearrange and equate to zero","correct factorisation","solve equation and select correct value","turning point / calculate \\(h(8)\\) / evidence of using \\(b^2-4ac\\)","calculate max height / demonstrate max / calculate \\(b^2-4ac\\)","communicate conclusion"],
  "2014 P2 Q1": ["know how to decrease by 15%","know how to calculate roll","carry out calculations correctly within a valid strategy and round to the nearest ten"],
  "2014 P2 Q2": ["state coordinates of B","state coordinates of C"],
  "2014 P2 Q3": ["construct equation","construct equation","evidence of scaling","follow a valid strategy through to produce values for \\(a\\) and \\(c\\)","calculate correct values for \\(a\\) and \\(c\\)","communicate answers in money"],
  "2014 P2 Q4": ["calculate mean","calculate \\((x - \\overline{x})^2\\) / find \\(\\sum x\\) and \\(\\sum x^2\\)","substitute into formula","calculate standard deviation","no, with valid explanation"],
  "2014 P2 Q5": ["state linear scale factor","state volume scale factor","calculate volume and state correct units"],
  "2014 P2 Q6": ["valid strategy","evaluation","comparison","valid conclusion"],
  "2014 P2 Q7": ["substitute correctly into formula for volume of cone","substitute correctly into formula for volume of sphere or hemisphere","know to subtract volume of hemisphere from volume of cone","carry out all calculations correctly","round final answer to 2 significant figures"],
  "2014 P2 Q8": ["simplify powers in numerator","cancel constants","eliminate \\(n\\) from denominator"],
  "2014 P2 Q9": ["correct common denominator (or correct numerator)","consistent numerator (or denominator)","simplify"],
  "2014 P2 Q10": ["substitute correctly into cosine rule","calculate \\(\\cos B\\) correctly","calculate angle ABC correctly","know how to calculate the angle","correctly calculate the angle within a valid strategy"],
  "2014 P2 Q11": ["subtract \\(ut\\)","multiply by 2","divide by \\(t^2\\)"],
  "2014 P2 Q12": ["rearrange equation","find one value of \\(x\\)","find another value of \\(x\\)"],
  "2014 P2 Q13": ["know how to find area of segment","know to express sector as a fraction of a circle","know how to find area of sector","know how to calculate area of triangle","carry out all calculations correctly within a valid strategy"],
  "2015 P1 Q1": ["correct common denominator","correct answer"],
  "2015 P1 Q2": ["multiply out bracket","collect like terms","solve for \\(x\\)"],
  "2015 P1 Q3": ["calculate the size of angle OBD","calculate the size of angle EDF","calculate the size of angle BDF"],
  "2015 P1 Q4": ["start to multiply out brackets","complete multiplying out brackets","collect like terms which must include a term in \\(x^3\\)"],
  "2015 P1 Q5": ["find \\(\\overline{x}\\) and \\((x - \\overline{x})^2\\) / find \\(\\sum x\\) and \\(\\sum x^2\\)","substitute into formula for \\(a\\)","calculate value of \\(a\\)"],
  "2015 P1 Q6": ["state the value of \\(a\\)","state the value of \\(b\\)"],
  "2015 P1 Q7": ["(i) state value of \\(a\\)","(ii) state value of \\(b\\)","state equation of axis of symmetry"],
  "2015 P1 Q8": ["find gradient","substitute gradient and a point into \\(y - b = m(x - a)\\) or \\(y = mx + c\\)","state equation of the line in terms of \\(y\\) and \\(x\\) in its simplest form"],
  "2015 P1 Q9": ["state correct order","justification stated explicitly"],
  "2015 P1 Q10": ["find median","find quartiles","calculate semi-interquartile range","compare medians","compare semi-interquartile ranges"],
  "2015 P1 Q11": ["evidence of scaling","follow a valid strategy through to produce values \\(x\\) and \\(y\\)","calculate correct values for \\(x\\) and \\(y\\)"],
  "2015 P1 Q12": ["factorise numerator","factorise denominator","cancel brackets correctly"],
  "2015 P1 Q13": ["express as equivalent fraction with rational denominator / manipulate surds","manipulate surds / express as equivalent fraction with rational denominator","consistent answer"],
  "2015 P1 Q14": ["interpret index","complete evaluation"],
  "2015 P2 Q1": ["know how to increase by 2.8%","know how to calculate expected turnover","carry out calculations correctly within a valid strategy"],
  "2015 P2 Q2": ["valid strategy","state value of \\(a\\)"],
  "2015 P2 Q3": ["correct substitution into cosine rule","evaluate \\(AB^2\\)","calculate \\(AB\\)"],
  "2015 P2 Q4": ["start process","solution"],
  "2015 P2 Q5": ["state components of either vector \\(\\mathbf{p}\\) or vector \\(\\mathbf{q}\\)","state components of vector \\(\\mathbf{p+q}\\)"],
  "2015 P2 Q6": ["substitute radius into volume of a sphere formula","evaluate volume","round volume to 2 significant figures","know to divide earth volume by moon volume","divide correctly"],
  "2015 P2 Q7": ["know how to start division calculation","continue process","express in simplest form"],
  "2015 P2 Q8": ["know that \\(85\\% = £297.50\\)","begin valid strategy","answer"],
  "2015 P2 Q9": ["linear scale factor","know how to find area of triangle PRS","find area of triangle PRS","find area of quadrilateral PQTS"],
  "2015 P2 Q10": ["correct fraction of circle","construct equation","know how to solve equation","solve equation and calculate length of the pendulum"],
  "2015 P2 Q11": ["correct angle","correct substitution into area of triangle formula","know how to find area of hexagon","correct calculation and correct units"],
  "2015 P2 Q12": ["marshal facts and recognize right-angle","correct Pythagoras statement","correct calculation of \\(x\\)","find depth of milk"],
  "2015 P2 Q13": ["calculate the size of angle POR","correct substitution into sine rule","know how to solve equation","calculate PR correctly"],
  "2015 P2 Q14": ["correct expression","find expression for area of card and expand pair of brackets","construct equation and rearrange into required form","correct substitution into quadratic formula","evaluate discriminant","solve for \\(x\\)","select positive value of \\(x\\), correctly stated to 1 decimal place"],
  "2016 P1 Q1": ["calculate \\(\\frac{1}{2}\\mathbf{p}\\)","solution"],
  "2016 P1 Q2": ["start the calculation correctly","consistent answer in simplest form"],
  "2016 P1 Q3": ["appropriate fraction","correct substitution into area of sector formula","calculate area of sector"],
  "2016 P1 Q4": ["construct equation","construct equation","evidence of scaling","follow a valid strategy through to produce values for \\(c\\) and \\(d\\)","calculate correct values for \\(c\\) and \\(d\\)","communicate answers in square metres"],
  "2016 P1 Q5": ["gradient","substitute gradient and a point into \\(y = mx + c\\) or \\(y - b = m(x - a)\\)","state equation in terms of \\(W\\) and \\(A\\) and in simplest form","calculate weight using equation from part (a)"],
  "2016 P1 Q6": ["find discriminant","state nature of roots"],
  "2016 P1 Q7": ["state coordinates of B","know how to find \\(AM^2\\)","know how to find \\(AV\\)","find length of AV"],
  "2016 P1 Q8": ["multiply throughout by 6 / rearrange","rearrange / start to solve for \\(x\\)","solve for \\(x\\)"],
  "2016 P1 Q9": ["correct substitution","consistent answer"],
  "2016 P1 Q10": ["coordinates of turning point correct","sketch parabola with minimum turning point consistent with •¹","y-intercept correct"],
  "2016 P1 Q11": ["identify correct trigonometric identity to be used","use correct trigonometric identity to simplify expression"],
  "2016 P1 Q12": ["find an expression for the area of the rectangle","find expanded expression for area of the rectangle","find expanded expression for area of the triangle","equate expanded expressions and rearrange into required form","factorise \\(x^2 - 2x - 8\\)","solve equation","reject invalid value of \\(x\\) and state length and breadth of rectangle"],
  "2016 P2 Q1": ["know how to decrease by 8%","know how to calculate the sugar content after 3 years","evaluate"],
  "2016 P2 Q2": ["correct method","answer"],
  "2016 P2 Q3": ["correct answer"],
  "2016 P2 Q4": ["begin to factorise","factorise fully"],
  "2016 P2 Q5": ["calculate the size of angle AOE or CAO","calculate the size of angle CAB","calculate the size of angle ABC"],
  "2016 P2 Q6": ["calculate mean","calculate \\((x - \\overline{x})^2\\)","substitute into formula","calculate standard deviation","compare means","compare standard deviations"],
  "2016 P2 Q7": ["know to find difference in two volumes","substitute correctly into formula for volume of large cone","substitute correctly into formula for volume of small cone","carry out all calculations correctly","round final answer to 2 significant figures and state correct units"],
  "2016 P2 Q8": ["correct substitution into sine rule","re-arrange formula","find \\(x\\)"],
  "2016 P2 Q9": ["correct bracket with square","complete process"],
  "2016 P2 Q10": ["simplify \\((n^2)^3\\)","simplify \\(n^6 \\times n^{-10}\\)","express with a positive power"],
  "2016 P2 Q11": ["linear scale factor","know to multiply / divide cost by square of linear scale factor","find cost of smaller picture"],
  "2016 P2 Q12": ["square","add \\(p\\)","divide by \\(4t\\)"],
  "2016 P2 Q13": ["correct denominator","correct numerator","remove brackets and collect like terms in numerator"],
  "2016 P2 Q14": ["rearrange equation","find one value of \\(x\\)","find another value of \\(x\\)"],
  "2016 P2 Q15": ["marshal facts and recognise right-angled triangle","correct Pythagoras statement","correct calculation of \\(x\\)","find height of label"],
  "2016 P2 Q16": ["identify \\(\\cos A\\) or angle A","substitute into cosine rule","calculate \\(BC^2\\)","calculate \\(BC\\) correct to one decimal place"],
  "2017 P1 Q1": ["substitute into \\(x^2 + 3x\\)","evaluate \\(x^2 + 3x\\)"],
  "2017 P1 Q2": ["find quartiles","calculate semi-interquartile range"],
  "2017 P1 Q3": ["start simplification and know how to divide fractions","consistent answer"],
  "2017 P1 Q4": ["start to expand","complete expansion","collect like terms which must include a term in \\(x^3\\) and a negative coefficient"],
  "2017 P1 Q5": ["Coordinate B","Coordinate C"],
  "2017 P1 Q6": ["find gradient","substitute gradient and a point","state equation in simplest form"],
  "2017 P1 Q7": ["correct substitution into area of triangle formula","calculate area"],
  "2017 P1 Q8": ["expand bracket","collect like terms","solve for \\(x\\)"],
  "2017 P1 Q9": ["calculate size of angle OBD / ABC","calculate size of angle ODB / OCB","calculate size of angle CAB"],
  "2017 P1 Q10": ["multiply by \\(c\\)","subtract \\(t^2\\)","divide by \\(4\\)"],
  "2017 P1 Q11": ["valid common denominator","answer in simplest form"],
  "2017 P1 Q12": ["find \\(\\overline{x}\\) / find \\(\\sum x\\) and \\(\\sum x^2\\)","find \\((x - \\overline{x})^2\\) / substitute into formula","substitute into formula and start to evaluate","find values of \\(a\\) and \\(b\\)"],
  "2017 P1 Q13": ["evidence of scaling (match \\(x\\) or \\(y\\) coefficients)","follow a valid strategy through to produce values for \\(x\\) and \\(y\\)","state correct \\(x\\) and \\(y\\) coordinates of P"],
  "2017 P1 Q14": ["state value of \\(a\\)","substitute \\((-3, 8)\\) into equation","state value of \\(b\\)"],
  "2017 P1 Q15": ["find scale factor","form equation / start to solve","find \\(x\\)"],
  "2017 P2 Q1": ["start process","solution"],
  "2017 P2 Q2": ["know how to increase by 4.5%","know how to calculate value after three years","evaluate to nearest £"],
  "2017 P2 Q3": ["correct substitution into cosine rule","evaluate \\(QR^2\\)","calculate \\(QR\\)"],
  "2017 P2 Q4": ["substitute correctly into quadratic formula","evaluate discriminant","calculate both values of \\(x\\) correct to one decimal place"],
  "2017 P2 Q5": ["know that \\(115\\% = 4830\\)","begin valid strategy","complete calculation within valid strategy"],
  "2017 P2 Q6": ["evidence of difference in two volumes","substitute correctly into formula for volume of large sphere","substitute correctly into formula for volume of small sphere","carry out all calculations correctly","round final answer to 3 significant figures and correct units"],
  "2017 P2 Q7": ["valid strategy (Converse of Pythagoras in correct triangle)","evaluation","comparison and state conclusion"],
  "2017 P2 Q8": ["answer","valid pathway","correct simplified expression"],
  "2017 P2 Q9": ["factorise","start to factorise","complete factorising","simplify"],
  "2017 P2 Q10": ["calculate size of angles DEF and DFE","correct substitution into sine rule","rearrange formula","calculate DF"],
  "2017 P2 Q11": ["isolate term in \\(y\\) or divide throughout by 5","state gradient explicitly"],
  "2017 P2 Q12": ["apply \\(\\sqrt[n]{x^m} = x^{\\frac{m}{n}}\\)","apply \\(\\frac{1}{x^n} = x^{-n}\\)"],
  "2017 P2 Q13": ["marshal facts and recognise right-angled triangle","consistent Pythagoras statement","calculation of \\(x\\)","find height of the logo"],
  "2017 P2 Q14": ["expression for arc length / ratio","know how to find angle","calculate angle"],
  "2017 P2 Q15": ["calculate height","calculate minimum height","substitute 61 correctly into equation","calculate \\(\\cos x\\)","calculate value of \\(x\\)","calculate 2nd value of \\(x\\)"],
  "2018 P1 Q1": ["identify common denominator","answer"],
  "2018 P1 Q2": ["start expansion","complete expansion","collect like terms"],
  "2018 P1 Q3": ["evidence of scaling (match \\(x\\) or \\(y\\) coefficients)","follow a valid strategy through to produce values for \\(x\\) and \\(y\\)","calculate correct values for \\(x\\) and \\(y\\)"],
  "2018 P1 Q4": ["evidence of subtraction","all components correct"],
  "2018 P1 Q5": ["correct factorisation","solve for \\(x\\)"],
  "2018 P1 Q6": ["state the value of \\(a\\)","state the value of \\(b\\)"],
  "2018 P1 Q7": ["calculate gradient","substitute gradient and a point","state equation in simplest form in terms of \\(P\\) and \\(d\\)","calculate cost"],
  "2018 P1 Q8": ["find discriminant","state nature of roots"],
  "2018 P1 Q9": ["calculate the size of an interior angle of the decagon or angle JKL","calculate the size of angle KJL"],
  "2018 P1 Q10": ["correct substitution into cosine rule","calculate \\(XY^2\\)","calculate \\(XY\\)"],
  "2018 P1 Q11": ["express as equivalent fraction with rational denominator","express in simplest form"],
  "2018 P1 Q12": ["state value"],
  "2018 P1 Q13": ["state coordinates of B","state coordinates of C"],
  "2018 P1 Q14": ["subtract \\(h\\)","divide by \\(g\\)","square"],
  "2018 P1 Q15": ["start process","complete process"],
  "2018 P1 Q16": ["identify roots","identify turning point OR y-intercept","identify the turning point AND the y-intercept and sketch a consistently annotated parabola"],
  "2018 P1 Q17": ["start substitution into formula / change subject to \\(h\\)","complete substitution into formula","calculate height"],
  "2018 P1 Q18": ["correct substitution for \\(\\tan x\\)","express in simplest form"],
  "2018 P1 Q19": ["(i) correct bracket with square","complete process","(ii) state equation of axis of symmetry","equate complete square form to zero / correct substitution into quadratic formula","start to solve / evaluate discriminant","solve equation / express discriminant in simplest form","complete process"],
  "2018 P2 Q1": ["know how to decrease by 2%","know how to calculate new total","carry out calculations correctly within a valid strategy"],
  "2018 P2 Q2": ["appropriate fraction","correct substitution into arc length formula","calculate arc length"],
  "2018 P2 Q3": ["start process","solution"],
  "2018 P2 Q4": ["start to process right hand side","collect like terms","solve for \\(x\\)"],
  "2018 P2 Q5": ["calculate mean","calculate \\((x - \\overline{x})^2\\) or \\(\\sum x\\) and \\(\\sum x^2\\)","substitute into formula","calculate standard deviation","compare means","compare standard deviations"],
  "2018 P2 Q6": ["valid strategy","state value of \\(a\\)"],
  "2018 P2 Q7": ["substitute into formula","calculate volume","round to 2 significant figures"],
  "2018 P2 Q8": ["rearrange equation","calculate value of \\(x\\)","calculate 2nd value of \\(x\\)"],
  "2018 P2 Q9": ["correct substitution into sine rule","re-arrange formula","calculate length"],
  "2018 P2 Q10": ["express \\(\\overrightarrow{ED}\\) in terms of \\(\\mathbf{u}\\) and \\(\\overrightarrow{DC}\\) in terms of \\(\\mathbf{w}\\)","express \\(\\overrightarrow{BC}\\) in terms of \\(\\mathbf{u}\\) and \\(\\mathbf{w}\\) in simplest form"],
  "2018 P2 Q11": ["know that \\(85\\% = 9.3 \\times 10^{11}\\)","begin valid strategy","complete calculation within valid strategy"],
  "2018 P2 Q12": ["marshal facts and recognise right angled triangle","consistent Pythagoras statement","calculate \\(x\\)","calculate width"],
  "2018 P2 Q13": ["correct substitution into cosine rule","correct calculation of \\(\\cos YTF\\)","calculate angle YTF","calculate bearing"],
  "2018 P2 Q14": ["isolate term in \\(y\\) or divide throughout by 5 / substitute \\(x = 0\\) into equation","state coordinates (must use brackets)"],
  "2018 P2 Q15": ["start to divide fractions","factorise","multiply and simplify"],
  "2018 P2 Q16": ["start valid strategy","continue strategy","calculate length of space diagonal","valid conclusion with comparison"],
  "2018 P2 Q17": ["substitute correctly into area of triangle formula","appropriate fraction for sector","substitute correctly into area of sector formula","know to subtract area of sector from area of triangle","calculate area of shaded region and state correct units"],
  "2018 P2 Q18": ["state linear scale factor","know to multiply volume by cube of linear scale factor","correct calculation, valid comparison and conclusion","find volume scale factor","correct calculation to find height (must involve a root of the volume scale factor)"],
  "2019 P1 Q1": ["substitute into \\(5x^3\\)","evaluate \\(5x^3\\)"],
  "2019 P1 Q2": ["start to multiply fractions","consistent answer in simplest form"],
  "2019 P1 Q3": ["start to expand","complete expansion","collect like terms (which must include a term in \\(x^3\\))"],
  "2019 P1 Q4": ["appropriate fraction","consistent substitution","calculate length of arc"],
  "2019 P1 Q5": ["state median","find quartiles","calculate SIQR","valid comment comparing medians","valid comment comparing SIQRs"],
  "2019 P1 Q6": ["calculate gradient","substitute gradient and a point","state equation in terms of \\(F\\) and \\(E\\) in simplest form","calculate fuel consumption"],
  "2019 P1 Q7": ["multiply by 2","divide by \\(h\\) / expand and subtract \\(hy\\)","subtract \\(y\\) / divide by \\(h\\)"],
  "2019 P1 Q8": ["construct equation","construct equation","correct scaling","value for \\(c\\) or \\(g\\)","value for \\(g\\) or \\(c\\)","communicate answer in kilograms"],
  "2019 P1 Q9": ["state equation of axis of symmetry","(i) state the value of \\(a\\)","(ii) state the value of \\(b\\)"],
  "2019 P1 Q10": ["correct answer","valid pathway","consistent components"],
  "2019 P1 Q11": ["find angle AOB","find angle FOB or ABO","find angle OFB"],
  "2019 P1 Q12": ["express as equivalent fraction with rational denominator / correct division","express numerator/denominator in simplest form","express in simplest form"],
  "2019 P1 Q13": ["state x-coordinate","state y-coordinate"],
  "2019 P1 Q14": ["eliminate denominators / collect algebraic terms","rearrange into form \\(ax = b\\)","solve for \\(x\\)"],
  "2019 P1 Q15": ["calculate height","construct equation","rearrange and equate to zero","consistent factorisation","solve equation and select correct value"],
  "2019 P2 Q1": ["know how to increase by 15%","know how to calculate number of packages after 3 years","evaluate"],
  "2019 P2 Q2": ["start process","consistent solution"],
  "2019 P2 Q3": ["correct substitution into area of triangle formula","calculate area"],
  "2019 P2 Q4": ["correct method","answer"],
  "2019 P2 Q5": ["state coordinates of A","state coordinates of B"],
  "2019 P2 Q6": ["correct substitution into quadratic formula","evaluate discriminant","calculate both roots correct to one decimal place"],
  "2019 P2 Q7": ["correct substitution into cosine rule to find angle Z","evaluate","calculate angle"],
  "2019 P2 Q8": ["correct substitution into formula for volume of sphere","correct substitution into formula for volume of cylinder","know to add volume of hemisphere to volume of cylinder","all calculations correct","round final answer to 3 significant figures and state correct units"],
  "2019 P2 Q9": ["know that \\(102.5\\% = £977.85\\)","begin valid strategy","complete calculation within valid strategy"],
  "2019 P2 Q10": ["correct bracket with square","complete process"],
  "2019 P2 Q11": ["use perimeter to find length of BC and use a valid strategy","evaluate","explicit comparison / calculate angle","conclusion with valid reason"],
  "2019 P2 Q12": ["linear scale factor","know to multiply area by square of linear scale factor","find area of smaller sector","expression for sector area / ratio","know how to find angle","calculate angle"],
  "2019 P2 Q13": ["correct substitution into gradient formula","factorise using difference of two squares","factorise using common factor and simplify"],
  "2019 P2 Q14": ["rearrange equation","find one value of \\(x\\)","find second value of \\(x\\)"],
  "2019 P2 Q15": ["correct denominator","correct numerator","express in simplest form"],
  "2019 P2 Q16": ["apply \\(a^m \\times ka^n = ka^{m+n}\\)","evidence of \\(\\sqrt{a} = a^{\\frac{1}{2}}\\)","complete simplification"],
  "2019 P2 Q17": ["expand brackets","simplify expression"],
  "2019 P2 Q18": ["marshal facts and recognise right-angled triangle","consistent Pythagoras statement","calculate radius of larger circle","calculate CD"],
  "2019 P2 Q19": ["correct substitution into sine rule","re-arrange formula","calculate BK","consistent substitution into appropriate trig formula","calculate height using trigonometry"],
  "2022 P1 Q1": ["start calculation correctly","consistent answer in simplest form"],
  "2022 P1 Q2": ["substitute into \\(x^3 - 2\\)","evaluate"],
  "2022 P1 Q3": ["correct substitution into formula for volume of cone","calculate volume"],
  "2022 P1 Q4": ["calculate size of angle COE or EDO or OED","calculate size of angle OCE","calculate size of angle ACE"],
  "2022 P1 Q5": ["correct bracket with square","complete process consistently","state coordinates of turning point"],
  "2022 P1 Q6": ["calculate gradient","substitute gradient and a point","determine the equation of the line in simplest form"],
  "2022 P1 Q7": ["multiply by \\(C^2\\)","subtract \\(4\\)"],
  "2022 P1 Q8": ["state the value of \\(a\\)","state the value of \\(b\\)"],
  "2022 P1 Q9": ["correct substitution into cosine rule","calculate \\(\\cos B\\) in simplest form"],
  "2022 P1 Q10": ["know that \\(70\\% = £16.10\\)","begin valid strategy","complete calculation within valid strategy"],
  "2022 P1 Q11": ["apply \\((m^a)^b = m^{ab}\\) / \\(m^{-a} = \\frac{1}{m^a}\\)","apply \\(m^a \\times m^b = m^{a+b}\\) / \\(m^{-a} = \\frac{1}{m^a}\\)","apply \\(m^{-a} = \\frac{1}{m^a}\\) / complete simplification"],
  "2022 P1 Q12": ["start to divide fractions","simplify"],
  "2022 P1 Q13": ["expand bracket","express surd in simplest form","complete simplification"],
  "2022 P1 Q14": ["identify roots","identify turning point OR y-intercept","identify turning point AND y-intercept and sketch a consistently annotated parabola"],
  "2022 P1 Q15": ["construct expression for area of triangle","construct expression for area of rectangle and equate to area of triangle","start to solve equation","re-arrange equation","solve for \\(x\\)"],
  "2024 P1 Q1": ["identify common denominator","consistent answer"],
  "2024 P1 Q2": ["substitute into \\(f(x)\\)","evaluate \\(f(x)\\)"],
  "2024 P1 Q3": ["start to expand","complete expansion","collect like terms"],
  "2024 P1 Q4": ["calculate \\(3a\\)","solution"],
  "2024 P1 Q5": ["correct median","find quartiles","calculate IQR","valid comment comparing medians","valid comment comparing IQRs"],
  "2024 P1 Q6": ["simplify surd","complete simplification"],
  "2024 P1 Q7": ["correct scaling","value for one variable","value for other variable"],
  "2024 P1 Q8": ["(a) state value of \\(a\\)","(b) state value of \\(b\\)"],
  "2024 P1 Q9": ["find gradient","substitute gradient and a point","state equation in terms of \\(D\\) and \\(T\\) in simplest form","calculate distance remaining"],
  "2024 P1 Q10": ["calculate size of angle OFD","calculate size of angle BOD or FED","calculate size of angle BCD"],
  "2024 P1 Q11": ["isolate term in \\(y\\) or divide throughout by 4","state gradient explicitly"],
  "2024 P1 Q12": ["correct bracket with square","complete process consistently","state coordinates of turning point","find \\(x\\) coordinate","find \\(y\\) coordinate"],
  "2024 P1 Q13": ["apply \\(x \\times x^{\\frac{m}{n}}\\) or \\(x \\times x^{-1}\\)","apply \\(x \\times x^{\\frac{m}{n}}\\) and \\(x \\times x^{-1}\\) and simplify"],
  "2024 P1 Q14": ["valid scale factor","consistent scaling of AD","calculate BD"],
  "2025 P1 Q1": ["start to multiply fractions","consistent answer in simplest form"],
  "2025 P1 Q2": ["expand pair of brackets","complete expansion","collect like terms"],
  "2025 P1 Q3": ["find quartiles","calculate IQR"],
  "2025 P1 Q4": ["evidence that \\(80\\% = 720\\)","start valid strategy","complete calculation within a valid strategy"],
  "2025 P1 Q5": ["substitute correctly into area formula","calculate area"],
  "2025 P1 Q6": ["calculate gradient","substitute gradient and a point","state equation in simplest form"],
  "2025 P1 Q7": ["state the value of \\(f(6)\\)","valid strategy","state value of \\(p\\)"],
  "2025 P1 Q8": ["state x-coordinate or y-coordinate","state x-coordinate and y-coordinate"],
  "2025 P1 Q9": ["state the value of \\(a\\)","state the value of \\(b\\)"],
  "2025 P1 Q10": ["apply \\((x^a)^b = x^{a \\times b}\\)","apply \\(x^m \\times x^n = x^{m+n}\\)","apply \\(\\frac{x^p}{x^q} = x^{p-q}\\)"],
  "2025 P1 Q11": ["calculate discriminant","state nature of roots"],
  "2025 P1 Q12": ["express as equivalent fraction with rational denominator","express in simplest form"],
  "2025 P1 Q13": ["correct nose-to-tail diagram / find components of \\(\\mathbf{p}+\\mathbf{q}\\)","consistent vector \\(\\mathbf{p}+\\mathbf{q}\\) drawn (must include arrow)"],
  "2025 P1 Q14": ["correct denominator","correct numerator","remove brackets and collect like terms in numerator"],
  "2025 P1 Q15": ["find expression for area of rectangle","equate required expressions and expand expression for area of square or rectangle within the equation","complete expansion and rearrange into required form","factorise \\(x^2 - x - 6\\)","solve equation","reject invalid value of \\(x\\) and state length and breadth of rectangle"],
  "2026 P1 Q1": ["start to expand","complete expansion","collect like terms (see Note 3)"],
  "2026 P1 Q2": ["evidence that \\(60\\% = 180\\)","begin valid strategy","complete calculation within valid strategy"],
  "2026 P1 Q3": ["calculate median","find quartiles","calculate IQR","valid comment comparing medians","valid comment comparing interquartile ranges"],
  "2026 P1 Q4": ["start to process right hand side","re-arrange (collect constants on one side and variables on other side)","solve for \\(x\\)"],
  "2026 P1 Q5": ["identify strategy **and** find common denominator","consistent answer in simplest form"],
  "2026 P1 Q6": ["calculate gradient","substitute gradient and a point — M1 into \\(y - b = m(x - a)\\), M2 into \\(y = mx + c\\)","state equation in terms of \\(F\\) and \\(P\\) **and** in simplest form — M1 also remove any brackets and collect constants","calculate mark"],
  "2026 P1 Q7": ["start process","consistent calculation","express as a surd in its simplest form"],
  "2026 P1 Q8": ["square both sides","add \\(3L\\)"],
  "2026 P1 Q9": ["correct substitution into \\(y = kx^2\\)","solve"],
  "2026 P1 Q10": ["calculate the size of angle ABO","calculate size of angle COB or angle AOB","calculate size of angles COB, AOB and **reflex** angle AOC"],
  "2026 P1 Q11": ["state coordinates","state coordinates"],
  "2026 P1 Q12": ["correct coordinates of turning point","M1 sketch parabola with minimum turning point consistent with •¹; M2 state correct \\(y\\)-intercept","M1 correct \\(y\\)-intercept shown on sketch; M2 sketch parabola with minimum turning point and \\(y\\)-intercept consistent with •¹ and •²"],
  "2026 P1 Q13": ["substitute into \\(f(x) = 5\\cos 2x\\)","evaluate"],
  "2026 P1 Q14": ["start to factorise (see Note 1)","complete factorisation","solve equation"],
  "2022 P2 Q1": ["start to expand","complete expansion","collect like terms which must include a term in \\(x^3\\) and a term with a negative coefficient"],
  "2022 P2 Q2": ["know how to increase by 3%","know how to calculate expected profit after 4 years","evaluate to nearest thousand pounds"],
  "2022 P2 Q3": ["correct substitution into volume of sphere formula","correct substitution into volume of cuboid formula and add to volume of sphere","consistent calculation and state correct units in final answer"],
  "2022 P2 Q4": ["construct equation","construct equation","correct scaling","value for \\(a\\) or \\(m\\)","value for \\(m\\) or \\(a\\)","communicate answer with units"],
  "2022 P2 Q5": ["calculate mean","calculate \\((x - \\overline{x})^2\\) or \\(\\sum x\\) and \\(\\sum x^2\\)","substitute into formula","calculate standard deviation","compare means","compare standard deviations"],
  "2022 P2 Q6": ["correct substitution into area of triangle formula","calculate area"],
  "2022 P2 Q7": ["correct substitution into quadratic formula","evaluate discriminant","calculate both unrounded values of \\(x\\) or one value of \\(x\\) rounded to 2 significant figures","calculate both values of \\(x\\) rounded to 2 significant figures"],
  "2022 P2 Q8": ["marshal facts and recognise right-angled triangle","consistent Pythagoras statement","calculate third side","calculate height"],
  "2022 P2 Q9": ["rearrange equation","find first value of \\(x\\)","find second value of \\(x\\)"],
  "2022 P2 Q10": ["expression for arc length / arc length: circumference ratio","know how to find angle","calculate angle"],
  "2022 P2 Q11": ["start valid strategy for finding length of face diagonal","continue valid strategy for finding length of space diagonal","calculate length of space diagonal"],
  "2022 P2 Q12": ["factorise numerator","factorise denominator","express fraction in simplest form"],
  "2022 P2 Q13": ["express as separate fractions","simplify"],
  "2022 P2 Q14": ["correct substitution into sine rule to calculate AC / AD","rearrange equation","calculate AC / AD","valid strategy to calculate BC / BD","calculate BC (ie BD - 15)"],
  "2023 P2 Q1": ["know how to decrease by 11% and 6%","know how to calculate value of caravan","evaluate"],
  "2023 P2 Q2": ["correct method","evaluate","express in scientific notation rounded to 3 significant figures"],
  "2023 P2 Q3": ["appropriate fraction","consistent substitution into arc length formula / ratio","calculate arc length"],
  "2023 P2 Q4": ["correct substitution into sine rule","rearrange equation","calculate angle JKL"],
  "2023 P2 Q5": ["calculate size of interior or exterior angle of the decagon","calculate size of shaded angle"],
  "2023 P2 Q6": ["evidence that 108% is 94500","start valid strategy","complete calculation within a valid strategy"],
  "2023 P2 Q7": ["add \\(r\\) / multiply by 3","multiply by 3 / add \\(3r\\)","divide by \\(n\\)"],
  "2023 P2 Q8": ["valid strategy","evaluation","explicit comparison","conclusion with valid reason"],
  "2023 P2 Q9": ["correct substitution into formula for volume of small pyramid","consistent substitution into formula for volume of large pyramid","know to subtract volume of small pyramid from volume of large pyramid","all calculations correct and state correct units"],
  "2023 P2 Q10": ["correct denominator","correct numerator","remove brackets and collect like terms in numerator"],
  "2023 P2 Q11": ["substitute \\(h=150\\) into formula","rearrange equation","calculate one value of \\(x\\)","calculate second value of \\(x\\)"],
  "2023 P2 Q12": ["factorise numerator","factorise denominator","cancel brackets correctly"],
  "2023 P2 Q13": ["factorise / expand / substitute","substitute and simplify"],
  "2023 P2 Q14": ["use the dimensions of the cuboid to find an expression for the volume","construct equation and rearrange into required form","correct substitution into quadratic formula","evaluate discriminant","solve for \\(x\\)","select correct value of \\(x\\), to one decimal place"],
  "2023 P2 Q15": ["correct trig. ratio","correct substitution into formula for area of triangle ADE","form equation","solve to find length of AE"],
  "2024 P2 Q1": ["know how to decrease by 26%","know how to calculate value","evaluate"],
  "2024 P2 Q2": ["correct method","evaluate and write in scientific notation"],
  "2024 P2 Q3": ["correct substitution into cosine rule","evaluate \\(\\cos A\\)","calculate angle"],
  "2024 P2 Q4": ["start to process left hand side","rearrange (collect constants on one side and variables on the other side)","solve for \\(x\\)"],
  "2024 P2 Q5": ["know that \\(116\\% = 278.40\\)","begin valid strategy","complete calculation within valid strategy"],
  "2024 P2 Q6": ["factorise","factorise denominator","simplify"],
  "2024 P2 Q7": ["correct substitution into volume of sphere formula","correct substitution into volume of cuboid formula and know to subtract volume of hemisphere from volume of cuboid","consistent calculation","round final answer to 2 significant figures and state correct units"],
  "2024 P2 Q8": ["correct substitution into quadratic formula","evaluate discriminant","calculate both roots correct to two decimal places"],
  "2024 P2 Q9": ["multiply by \\(e\\)","subtract \\(3\\)","divide by \\(2\\)"],
  "2024 P2 Q10": ["marshal facts and recognise right-angled triangle","consistent Pythagoras statement","calculate third side","calculate width"],
  "2024 P2 Q11": ["re-arrange equation","find one value of \\(x\\)","find second value of \\(x\\)"],
  "2024 P2 Q12": ["correct denominator","correct numerator(s)","express in simplest form (remove brackets in numerator and collect like terms)"],
  "2024 P2 Q13": ["correct substitution into sine rule","re-arrange formula","calculate intermediate length","consistent substitution into appropriate trig formula","calculate \\(BD\\)"],
  "2024 P2 Q14": ["state vector","valid pathway","Express \\(\\overrightarrow{WM}\\) in terms of \\(\\mathbf{a}\\) and \\(\\mathbf{b}\\) in simplest form"],
  "2024 P2 Q15": ["correct fraction / start strategy for finding angle","know how to calculate sector area","calculate sector area"],
  "2024 P2 Q16": ["valid substitution","express in the form \\(a + b \\sin^2 x^\\circ\\)"],
  "2025 P2 Q1": ["know how to increase by 4%","know how to calculate visitors after 2 years","consistent calculation"],
  "2025 P2 Q2": ["substitute into formula","calculate volume","round to 3 significant figures AND state correct units"],
  "2025 P2 Q3": ["correct method","answer"],
  "2025 P2 Q4": ["calculate mean","calculate \\((x - \\overline{x})^2\\) or \\(\\sum x\\) and \\(\\sum x^2\\)","substitute into formula","calculate standard deviation","compare means","compare standard deviations"],
  "2025 P2 Q5": ["correct bracket with square","complete process consistently"],
  "2025 P2 Q6": ["appropriate fraction","consistent substitution into area formula","calculate sector area"],
  "2025 P2 Q7": ["calculate the size of an interior angle of the pentagon or angle FAE","calculate the size of angle FEA"],
  "2025 P2 Q8": ["state coordinates","start valid strategy","continue strategy","calculate length of space diagonal"],
  "2025 P2 Q9": ["add \\(3c\\) / multiply by 4","multiply by 4 / add \\(12c\\)","divide by \\(c^2\\)"],
  "2025 P2 Q10": ["construct equation","construct equation","correct scaling","value for \\(p\\) or \\(e\\)","value for \\(e\\) or \\(p\\)","consistent calculation"],
  "2025 P2 Q11": ["find linear scale factor","multiply / divide area by square of linear scale factor","find area of large wing"],
  "2025 P2 Q12": ["correct substitution into the sine rule","rearrange equation","calculate angle ACB","calculate bearing"],
  "2025 P2 Q13": ["eliminate denominators","rearrange into the form \\(ax = b\\)","solve for \\(x\\)"],
  "2025 P2 Q14": ["substitute \\(h = 13\\) into formula","rearrange equation","calculate one value of \\(x\\)","calculate 2nd value of \\(x\\)"],
  "2025 P2 Q15": ["express \\(\\overrightarrow{GF}\\) as a vector journey","express \\(\\overrightarrow{GF}\\) in simplest form"],
  "2026 P2 Q1": ["know how to decrease by 28%","know how to calculate value","evaluate","answer correct to 3 significant figures"],
  "2026 P2 Q2": ["correct substitution into cosine rule","evaluate \\(XY^2\\)","evaluate \\(XY\\)"],
  "2026 P2 Q3": ["find linear scale factor","M1 multiply volume by cube of linear scale factor; M2 divide volume by cube of linear scale factor","find volume (calculation must involve a power of a linear scale factor)"],
  "2026 P2 Q4": ["construct equation","construct equation","correct scaling","value for \\(c\\) or \\(p\\)","value for \\(p\\) or \\(c\\)","calculate final answer"],
  "2026 P2 Q5": ["marshal facts and recognise right angled triangle","consistent Pythagoras statement","calculate radius"],
  "2026 P2 Q6": ["correct substitution into formula for volume of sphere","consistent volume calculation","M1 start substitution into formula for volume of cone; M2 change subject to \\(h\\)","M1 complete substitution into formula; M2 correct substitution into formula","calculate height"],
  "2026 P2 Q7": ["start a valid strategy","carry that strategy through and evaluate","compare explicitly within the strategy, then state the conclusion"],
  "2026 P2 Q8": ["rearrange equation","find first value of \\(x\\)","find second value of \\(x\\)"],
  "2026 P2 Q9": ["start to divide fractions","factorise","multiply and simplify"],
  "2026 P2 Q10": ["find angle","substitute into area of a triangle formula","M1 substitute into sector formula; M2 know how to calculate area of **all** segments","know how to calculate area of a segment","calculate area of segment **and state correct units**"],
  "2026 P2 Q11": ["start to simplify denominator","simplify denominator","complete simplification"],
  "2026 P2 Q12": ["M1 factorises; M2 valid substitution","express in simplest form"],
  "2026 P2 Q13": ["correct expression","find expression for area of extension and expand pair of brackets","construct equation and rearrange into required form","correct substitution into quadratic formula","evaluate discriminant","solve for \\(x\\)","select correct value of \\(x\\), stated to 2 decimal places"],
  "2023 P1 Q1": ["convert to improper fraction and multiply by the reciprocal","consistent answer"],
  "2023 P1 Q2": ["start expansion","complete expansion","collect like terms"],
  "2023 P1 Q3": ["correct scaling","value for one variable","value for other variable"],
  "2023 P1 Q4": ["state value of \\(a\\)","state value of \\(b\\)","(b) find value of \\(c\\)"],
  "2023 P1 Q5": ["calculate discriminant","state nature of roots"],
  "2023 P1 Q6": ["correct substitution into cosine rule","calculate \\(AB^2\\)","calculate \\(AB\\)"],
  "2023 P1 Q7": ["calculate gradient","substitute gradient and a point","equation in terms of \\(P\\) and \\(T\\), simplest form","calculate salary"],
  "2023 P1 Q8": ["express as equivalent fraction with rational denominator","express in simplest form"],
  "2023 P1 Q9": ["calculate median","find quartiles","calculate IQR","valid comment comparing medians","valid comment comparing IQRs"],
  "2023 P1 Q10": ["marshal facts and recognise right-angled triangle","consistent Pythagoras statement","calculate third side","calculate width"],
  "2023 P1 Q11": ["state value"],
  "2023 P1 Q12": ["M1 start to simplify (one correct application) / M2 express with a positive power","M1 complete simplification / M2 start to simplify","express with a positive power"],
  "2023 P1 Q13": ["(a) state value of \\(a\\)","(b) state value of \\(b\\)"],
  "2023 P1 Q14": ["M1 eliminate denominators","rearrange into the form \\(ax > b\\) or \\(b > ax\\)","solve for \\(x\\)"],
};
