/**
 * What to tell a pupil who is stuck on a past paper question.
 *
 * **Generated — do not edit.** Run `npx tsx scripts/emit-paper-hints.ts`, and
 * `__checks__/hints.ts` fails if this file and the registry disagree.
 *
 * A past paper question has no worked solution on this site: the data carries
 * the final answer and a video, nothing between. Its hints come instead from
 * the variation modelled on it — `skill` is what the question asks for, and
 * `method` is the first sentence of the markscheme route recorded when that
 * variation was checked against its marking instructions.
 *
 * No imports, deliberately: the registry is 155 KB inside a 33,000-line engine,
 * and a pupil asking for a hint should not download it.
 */
export interface PaperHint {
  /** What the question is asking the pupil to do. */
  skill: string;
  /** How the marks are earned, in one line. */
  method: string;
}

export const PAPER_HINTS: Record<string, PaperHint> = {
  "2014 P1 Q1": { skill: "Multiply a mixed number by a fraction or another mixed number", method: "Start to multiply the fractions, which means converting to improper fractions first, then a consistent answer in simplest form" },
  "2014 P1 Q2": { skill: "Multiply every term in one bracket by every term in the other", method: "Any three terms correct, then the fourth term and the like terms collected" },
  "2014 P1 Q3": { skill: "Write x^2+bx+c in the form (x+p)^2+q", method: "Correct bracket with square, then complete the process" },
  "2014 P1 Q4": { skill: "Scale two vectors and combine them, answering in component form", method: "Calculate the scalar multiple, then the solution in component form" },
  "2014 P1 Q5": { skill: "Pair each side with its opposite angle, then multiply up", method: "Correct substitution into the sine rule, know how to solve it, then the correct calculation" },
  "2014 P1 Q6": { skill: "Read two points off a graph, find the equation, then use it", method: "Find the gradient, substitute it with one of the points, state the equation in the question own letters and in simplest form, then evaluate it at a given value" },
  "2014 P1 Q7": { skill: "Substitute a point on a parabola to find its stretch", method: "Know to substitute the marked point into y = ax^2, then solve for a" },
  "2014 P1 Q8": { skill: "Reduce three surds to a common root, then add the coefficients", method: "Simplify the first surd, simplify the third, then state the answer in simplest form" },
  "2014 P1 Q9": { skill: "Recover a total when a part is given as a straight percentage of it", method: "Know that r% is the figure given, find 1%, multiply by 100 — both are Paper 1, so it divides by hand" },
  "2014 P1 Q10": { skill: "Read an amplitude and a phase shift off a trigonometric graph", method: "State a, the amplitude, then state b from how far the graph has moved sideways" },
  "2014 P1 Q11": { skill: "Rearrange for the gradient, then find where the line meets the x-axis", method: "2 for starting the rearrangement and stating the gradient, 2 for knowing to set y = 0 and stating the coordinates" },
  "2014 P1 Q12": { skill: "Drop a perpendicular to the chord, use Pythagoras, add or subtract the radius", method: "Marshal the facts and recognise the right-angled triangle, then a consistent Pythagoras statement, then calculate the third side, then the length asked for" },
  "2014 P1 Q13": { skill: "Solve a quadratic model for a stated height, then decide whether a greater height is reached", method: "Construct the equation, rearrange to zero, factorise and select the first of the two times; then the turning point, the maximum height, and a conclusion comparing it with the height asked about" },
  "2014 P2 Q1": { skill: "Apply a multiplier once per year, then round as the question asks", method: "Know how to change by the rate, then know how to carry it across the years, then evaluate to the stated accuracy" },
  "2014 P2 Q2": { skill: "Read a coordinate off a solid standing on another", method: "State one coordinate, state the other" },
  "2014 P2 Q3": { skill: "Build both equations from a context, solve, answer in units", method: "Construct an equation for each situation, then correct scaling, a value, the other value, and the answer communicated in its units" },
  "2014 P2 Q4": { skill: "Find the mean and standard deviation, then judge consistency from the deviation alone", method: "The mean is its own part, then the squared differences, the formula and the standard deviation, then a single judgement" },
  "2014 P2 Q5": { skill: "Cube the linear scale factor to scale a volume", method: "State the linear scale factor, state the volume scale factor, then calculate the volume and state its units" },
  "2014 P2 Q6": { skill: "Compare the two shorter sides squared with the longest squared, and conclude", method: "Valid strategy, then evaluation, then an explicit comparison, then a conclusion with a valid reason" },
  "2014 P2 Q7": { skill: "Subtract the volume of a hemisphere from the volume of a cone", method: "Cone, hemisphere, know to subtract, calculate, round" },
  "2014 P2 Q8": { skill: "Divide coefficients and powers by their own separate rules", method: "Simplify the powers in the numerator, cancel the constants, then eliminate the variable from the denominator" },
  "2014 P2 Q9": { skill: "Common denominator, expand the numerator watching the sign, collect like terms", method: "Correct common denominator, then correct numerator, then remove the brackets and collect like terms" },
  "2014 P2 Q10": { skill: "Three distances on a map, find the angle at one of them", method: "Substitute into the cosine rule, calculate the cosine, calculate the angle; then the back bearing and the shaded angle" },
  "2014 P2 Q11": { skill: "Clear the fraction first, then isolate the subject", method: "Clear the constant term, clear the fractional coefficient, then divide by what is left" },
  "2014 P2 Q12": { skill: "Isolate the ratio, take the inverse, then find both angles in the range", method: "Rearrange the equation, find one value of x, then find the other" },
  "2014 P2 Q13": { skill: "The whole circle less the sector-minus-triangle", method: "As for the minor segment, with the final mark covering the extra subtraction from the whole circle" },
  "2015 P1 Q1": { skill: "Subtract mixed numbers, or a fraction from a mixed number", method: "Identify a common denominator, then a consistent answer" },
  "2015 P1 Q2": { skill: "Expand, collect, solve — and reverse the sign if dividing by a negative", method: "Expand the bracket, then collect like terms, then solve" },
  "2015 P1 Q3": { skill: "Right angle at a tangent, isosceles radii, and the angle in a semicircle", method: "Angle OBD, then EDF from the semicircle, then BDF as their sum" },
  "2015 P1 Q4": { skill: "Expand a binomial times a trinomial, giving a term in x cubed", method: "Start to expand, evidenced by any three correct terms, then complete the expansion, then collect like terms" },
  "2015 P1 Q5": { skill: "Read the variance out of a standard deviation given as a root", method: "Find the mean and the squared differences, substitute into the formula for a, then calculate a" },
  "2015 P1 Q6": { skill: "Read the amplitude off the axis and count the cycles for b", method: "State a, the amplitude read off the y-axis, then state b, the number of complete waves between 0 and 360" },
  "2015 P1 Q7": { skill: "Read a and b off a turning point, then give the axis of symmetry", method: "State a, state b, then state the equation of the axis of symmetry" },
  "2015 P1 Q8": { skill: "Find the equation of the line through two given points", method: "Find the gradient, substitute it and a point, then state the equation in its simplest form" },
  "2015 P1 Q9": { skill: "Order trigonometric values by sign, and say why", method: "State the correct order, then justify it explicitly by the sign of each value" },
  "2015 P1 Q10": { skill: "Median and IQR, then one comparison of average and one of spread", method: "The median, the quartiles, the interquartile range, then a valid comparison of the medians and one of the interquartile ranges" },
  "2015 P1 Q11": { skill: "Scale, eliminate, substitute back", method: "Correct scaling, then a value for one variable, then a value for the other" },
  "2015 P1 Q12": { skill: "Factorise numerator and denominator, then cancel", method: "Factorise the numerator, factorise the denominator, then cancel the brackets correctly" },
  "2015 P1 Q13": { skill: "Rationalise a denominator whose surd is not yet in simplest form", method: "Express as an equivalent fraction with a rational denominator, manipulate the surd, then a consistent answer" },
  "2015 P1 Q14": { skill: "Evaluate a numeric fractional index by taking the root then the power", method: "Interpret the index as a root and a power, then complete the evaluation" },
  "2015 P2 Q1": { skill: "Apply a multiplier once per year, then round as the question asks", method: "Know how to change by the rate, then know how to carry it across the years, then evaluate to the stated accuracy" },
  "2015 P2 Q2": { skill: "Given f(a) = b, solve for a", method: "Valid strategy, which is setting the function equal to the given value, then state the value of the unknown" },
  "2015 P2 Q3": { skill: "Two sides and the angle between them, find the third side", method: "Correct substitution into the cosine rule, evaluate the square of the side, then take the root" },
  "2015 P2 Q4": { skill: "Square the components, add, and take an exact square root", method: "Start the process by squaring and adding the components, then the solution" },
  "2015 P2 Q5": { skill: "Count two vectors off a square grid and add their components", method: "Components of either vector counted off the squares, then the components of the sum" },
  "2015 P2 Q6": { skill: "Give a sphere's volume in scientific notation, then divide two such volumes", method: "3 for the volume in scientific notation, 2 for the division" },
  "2015 P2 Q7": { skill: "Multiply by the reciprocal, factorise, cancel", method: "Start the division by multiplying by the reciprocal, then factorise, then multiply and express in simplest form" },
  "2015 P2 Q8": { skill: "Divide by the multiplier to recover the original quantity", method: "Know that the given amount is (100 +/- r)% of the original, then begin a valid strategy, then complete the calculation within it" },
  "2015 P2 Q9": { skill: "The square of the linear scale factor, then a subtraction", method: "Linear scale factor, square it to reach the whole area, then subtract the small triangle" },
  "2015 P2 Q10": { skill: "Angle and arc back to the radius", method: "The correct fraction of the circle, construct the equation, know how to solve it, then solve it and state the radius" },
  "2015 P2 Q11": { skill: "Diagonals cut a regular hexagon into six triangles of half ab sin C", method: "The correct angle at the centre, correct substitution into the area of a triangle formula, know to multiply by six for the hexagon, then the calculation with its units" },
  "2015 P2 Q12": { skill: "Drop a perpendicular to the chord, use Pythagoras, add or subtract the radius", method: "Marshal the facts and recognise the right-angled triangle, then a consistent Pythagoras statement, then calculate the third side, then the length asked for" },
  "2015 P2 Q13": { skill: "Two places on a cardinal line, a bearing from each, find a distance", method: "Calculate the angles of the triangle from the bearings, correct substitution into the sine rule, rearrange it, then calculate the side" },
  "2015 P2 Q14": { skill: "Turn a border of width x into a quadratic, then solve it", method: "1 for the expression, 2 for the area and the rearrangement, 4 for the formula: substitute, discriminant, solve, select and round" },
  "2016 P1 Q1": { skill: "Scale two vectors and combine them, answering in component form", method: "Calculate the scalar multiple, then the solution in component form" },
  "2016 P1 Q2": { skill: "Evaluate the bracket first, then multiply - two operations", method: "Start the calculation correctly, which is the bracket over a common denominator, then a consistent answer in simplest form" },
  "2016 P1 Q3": { skill: "The same with pi taken as 3.14, which is a different sum", method: "Appropriate fraction, correct substitution into the area formula with pi taken as 3.14, then calculate the area" },
  "2016 P1 Q4": { skill: "Build both equations from a context, solve, answer in units", method: "Construct an equation for each situation, then correct scaling, a value, the other value, and the answer communicated in its units" },
  "2016 P1 Q5": { skill: "Read two points off a graph, find the equation, then use it", method: "Find the gradient, substitute it with one of the points, state the equation in the question own letters and in simplest form, then evaluate it at a given value" },
  "2016 P1 Q6": { skill: "Calculate b^2-4ac and state the nature of the roots", method: "Calculate the discriminant, then state the nature of the roots" },
  "2016 P1 Q7": { skill: "The apex of a pyramid sits above the centre of its base", method: "State the coordinates of B, then know how to find AM squared, know how to find AV, and find the length of AV" },
  "2016 P1 Q8": { skill: "Multiply every term by the lowest common multiple, then solve", method: "Eliminate the denominators, rearrange into ax = b, solve" },
  "2016 P1 Q9": { skill: "Substitute into a function, then rationalise the denominator", method: "Correct substitution into f(x), then a consistent answer with a rational denominator" },
  "2016 P1 Q10": { skill: "Read the turning point off completed square form and sketch the curve", method: "State the turning point, sketch a parabola with a minimum turning point consistent with it, then the y-intercept" },
  "2016 P1 Q11": { skill: "Replace tan with sin/cos, or take out a common factor, then use sin^2+cos^2=1", method: "Identify and substitute the correct identity, then express the result in simplest form" },
  "2016 P1 Q12": { skill: "Derive a quadratic from two equal areas, then solve it for the sides", method: "An expression for the rectangle, then the two areas expanded separately and equated into the printed quadratic, then factorise, solve and reject" },
  "2016 P2 Q1": { skill: "Apply a multiplier once per year, then round as the question asks", method: "Know how to change by the rate, then know how to carry it across the years, then evaluate to the stated accuracy" },
  "2016 P2 Q2": { skill: "Multiply, divide or take a percentage, then express in scientific notation", method: "Correct method, then evaluate and write in scientific notation" },
  "2016 P2 Q3": { skill: "Express a diagonal of a parallelogram in terms of two sides", method: "One mark, one step: the route round two sides of the parallelogram" },
  "2016 P2 Q4": { skill: "Common factor first, then the difference of two squares", method: "Begin to factorise by taking out the common factor, then factorise fully via the difference of two squares" },
  "2016 P2 Q5": { skill: "Allied angles across parallel lines, isosceles radii, then a quadrilateral with two right angles", method: "Angle CAO across the parallels, then CAB, then ABC" },
  "2016 P2 Q6": { skill: "Mean and standard deviation, then compare both with a second sample", method: "The mean, the squared differences, substitution into the formula, the standard deviation, then a valid comparison of the means and one of the standard deviations" },
  "2016 P2 Q7": { skill: "Subtract a similar cone from a cone to find the volume of a frustum", method: "Know it is a difference, large cone, small cone, calculate, round" },
  "2016 P2 Q8": { skill: "Pair each side with its opposite angle, then find the acute angle", method: "Correct substitution into the sine rule, rearrange it, then calculate the angle" },
  "2016 P2 Q9": { skill: "Write x^2+bx+c in the form (x+p)^2+q", method: "Correct bracket with square, then complete the process" },
  "2016 P2 Q10": { skill: "Combine powers to a negative index, then write it with a positive power", method: "Apply the power of a power, then add the powers, then express the result with a positive power" },
  "2016 P2 Q11": { skill: "Scale a quantity proportional to area by the square of the scale factor", method: "The linear scale factor, know to multiply or divide the cost by its square, then find the cost" },
  "2016 P2 Q12": { skill: "Square or take a root to undo the power, then rearrange", method: "Undo the operations in turn, one mark each, with the square or the square root taken at the point it applies" },
  "2016 P2 Q13": { skill: "Common denominator, expand the numerator, collect like terms", method: "Correct common denominator, then correct numerator, then remove the brackets and collect like terms" },
  "2016 P2 Q14": { skill: "Isolate the ratio, take the inverse, then find both angles in the range", method: "Rearrange the equation, find one value of x, then find the other" },
  "2016 P2 Q15": { skill: "Drop a perpendicular to the chord, use Pythagoras, add or subtract the radius", method: "Marshal the facts and recognise the right-angled triangle, then a consistent Pythagoras statement, then calculate the third side, then the length asked for" },
  "2016 P2 Q16": { skill: "Cosine from the small triangle, then the cosine rule in the large one", method: "Identify the cosine of the shared angle, substitute into the cosine rule, calculate the square of the side, then calculate the side" },
  "2017 P1 Q1": { skill: "Substitute a value, usually negative, into f(x)", method: "Substitute the value into f(x), then evaluate" },
  "2017 P1 Q2": { skill: "Order the data, find the quartiles, then the (semi-)interquartile range", method: "Find the quartiles, then calculate the range" },
  "2017 P1 Q3": { skill: "Divide a mixed number by a fraction or a whole number", method: "Convert to improper fractions and multiply by the reciprocal, then a consistent answer in simplest form" },
  "2017 P1 Q4": { skill: "Expand a binomial times a trinomial, giving a term in x cubed", method: "Start to expand, evidenced by any three correct terms, then complete the expansion, then collect like terms" },
  "2017 P1 Q5": { skill: "Find the apex of a pyramid over the centre of the solid beneath it", method: "State one coordinate, state the other" },
  "2017 P1 Q6": { skill: "Find the equation of the line through two given points", method: "Find the gradient, substitute it and a point, then state the equation in its simplest form" },
  "2017 P1 Q7": { skill: "Half ab sin C with the sine given as a fraction, no calculator", method: "Correct substitution into the area formula, then calculate the area" },
  "2017 P1 Q8": { skill: "Expand, collect, solve — and reverse the sign if dividing by a negative", method: "Expand the bracket, then collect like terms, then solve" },
  "2017 P1 Q9": { skill: "Isosceles radii, a straight line at the centre, then the triangle outside the circle", method: "Angle OBD, then ODB from the isosceles radii, then CAB" },
  "2017 P1 Q10": { skill: "Multiply up, subtract, divide — the subject sits in a numerator", method: "Multiply by the denominator, subtract the constant term, divide by the coefficient - one mark per operation" },
  "2017 P1 Q11": { skill: "Common denominator, expand the numerator watching the sign, collect like terms", method: "Correct common denominator, then correct numerator, then remove the brackets and collect like terms" },
  "2017 P1 Q12": { skill: "Express the standard deviation of five values in the form a√b/2", method: "Find the mean, find the squared differences, substitute into the formula and start to evaluate, then state a and b" },
  "2017 P1 Q13": { skill: "Solve the pair to find where two lines cross, answer as coordinates", method: "Evidence of scaling to match the x or y coefficients, then a valid strategy through to values for x and y, then state the coordinates of the point" },
  "2017 P1 Q14": { skill: "Take a from the axis of symmetry, then substitute a point for b", method: "State a from the axis of symmetry, then substitute the marked point and state b" },
  "2017 P1 Q15": { skill: "Equal ratios across a parallel cut, then an equation in x", method: "Scale factor, form the equation, solve for x" },
  "2017 P2 Q1": { skill: "Square the components, add, and take an exact square root", method: "Start the process by squaring and adding the components, then the solution" },
  "2017 P2 Q2": { skill: "Apply a multiplier once per year, then round as the question asks", method: "Know how to change by the rate, then know how to carry it across the years, then evaluate to the stated accuracy" },
  "2017 P2 Q3": { skill: "Two sides and the angle between them, find the third side", method: "Correct substitution into the cosine rule, evaluate the square of the side, then take the root" },
  "2017 P2 Q4": { skill: "Substitute into the formula and round as the question asks", method: "Correct substitution into the quadratic formula, then evaluate the discriminant, then both roots at the stated accuracy" },
  "2017 P2 Q5": { skill: "Divide by the multiplier to recover the original quantity", method: "Know that the given amount is (100 +/- r)% of the original, then begin a valid strategy, then complete the calculation within it" },
  "2017 P2 Q6": { skill: "Find the volume of a coating from the outer diameter and its thickness", method: "Know it is a difference, outer sphere, inner sphere, calculate, round" },
  "2017 P2 Q7": { skill: "Two triangles joined along a shared edge: build the base, then test the composite", method: "Form the composite base from its two parts, then a valid strategy and an evaluation, with the comparison and the conclusion together in the third mark rather than separately - three marks, one fewer than the four-mark converse papers" },
  "2017 P2 Q8": { skill: "Use an extended side and a midpoint to reach a fourth point", method: "1 for the direct route, then 2: the pathway through the extension and the midpoint, then collecting it" },
  "2017 P2 Q9": { skill: "Factorise, then hence simplify — the scaffolded two-part form", method: "Factorise for part (a), then factorise the denominator and simplify for part (b)" },
  "2017 P2 Q10": { skill: "Two places on a cardinal line, a bearing from each, find a distance", method: "Calculate the angles of the triangle from the bearings, correct substitution into the sine rule, rearrange it, then calculate the side" },
  "2017 P2 Q11": { skill: "Rearrange into y = mx + c and read off the gradient", method: "Isolate the term in y, or divide throughout, then state the gradient explicitly" },
  "2017 P2 Q12": { skill: "Write a reciprocal root as a single negative fractional power", method: "Apply the nth root of x^m = x^(m/n), then apply 1/x^n = x^(-n)" },
  "2017 P2 Q13": { skill: "Drop a perpendicular to the chord, use Pythagoras, add or subtract the radius", method: "Marshal the facts and recognise the right-angled triangle, then a consistent Pythagoras statement, then calculate the third side, then the length asked for" },
  "2017 P2 Q14": { skill: "The arc as a fraction of the circumference gives the angle", method: "An expression for the arc length, or the arc-to-circumference ratio, then know how to find the angle from it, then calculate the angle" },
  "2017 P2 Q15": { skill: "Solve a given height formula for the angle, in a range", method: "Substitute the given height into the formula, rearrange it, calculate one value of x, then the second" },
  "2018 P1 Q1": { skill: "Add mixed numbers, or a mixed number and a fraction", method: "Identify a common denominator, then a consistent answer" },
  "2018 P1 Q2": { skill: "Expand a product and a single bracket, then collect like terms", method: "Start the expansion, then complete it, then collect like terms" },
  "2018 P1 Q3": { skill: "Scale, eliminate, substitute back", method: "Correct scaling, then a value for one variable, then a value for the other" },
  "2018 P1 Q4": { skill: "Scale two vectors and combine them, answering in component form", method: "Calculate the scalar multiple, then the solution in component form" },
  "2018 P1 Q5": { skill: "Factorise, then set each bracket to zero", method: "Correct factorisation, then solve for x" },
  "2018 P1 Q6": { skill: "Read the amplitude off the axis and count the cycles for b", method: "State a, the amplitude read off the y-axis, then state b, the number of complete waves between 0 and 360" },
  "2018 P1 Q7": { skill: "Read two points off a graph, find the equation, then use it", method: "Find the gradient, substitute it with one of the points, state the equation in the question own letters and in simplest form, then evaluate it at a given value" },
  "2018 P1 Q8": { skill: "Calculate b^2-4ac and state the nature of the roots", method: "Calculate the discriminant, then state the nature of the roots" },
  "2018 P1 Q9": { skill: "Interior angle of a regular polygon, then the angles of a triangle", method: "Interior angle of the polygon (or the angle at the outside point), then the angle asked for" },
  "2018 P1 Q10": { skill: "Substitute a given cosine into the cosine rule for an exact side", method: "Correct substitution into the cosine rule, evaluate the square of the side, then take the root" },
  "2018 P1 Q11": { skill: "Multiply top and bottom by the root, then simplify", method: "Express as an equivalent fraction with a rational denominator, then express in simplest form" },
  "2018 P1 Q12": { skill: "Use the quadrant to put the right sign on a known trigonometric value", method: "State the value - one mark" },
  "2018 P1 Q13": { skill: "Use an isosceles cross-section to place the far corner of a prism", method: "State one coordinate, state the other" },
  "2018 P1 Q14": { skill: "Square or take a root to undo the power, then rearrange", method: "Undo the operations in turn, one mark each, with the square or the square root taken at the point it applies" },
  "2018 P1 Q15": { skill: "Apply the power to the coefficient as well as the variable", method: "Start the process by taking the power to both parts of the product, then complete it" },
  "2018 P1 Q16": { skill: "Take the roots from the brackets, halve between them, and sketch", method: "Identify the roots, then the turning point or the y-intercept, then both of them on a consistently annotated sketch" },
  "2018 P1 Q17": { skill: "Find the height of a square-based pyramid from its volume", method: "Substitute into V = Ah/3 and solve" },
  "2018 P1 Q18": { skill: "Replace tan with sin/cos, or take out a common factor, then use sin^2+cos^2=1", method: "Identify and substitute the correct identity, then express the result in simplest form" },
  "2018 P1 Q19": { skill: "Complete the square, read off the axis, then solve for surd roots", method: "The bracket with the square, complete the process, state the axis of symmetry; then equate the completed square to zero, start to solve, solve, and complete" },
  "2018 P2 Q1": { skill: "Apply a multiplier once per year, then round as the question asks", method: "Know how to change by the rate, then know how to carry it across the years, then evaluate to the stated accuracy" },
  "2018 P2 Q2": { skill: "Radius and angle to the arc length, major or minor", method: "Appropriate fraction, consistent substitution into the arc length formula, then calculate the arc" },
  "2018 P2 Q3": { skill: "Square the components, add, and take an exact square root", method: "Start the process by squaring and adding the components, then the solution" },
  "2018 P2 Q4": { skill: "Expand, collect, solve — and reverse the sign if dividing by a negative", method: "Expand the bracket, then collect like terms, then solve" },
  "2018 P2 Q5": { skill: "Mean and standard deviation, then compare both with a second sample", method: "The mean, the squared differences, substitution into the formula, the standard deviation, then a valid comparison of the means and one of the standard deviations" },
  "2018 P2 Q6": { skill: "Given f(a) = b, solve for a", method: "Valid strategy, which is setting the function equal to the given value, then state the value of the unknown" },
  "2018 P2 Q7": { skill: "Halve the diameter, substitute into the volume of a sphere, and round", method: "Substitute, evaluate, round" },
  "2018 P2 Q8": { skill: "Isolate the ratio, take the inverse, then find both angles in the range", method: "Rearrange the equation, find one value of x, then find the other" },
  "2018 P2 Q9": { skill: "The angle given is on the line, so the triangle takes its supplement", method: "Correct substitution into the sine rule, rearrange it, then calculate the length" },
  "2018 P2 Q10": { skill: "Follow a route of four edges, two of them multiples of the given pair", method: "The pathway the long way round, then writing each piece as a multiple and collecting" },
  "2018 P2 Q11": { skill: "Divide by the multiplier to recover the original quantity", method: "Know that the given amount is (100 +/- r)% of the original, then begin a valid strategy, then complete the calculation within it" },
  "2018 P2 Q12": { skill: "Drop a perpendicular to the chord, use Pythagoras, add or subtract the radius", method: "Marshal the facts and recognise the right-angled triangle, then a consistent Pythagoras statement, then calculate the third side, then the length asked for" },
  "2018 P2 Q13": { skill: "Cosine rule for the angle, then add or subtract from a given bearing", method: "Correct substitution into the cosine rule, calculate the cosine, calculate the angle, then calculate the bearing" },
  "2018 P2 Q14": { skill: "Set x = 0 to find where the line crosses the y-axis", method: "Substitute x = 0, or isolate the term in y, then state the coordinates" },
  "2018 P2 Q15": { skill: "Multiply by the reciprocal, factorise, cancel", method: "Start the division by multiplying by the reciprocal, then factorise, then multiply and express in simplest form" },
  "2018 P2 Q16": { skill: "Space diagonal, then decide whether an object fits inside", method: "As above, then a valid conclusion with the comparison against the object's length" },
  "2018 P2 Q17": { skill: "Subtract a sector from the triangle that shares its apex and its angle", method: "The triangle by (1/2)ab sin C, the fraction of the circle, the sector area, know to subtract, then evaluate with units" },
  "2018 P2 Q18": { skill: "Assume similar, find the contradiction, then scale back with a cube root", method: "State the linear scale factor, know to multiply the volume by its cube, then the calculation with a valid comparison and conclusion; then find the volume scale factor and a calculation involving a root of it" },
  "2019 P1 Q1": { skill: "Substitute a value, usually negative, into f(x)", method: "Substitute the value into f(x), then evaluate" },
  "2019 P1 Q2": { skill: "Multiply a mixed number by a fraction or another mixed number", method: "Start to multiply the fractions, which means converting to improper fractions first, then a consistent answer in simplest form" },
  "2019 P1 Q3": { skill: "Expand a binomial times a trinomial, giving a term in x cubed", method: "Start to expand, evidenced by any three correct terms, then complete the expansion, then collect like terms" },
  "2019 P1 Q4": { skill: "The same with pi taken as 3.14, which is a different sum", method: "Appropriate fraction, correct substitution into the arc length formula with pi taken as 3.14, then calculate the arc" },
  "2019 P1 Q5": { skill: "Median and IQR, then one comparison of average and one of spread", method: "The median, the quartiles, the interquartile range, then a valid comparison of the medians and one of the interquartile ranges" },
  "2019 P1 Q6": { skill: "Read two points off a ruled scattergraph, find the line, then use it", method: "3 + 1, the same four as straight-line.best-fit - gradient, substitute a point, state the equation in the question letters, then evaluate" },
  "2019 P1 Q7": { skill: "Clear the fraction first, then isolate the subject", method: "Clear the constant term, clear the fractional coefficient, then divide by what is left" },
  "2019 P1 Q8": { skill: "Build both equations from a context, solve, answer in units", method: "Construct an equation for each situation, then correct scaling, a value, the other value, and the answer communicated in its units" },
  "2019 P1 Q9": { skill: "Read a maximum turning point off a graph and match it to y = b - (x - a)^2", method: "The axis of symmetry from the turning point, then a, then b" },
  "2019 P1 Q10": { skill: "Follow a pathway through a midpoint, in component form", method: "1 for the direct pathway, then 2: a valid pathway through the midpoint, then consistent components" },
  "2019 P1 Q11": { skill: "Equal angles at the centre of a regular polygon, a straight line, then isosceles radii", method: "Angle AOB from the equal division, then FOB on the straight line, then OFB" },
  "2019 P1 Q12": { skill: "Divide one surd by another and leave a rational denominator", method: "A rational denominator, then the numerator in simplest form, then the whole fraction in simplest form" },
  "2019 P1 Q13": { skill: "Compute a turning point of a shifted trigonometric graph", method: "Find the x of the turning point by shifting the unshifted one, then state the coordinates" },
  "2019 P1 Q14": { skill: "Multiply every term by the lowest common multiple, then solve", method: "Eliminate the denominators, rearrange into ax = b, solve" },
  "2019 P1 Q15": { skill: "Solve a quadratic model for the moment it falls below where it started", method: "Evaluate the height at a given time, then set the equation equal to the negative drop, rearrange to zero, factorise and reject the negative root" },
  "2019 P2 Q1": { skill: "Count the years between two dates, then apply the multiplier that many times", method: "Multiplier, then the number of years worked out from the two dates, then evaluate" },
  "2019 P2 Q2": { skill: "Square the components, add, and take an exact square root", method: "Start the process by squaring and adding the components, then the solution" },
  "2019 P2 Q3": { skill: "Half ab sin C, with the angle between the two given sides", method: "Correct substitution into the area of a triangle formula, then calculate the area" },
  "2019 P2 Q4": { skill: "Multiply, divide or take a percentage, then express in scientific notation", method: "Correct method, then evaluate and write in scientific notation" },
  "2019 P2 Q5": { skill: "Place a circle from the two axes it touches, then a point above it", method: "State one coordinate, state the other" },
  "2019 P2 Q6": { skill: "Substitute into the formula and round as the question asks", method: "Correct substitution into the quadratic formula, then evaluate the discriminant, then both roots at the stated accuracy" },
  "2019 P2 Q7": { skill: "Three sides, find an angle — often the smallest", method: "Correct substitution into the cosine rule, evaluate the cosine, then calculate the angle" },
  "2019 P2 Q8": { skill: "Add a hemisphere to a cylinder, working the cylinder's height out of the total", method: "Hemisphere, cylinder, know to add, calculate, round" },
  "2019 P2 Q9": { skill: "Find a surcharge from the total that includes it", method: "Know that (100 + r)% is the total, divide back to the bill, then subtract to get the extra" },
  "2019 P2 Q10": { skill: "Write x^2+bx+c in the form (x+p)^2+q", method: "Correct bracket with square, then complete the process" },
  "2019 P2 Q11": { skill: "The same, but one distance has to be found from the total first", method: "Find the third distance from the total, then the same four: strategy, evaluation, an explicit comparison, and a conclusion with a valid reason" },
  "2019 P2 Q12": { skill: "Scale an area between similar sectors, and recover a sector angle from its area", method: "The linear scale factor, squared for areas, evaluated; then the larger sector area as a fraction of its circle, rearranged for the angle, evaluated" },
  "2019 P2 Q13": { skill: "Substitute into the gradient formula, then simplify", method: "Correct substitution into the gradient formula, then factorise the numerator as a difference of two squares, then take the common factor out of the denominator and simplify" },
  "2019 P2 Q14": { skill: "Isolate the ratio, take the inverse, then find both angles in the range", method: "Rearrange the equation, find one value of x, then find the other" },
  "2019 P2 Q15": { skill: "Common denominator, expand the numerator watching the sign, collect like terms", method: "Correct common denominator, then correct numerator, then remove the brackets and collect like terms" },
  "2019 P2 Q16": { skill: "Turn a root into a fractional index so the division law applies", method: "Apply a^m x ka^n = ka^(m+n), then show evidence of the square root as a power of a half, then complete the simplification" },
  "2019 P2 Q17": { skill: "Expand the square, then collect sin^2 + cos^2 into 1", method: "Expand the brackets, then simplify using sin squared plus cos squared equals one" },
  "2019 P2 Q18": { skill: "Drop a perpendicular to the chord, use Pythagoras, add or subtract the radius", method: "Marshal the facts and recognise the right-angled triangle, then a consistent Pythagoras statement, then calculate the third side, then the length asked for" },
  "2019 P2 Q19": { skill: "Two elevations from the ends of a base, find the height between them", method: "Correct substitution into the sine rule, rearrange it, calculate the intermediate length, consistent substitution into the right-angled trig formula, then calculate the height" },
  "2022 P1 Q1": { skill: "Evaluate the bracket first, then multiply - two operations", method: "Start the calculation correctly, which is the bracket over a common denominator, then a consistent answer in simplest form" },
  "2022 P1 Q2": { skill: "Substitute a value, usually negative, into f(x)", method: "Substitute the value into f(x), then evaluate" },
  "2022 P1 Q3": { skill: "Volume of a cone with pi taken as 3.14, without a calculator", method: "Substitute then calculate, keeping the fraction and 3.14 visible" },
  "2022 P1 Q4": { skill: "Straight line at the centre, isosceles radii, then the right angle at the tangent", method: "Angle COE at the centre, then OCE from the isosceles radii, then ACE" },
  "2022 P1 Q5": { skill: "Complete the square, then read off the turning point", method: "Correct bracket with square, complete the process consistently, then state the coordinates of the turning point" },
  "2022 P1 Q6": { skill: "Find the equation of the line through two given points", method: "Find the gradient, substitute it and a point, then state the equation in its simplest form" },
  "2022 P1 Q7": { skill: "Multiply up and subtract — the subject has no coefficient to divide out", method: "Multiply by the denominator, then subtract the constant term" },
  "2022 P1 Q8": { skill: "Read the amplitude off the axis and count the cycles for b", method: "State a, the amplitude read off the y-axis, then state b, the number of complete waves between 0 and 360" },
  "2022 P1 Q9": { skill: "Rearrange the cosine rule and give the cosine as a fraction", method: "Correct substitution into the cosine rule, then calculate the cosine in its simplest form" },
  "2022 P1 Q10": { skill: "Divide by the multiplier to recover the original quantity", method: "Know that the given amount is (100 +/- r)% of the original, then begin a valid strategy, then complete the calculation within it" },
  "2022 P1 Q11": { skill: "Combine powers to a negative index, then write it with a positive power", method: "Apply the power of a power, then add the powers, then express the result with a positive power" },
  "2022 P1 Q12": { skill: "Multiply by the reciprocal, then cancel a repeated factor", method: "Start the division by multiplying by the reciprocal, then simplify" },
  "2022 P1 Q13": { skill: "Expand, simplify the resulting surd, then collect like surds", method: "Expand the bracket, then express the surd in simplest form, then complete the simplification by collecting like surds" },
  "2022 P1 Q14": { skill: "Take the roots from the brackets, halve between them, and sketch", method: "Identify the roots, then the turning point or the y-intercept, then both of them on a consistently annotated sketch" },
  "2022 P1 Q15": { skill: "Equate a triangle and a rectangle, clear the fraction, solve", method: "1 for the triangle area, then 4: equate, start to solve, rearrange, solve" },
  "2022 P2 Q1": { skill: "Expand a binomial times a trinomial, giving a term in x cubed", method: "Start to expand, evidenced by any three correct terms, then complete the expansion, then collect like terms" },
  "2022 P2 Q2": { skill: "Apply a multiplier once per year, then round as the question asks", method: "Know how to change by the rate, then know how to carry it across the years, then evaluate to the stated accuracy" },
  "2022 P2 Q3": { skill: "Add a sphere to a cuboid, working the cuboid's height out of the total", method: "Sphere, cuboid and add, calculate with units — three marks, not five" },
  "2022 P2 Q4": { skill: "Build both equations from a context, solve, answer in units", method: "Construct an equation for each situation, then correct scaling, a value, the other value, and the answer communicated in its units" },
  "2022 P2 Q5": { skill: "Mean and standard deviation, then compare both with a second sample", method: "The mean, the squared differences, substitution into the formula, the standard deviation, then a valid comparison of the means and one of the standard deviations" },
  "2022 P2 Q6": { skill: "Half ab sin C, with the angle between the two given sides", method: "Correct substitution into the area of a triangle formula, then calculate the area" },
  "2022 P2 Q7": { skill: "Substitute into the formula and round as the question asks", method: "Correct substitution into the quadratic formula, then evaluate the discriminant, then both roots at the stated accuracy" },
  "2022 P2 Q8": { skill: "Drop a perpendicular to the chord, use Pythagoras, add or subtract the radius", method: "Marshal the facts and recognise the right-angled triangle, then a consistent Pythagoras statement, then calculate the third side, then the length asked for" },
  "2022 P2 Q9": { skill: "Isolate the ratio, take the inverse, then find both angles in the range", method: "Rearrange the equation, find one value of x, then find the other" },
  "2022 P2 Q10": { skill: "The arc as a fraction of the circumference gives the angle", method: "An expression for the arc length, or the arc-to-circumference ratio, then know how to find the angle from it, then calculate the angle" },
  "2022 P2 Q11": { skill: "Face diagonal first, then the space diagonal", method: "Start the strategy with the face diagonal, continue it to the space diagonal, then calculate its length" },
  "2022 P2 Q12": { skill: "Factorise numerator and denominator, then cancel", method: "Factorise the numerator, factorise the denominator, then cancel the brackets correctly" },
  "2022 P2 Q13": { skill: "Split into separate fractions, then simplify each", method: "Express as separate fractions, then simplify" },
  "2022 P2 Q14": { skill: "Two elevations from one side, using the angle on a straight line", method: "Correct substitution into the sine rule, rearrange, calculate the slant length, then a valid strategy for the ground distance, then calculate it" },
  "2023 P1 Q1": { skill: "Divide a mixed number by a fraction or a whole number", method: "Convert to improper fractions and multiply by the reciprocal, then a consistent answer in simplest form" },
  "2023 P1 Q2": { skill: "Expand a product and a single bracket, then collect like terms", method: "Start the expansion, then complete it, then collect like terms" },
  "2023 P1 Q3": { skill: "Scale, eliminate, substitute back", method: "Correct scaling, then a value for one variable, then a value for the other" },
  "2023 P1 Q4": { skill: "Read a and b off a turning point, then find where the curve cuts the y-axis", method: "State a, state b, then find c by putting x = 0 into the equation" },
  "2023 P1 Q5": { skill: "Calculate b^2-4ac and state the nature of the roots", method: "Calculate the discriminant, then state the nature of the roots" },
  "2023 P1 Q6": { skill: "Substitute a given cosine into the cosine rule for an exact side", method: "Correct substitution into the cosine rule, evaluate the square of the side, then take the root" },
  "2023 P1 Q7": { skill: "Read two points off a ruled scattergraph, find the line, then use it", method: "3 + 1, the same four as straight-line.best-fit - gradient, substitute a point, state the equation in the question letters, then evaluate" },
  "2023 P1 Q8": { skill: "Multiply top and bottom by the root, then simplify", method: "Express as an equivalent fraction with a rational denominator, then express in simplest form" },
  "2023 P1 Q9": { skill: "Median and IQR, then one comparison of average and one of spread", method: "The median, the quartiles, the interquartile range, then a valid comparison of the medians and one of the interquartile ranges" },
  "2023 P1 Q10": { skill: "Drop a perpendicular to the chord, use Pythagoras, add or subtract the radius", method: "Marshal the facts and recognise the right-angled triangle, then a consistent Pythagoras statement, then calculate the third side, then the length asked for" },
  "2023 P1 Q11": { skill: "Use the quadrant to put the right sign on a known trigonometric value", method: "State the value - one mark" },
  "2023 P1 Q12": { skill: "Combine powers to a negative index, then write it with a positive power", method: "Apply the power of a power, then add the powers, then express the result with a positive power" },
  "2023 P1 Q13": { skill: "Separate a sideways shift from a vertical one on a trig graph", method: "State a from the sideways shift, then b from how far the whole wave has been lifted" },
  "2023 P1 Q14": { skill: "Multiply through by the lowest common multiple, then solve", method: "Eliminate the denominators, then rearrange into ax > b, then solve" },
  "2023 P2 Q1": { skill: "One rate for the first year, a different rate for the years after", method: "Know how to decrease by both rates, then know how to calculate the value, then evaluate" },
  "2023 P2 Q2": { skill: "As above, then round the answer to three significant figures", method: "Correct method, then evaluate, then express in scientific notation rounded to three significant figures" },
  "2023 P2 Q3": { skill: "Radius and angle to the arc length, major or minor", method: "Appropriate fraction, consistent substitution into the arc length formula, then calculate the arc" },
  "2023 P2 Q4": { skill: "Pair each side with its opposite angle, then find the acute angle", method: "Correct substitution into the sine rule, rearrange it, then calculate the angle" },
  "2023 P2 Q5": { skill: "A right angle plus the exterior angle of a regular polygon", method: "Interior or exterior angle of the polygon, then the shaded angle" },
  "2023 P2 Q6": { skill: "Divide by the multiplier to recover the original quantity", method: "Know that the given amount is (100 +/- r)% of the original, then begin a valid strategy, then complete the calculation within it" },
  "2023 P2 Q7": { skill: "Clear the fraction first, then isolate the subject", method: "Clear the constant term, clear the fractional coefficient, then divide by what is left" },
  "2023 P2 Q8": { skill: "Compare the two shorter sides squared with the longest squared, and conclude", method: "Valid strategy, then evaluation, then an explicit comparison, then a conclusion with a valid reason" },
  "2023 P2 Q9": { skill: "Subtract a similar pyramid from a pyramid, finding the large height first", method: "Small pyramid, large pyramid, know to subtract, calculate with units" },
  "2023 P2 Q10": { skill: "Common denominator, expand the numerator watching the sign, collect like terms", method: "Correct common denominator, then correct numerator, then remove the brackets and collect like terms" },
  "2023 P2 Q11": { skill: "Solve a given height formula for the angle, in a range", method: "Substitute the given height into the formula, rearrange it, calculate one value of x, then the second" },
  "2023 P2 Q12": { skill: "Factorise numerator and denominator, then cancel", method: "Factorise the numerator, factorise the denominator, then cancel the brackets correctly" },
  "2023 P2 Q13": { skill: "Replace tan with sin/cos, or take out a common factor, then use sin^2+cos^2=1", method: "Identify and substitute the correct identity, then express the result in simplest form" },
  "2023 P2 Q14": { skill: "Turn a cuboid volume into a quadratic, then solve it", method: "2 for the volume expression and the rearrangement, 4 for the formula" },
  "2023 P2 Q15": { skill: "Sine from the small triangle, then the area formula run backwards", method: "The correct trig ratio, correct substitution into the area of a triangle formula, form the equation, then solve it for the length" },
  "2024 P1 Q1": { skill: "Subtract mixed numbers, or a fraction from a mixed number", method: "Identify a common denominator, then a consistent answer" },
  "2024 P1 Q2": { skill: "Substitute a value, usually negative, into f(x)", method: "Substitute the value into f(x), then evaluate" },
  "2024 P1 Q3": { skill: "Expand a binomial times a trinomial, giving a term in x cubed", method: "Start to expand, evidenced by any three correct terms, then complete the expansion, then collect like terms" },
  "2024 P1 Q4": { skill: "Scale two vectors and combine them, answering in component form", method: "Calculate the scalar multiple, then the solution in component form" },
  "2024 P1 Q5": { skill: "Median and IQR, then one comparison of average and one of spread", method: "The median, the quartiles, the interquartile range, then a valid comparison of the medians and one of the interquartile ranges" },
  "2024 P1 Q6": { skill: "Simplify each surd to a common root, then subtract the coefficients", method: "Simplify the surds so they share a root, then complete the simplification by combining the coefficients" },
  "2024 P1 Q7": { skill: "Scale, eliminate, substitute back", method: "Correct scaling, then a value for one variable, then a value for the other" },
  "2024 P1 Q8": { skill: "Read the amplitude off the axis and count the cycles for b", method: "State a, the amplitude read off the y-axis, then state b, the number of complete waves between 0 and 360" },
  "2024 P1 Q9": { skill: "Read two points off a graph, find the equation, then use it", method: "Find the gradient, substitute it with one of the points, state the equation in the question own letters and in simplest form, then evaluate it at a given value" },
  "2024 P1 Q10": { skill: "Angle at the centre twice the angle at the circumference, then a quadrilateral with two right angles", method: "Angle OFD, then BOD as twice it, then BCD" },
  "2024 P1 Q11": { skill: "Rearrange into y = mx + c and read off the gradient", method: "Isolate the term in y, or divide throughout, then state the gradient explicitly" },
  "2024 P1 Q12": { skill: "Complete the square, read the turning point, then reflect a point in the axis of symmetry", method: "The bracket and the completed square, then the turning point, then the x and the y of Q" },
  "2024 P1 Q13": { skill: "Expand a bracket whose terms carry fractional and negative indices", method: "Apply one of the two multiplications, then apply both and simplify" },
  "2024 P1 Q14": { skill: "The linear scale factor applied to a whole side, then what is left", method: "Scale factor, scale the whole side consistently, then subtract" },
  "2024 P2 Q1": { skill: "Apply a multiplier once per year, then round as the question asks", method: "Know how to change by the rate, then know how to carry it across the years, then evaluate to the stated accuracy" },
  "2024 P2 Q2": { skill: "Multiply, divide or take a percentage, then express in scientific notation", method: "Correct method, then evaluate and write in scientific notation" },
  "2024 P2 Q3": { skill: "Three sides, find an angle — often the smallest", method: "Correct substitution into the cosine rule, evaluate the cosine, then calculate the angle" },
  "2024 P2 Q4": { skill: "Expand, collect, solve — and reverse the sign if dividing by a negative", method: "Expand the bracket, then collect like terms, then solve" },
  "2024 P2 Q5": { skill: "Divide by the multiplier to recover the original quantity", method: "Know that the given amount is (100 +/- r)% of the original, then begin a valid strategy, then complete the calculation within it" },
  "2024 P2 Q6": { skill: "Factorise, then hence simplify — the scaffolded two-part form", method: "Factorise for part (a), then factorise the denominator and simplify for part (b)" },
  "2024 P2 Q7": { skill: "Subtract a hemisphere from a cuboid", method: "Hemisphere, cuboid and subtract, calculate, round" },
  "2024 P2 Q8": { skill: "Substitute into the formula and round as the question asks", method: "Correct substitution into the quadratic formula, then evaluate the discriminant, then both roots at the stated accuracy" },
  "2024 P2 Q9": { skill: "Multiply up, subtract, divide — the subject sits in a numerator", method: "Multiply by the denominator, subtract the constant term, divide by the coefficient - one mark per operation" },
  "2024 P2 Q10": { skill: "Drop a perpendicular to the chord, use Pythagoras, add or subtract the radius", method: "Marshal the facts and recognise the right-angled triangle, then a consistent Pythagoras statement, then calculate the third side, then the length asked for" },
  "2024 P2 Q11": { skill: "Isolate the ratio, take the inverse, then find both angles in the range", method: "Rearrange the equation, find one value of x, then find the other" },
  "2024 P2 Q12": { skill: "Common denominator, expand the numerator, collect like terms", method: "Correct common denominator, then correct numerator, then remove the brackets and collect like terms" },
  "2024 P2 Q13": { skill: "Sine rule for a slant side, then the right angle at the foot", method: "Correct substitution into the sine rule, rearrange it, calculate the intermediate length, consistent substitution into the right-angled trig formula, then calculate the perpendicular" },
  "2024 P2 Q14": { skill: "Use a diagonal and a midpoint to cross a rhombus", method: "1 for the side from the diagonal, then 2: the pathway through the midpoint, then collecting it" },
  "2024 P2 Q15": { skill: "The arc gives the angle, and the angle gives the area", method: "The correct fraction, or start the strategy for finding the angle, then know how to calculate the sector area, then calculate it" },
  "2024 P2 Q16": { skill: "Substitute cos^2 = 1 - sin^2, then collect terms into the given form", method: "A valid substitution, then express the result in the form the question asks for" },
  "2025 P1 Q1": { skill: "Multiply a mixed number by a fraction or another mixed number", method: "Start to multiply the fractions, which means converting to improper fractions first, then a consistent answer in simplest form" },
  "2025 P1 Q2": { skill: "Expand a product and a single bracket, then collect like terms", method: "Start the expansion, then complete it, then collect like terms" },
  "2025 P1 Q3": { skill: "Order the data, find the quartiles, then the (semi-)interquartile range", method: "Find the quartiles, then calculate the range" },
  "2025 P1 Q4": { skill: "Divide by the multiplier to recover the original quantity", method: "Know that the given amount is (100 +/- r)% of the original, then begin a valid strategy, then complete the calculation within it" },
  "2025 P1 Q5": { skill: "Half ab sin C with the sine given as a fraction, no calculator", method: "Correct substitution into the area formula, then calculate the area" },
  "2025 P1 Q6": { skill: "Find the equation of a line from two points marked on a sketch", method: "Calculate the gradient, substitute it with a point into y = mx + c or y - b = m(x - a), then state the equation in simplest form" },
  "2025 P1 Q7": { skill: "Evaluate f at a value, then solve f(a) = b for a", method: "State f at the given value for part (a), then for part (b) a valid strategy and the value of the unknown" },
  "2025 P1 Q8": { skill: "Compute a turning point of a shifted trigonometric graph", method: "Find the x of the turning point by shifting the unshifted one, then state the coordinates" },
  "2025 P1 Q9": { skill: "Read a and b off a turning point, watching the sign of a", method: "State a, then state b - a mark each" },
  "2025 P1 Q10": { skill: "Apply the power, multiplication and division laws in one expression", method: "Apply the power of a power, then multiply by adding the powers, then divide by subtracting them - a mark for each law" },
  "2025 P1 Q11": { skill: "Calculate b^2-4ac and state the nature of the roots", method: "Calculate the discriminant, then state the nature of the roots" },
  "2025 P1 Q12": { skill: "Multiply top and bottom by the root, then simplify", method: "Express as an equivalent fraction with a rational denominator, then express in simplest form" },
  "2025 P1 Q13": { skill: "Add two vectors in components and draw the resultant on a grid", method: "The components of p+q (or a nose-to-tail diagram), then the resultant drawn consistently" },
  "2025 P1 Q14": { skill: "Common denominator, expand the numerator watching the sign, collect like terms", method: "Correct common denominator, then correct numerator, then remove the brackets and collect like terms" },
  "2025 P1 Q15": { skill: "Equate two areas, factorise, and reject the root that is not a length", method: "1 for the area, 2 for the expansion and rearrangement, 3 for factorising, solving and rejecting the negative root" },
  "2025 P2 Q1": { skill: "Count the years between two dates, then apply the multiplier that many times", method: "Multiplier, then the number of years worked out from the two dates, then evaluate" },
  "2025 P2 Q2": { skill: "Halve the diameter, substitute into the volume of a sphere, and round", method: "Substitute, evaluate, round" },
  "2025 P2 Q3": { skill: "Multiply, divide or take a percentage, then express in scientific notation", method: "Correct method, then evaluate and write in scientific notation" },
  "2025 P2 Q4": { skill: "Mean and standard deviation, then compare both with a second sample", method: "The mean, the squared differences, substitution into the formula, the standard deviation, then a valid comparison of the means and one of the standard deviations" },
  "2025 P2 Q5": { skill: "Write x^2+bx+c in the form (x+p)^2+q", method: "Correct bracket with square, then complete the process" },
  "2025 P2 Q6": { skill: "Radius and angle to the area of the sector", method: "Appropriate fraction of the circle, consistent substitution into the area formula, then calculate the area" },
  "2025 P2 Q7": { skill: "Interior angle of a regular polygon, then the angles of a triangle", method: "Interior angle of the polygon (or the angle at the outside point), then the angle asked for" },
  "2025 P2 Q8": { skill: "Read a vertex off a cuboid on axes, then find a space diagonal", method: "State the coordinates, then start a valid strategy, continue it, and calculate the length of the space diagonal" },
  "2025 P2 Q9": { skill: "Clear the fraction first, then isolate the subject", method: "Clear the constant term, clear the fractional coefficient, then divide by what is left" },
  "2025 P2 Q10": { skill: "Build both equations from a context, solve, answer in units", method: "Construct an equation for each situation, then correct scaling, a value, the other value, and the answer communicated in its units" },
  "2025 P2 Q11": { skill: "Square the linear scale factor to scale an area", method: "Find the linear scale factor, multiply or divide the area by its square, then find the area" },
  "2025 P2 Q12": { skill: "Sine rule for the angle, then turn it back into a bearing", method: "Correct substitution into the sine rule, rearrange the equation, calculate the angle, then calculate the bearing" },
  "2025 P2 Q13": { skill: "Multiply every term by the lowest common multiple, then solve", method: "Eliminate the denominators, rearrange into ax = b, solve" },
  "2025 P2 Q14": { skill: "Solve a given height formula for the angle, in a range", method: "Substitute the given height into the formula, rearrange it, calculate one value of x, then the second" },
  "2025 P2 Q15": { skill: "Continue past a point by a fraction of the line already travelled", method: "The base as a sum and the fraction of it beyond the end, then the route from the third point" },
  "2026 P1 Q1": { skill: "Expand a binomial times a trinomial, giving a term in x cubed", method: "Start to expand, evidenced by any three correct terms, then complete the expansion, then collect like terms" },
  "2026 P1 Q2": { skill: "Recover a total when a part is given as a straight percentage of it", method: "Know that r% is the figure given, find 1%, multiply by 100 — both are Paper 1, so it divides by hand" },
  "2026 P1 Q3": { skill: "Median and IQR, then one comparison of average and one of spread", method: "The median, the quartiles, the interquartile range, then a valid comparison of the medians and one of the interquartile ranges" },
  "2026 P1 Q4": { skill: "Expand, collect, solve — and reverse the sign if dividing by a negative", method: "Expand the bracket, then collect like terms, then solve" },
  "2026 P1 Q5": { skill: "Read the operation from a worded situation and answer with units", method: "Start the addition with a common denominator, then complete it and state the units" },
  "2026 P1 Q6": { skill: "Read two points off a graph, find the equation, then use it", method: "Find the gradient, substitute it with one of the points, state the equation in the question own letters and in simplest form, then evaluate it at a given value" },
  "2026 P1 Q7": { skill: "Find a magnitude that does not come out whole, and simplify it", method: "Square and add, take the root, simplify the surd — one mark per skill the answer needs" },
  "2026 P1 Q8": { skill: "Square both sides, then move the one remaining term", method: "Square, then add — one mark per operation" },
  "2026 P1 Q9": { skill: "Substitute a point on a parabola to find its stretch", method: "Know to substitute the marked point into y = ax^2, then solve for a" },
  "2026 P1 Q10": { skill: "Two isosceles triangles from the radii, one reached through the right angle at a tangent", method: "Two isosceles triangles from the radii, one reached through the right angle at the tangent, then their sum" },
  "2026 P1 Q11": { skill: "Read coordinates off a fully lettered cuboid, and find a midpoint on one edge", method: "State G, then state the midpoint of CD" },
  "2026 P1 Q12": { skill: "Read the turning point off completed square form and sketch the curve", method: "State the turning point, sketch a parabola with a minimum turning point consistent with it, then the y-intercept" },
  "2026 P1 Q13": { skill: "Evaluate a trigonometric function at a quadrantal angle", method: "Substitute the value and work out the angle inside, then apply the exact value and multiply" },
  "2026 P1 Q14": { skill: "Factorise a quadratic whose x squared term has a coefficient, then solve", method: "Split the leading coefficient, complete the factorisation, then solve" },
  "2026 P2 Q1": { skill: "Apply a multiplier once per year, then round as the question asks", method: "Know how to change by the rate, then know how to carry it across the years, then evaluate to the stated accuracy" },
  "2026 P2 Q2": { skill: "Two sides and the angle between them, find the third side", method: "Correct substitution into the cosine rule, evaluate the square of the side, then take the root" },
  "2026 P2 Q3": { skill: "Cube the linear scale factor to scale a volume", method: "State the linear scale factor, state the volume scale factor, then calculate the volume and state its units" },
  "2026 P2 Q4": { skill: "Solve a constructed pair, then use both values on a new quantity", method: "1 + 1 + 4 as the question data gives, mapping onto the other five papers exactly except that the last mark applies the two values rather than stating them" },
  "2026 P2 Q5": { skill: "Use the bisected chord and Pythagoras to find the radius", method: "Halve the chord, state Pythagoras with the radius as the hypotenuse, then evaluate and take the root" },
  "2026 P2 Q6": { skill: "Find the height of a cone with the same volume as a given sphere", method: "2 for the sphere, 3 for the cone — read off the pattern the other years set" },
  "2026 P2 Q7": { skill: "Compare the two shorter sides squared with the longest squared, and conclude", method: "Valid strategy, then evaluation, then an explicit comparison, then a conclusion with a valid reason" },
  "2026 P2 Q8": { skill: "Isolate the ratio, take the inverse, then find both angles in the range", method: "Rearrange the equation, find one value of x, then find the other" },
  "2026 P2 Q9": { skill: "Divide algebraic fractions where the numerator factorises", method: "Start to divide by taking the reciprocal, factorise the difference of two squares, then cancel and state" },
  "2026 P2 Q10": { skill: "Equal vertices give the angle at the centre, then sector less triangle", method: "The angle from the number of vertices, express the sector as a fraction of the circle, evaluate it, the triangle, then subtract" },
  "2026 P2 Q11": { skill: "Take a power into a bracket in a denominator, then divide", method: "Take the power to both parts of the denominator, divide the powers of the variable, then assemble the answer over the coefficient" },
  "2026 P2 Q12": { skill: "Replace tan with sin/cos, or take out a common factor, then use sin^2+cos^2=1", method: "Identify and substitute the correct identity, then express the result in simplest form" },
  "2026 P2 Q13": { skill: "A wall on three sides grows the length twice and the width once", method: "The 1 + 2 + 4 the question data gives, split as 2015 P2 Q14 splits its identical parts" },
};
