/**
 * Writes the live app's AH markscheme files from the transcribed table, so the
 * app shows what the website shows.
 *
 *   npx tsx scripts/emit-app-ah-markschemes.mts [--check]
 *
 * The owner, 2026-09-27: "The new markscheme should be one that website uses",
 * and then "adding correct mark schemes to the app as well". The app shows AH
 * marking instructions on its six papers with no video (2016 to 2019, 2021),
 * from `Current Deployment/src/data/ah/markschemes/AH*MI.js`. Those were
 * machine-extracted; this replaces them with the same file names, exports and
 * shape (`{ year, papers: [{ paperNumber, questions: [{ questionNumber,
 * answer }] }] }`), so no app code changes.
 *
 * **One entry per card on the site, keyed by the card's own number** ("5",
 * "1(a)", "11(c)(d)"). The app's `getMarkschemeEntries` matches a card's
 * number exactly first, so each card finds only its own entry. Its content is
 * `cardScheme`: the card's rows, numbered as in the whole question, and its
 * notes.
 *
 * `--check` writes nothing and fails if a file would change.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { getAllAHQuestions } from '../lib/data-loader';
import { ahCard, cardScheme } from '../lib/course-markschemes';
import { PAPER_MARKSCHEME_AH } from '../lib/generator/generators/paper-markscheme-ah';

const APP = join(import.meta.dirname, '..', '..', 'Current Deployment', 'src', 'data', 'ah', 'markschemes');
const FILES: { year: number; paper: number; file: string; name: string }[] = [
  { year: 2016, paper: 1, file: 'AH2016MI.js', name: 'advHigherMaths2016Markscheme' },
  { year: 2017, paper: 1, file: 'AH2017MI.js', name: 'advHigherMaths2017Markscheme' },
  { year: 2018, paper: 1, file: 'AH2018MI.js', name: 'advHigherMaths2018Markscheme' },
  { year: 2019, paper: 1, file: 'AH2019MI.js', name: 'advHigherMaths2019Markscheme' },
  { year: 2021, paper: 1, file: 'AH2021_P1_MI.js', name: 'advHigherMaths2021P1Markscheme' },
  { year: 2021, paper: 2, file: 'AH2021_P2_MI.js', name: 'advHigherMaths2021P2Markscheme' },
];

// The table's text is already the site's HTML, with \( \) maths the app's MathJax reads.
function entryHtml(rows: ReturnType<typeof cardScheme>['rows'], notes: string[]): string {
  const body = rows.map(({ row, n }) =>
    `<tr class="border-t border-gray-700 align-top">` +
    `<td class="py-2 pr-3 whitespace-nowrap text-gray-300">${row.part ? `${row.part} ` : ''}&bull;<sup>${n + 1}</sup></td>` +
    `<td class="py-2 pr-3">${row.for}</td>` +
    `<td class="py-2">${row.shows}</td></tr>`).join('');
  const table =
    `<div class="overflow-x-auto"><table class="w-full text-sm text-left">` +
    `<thead><tr class="text-purple-300 text-xs uppercase tracking-wider">` +
    `<th class="py-2 pr-3">Mark</th><th class="py-2 pr-3">Awarded for</th><th class="py-2">Illustrative answer</th></tr></thead>` +
    `<tbody>${body}</tbody></table></div>`;
  const list = notes.length
    ? `<p class="text-purple-300 text-xs uppercase tracking-wider mt-3 mb-1">Notes</p>` +
      // In its own scroller, as the table is: a note holding a long line of
      // maths (2018 Q7's) would otherwise widen the page on a phone.
      `<div class="overflow-x-auto"><ul class="text-sm text-gray-300 space-y-1">${notes.map(n => `<li>${n}</li>`).join('')}</ul></div>`
    : '';
  return table + list;
}

const questions = await getAllAHQuestions();
let changed = 0, cards = 0;
for (const f of FILES) {
  const mine = questions.filter(q => Number(q.year) === f.year && q.paperNumber === f.paper);
  const entries: { questionNumber: string; answer: string }[] = [];
  for (const q of mine) {
    const card = ahCard(q.question);
    if (!card) throw new Error(`${f.file}: a card with no AH label: ${q.question.slice(0, 80)}`);
    const scheme = PAPER_MARKSCHEME_AH[card.label];
    if (!scheme) throw new Error(`${card.ref}: no transcription in the table`);
    const own = cardScheme(scheme, card.parts);
    if (!own.rows.length) throw new Error(`${card.ref}: no rows for its parts`);
    entries.push({ questionNumber: card.ref.replace(/^.* Q/, ''), answer: entryHtml(own.rows, own.notes) });
    cards++;
  }
  const out = `// ${f.year}${f.file.includes('_P') ? ` Paper ${f.paper}` : ''} Advanced Higher marking instructions.
// GENERATED by website-v1/scripts/emit-app-ah-markschemes.mts from the
// transcribed marking instructions (the table the website uses). Do not edit
// by hand. Contains information reproduced from Qualifications Scotland
// marking instructions on a non-commercial basis, with Qualifications Scotland
// acknowledged as the source.
export const ${f.name} = ${JSON.stringify({ year: f.year, papers: [{ paperNumber: f.paper, questions: entries }] }, null, 2)};
`;
  const path = join(APP, f.file);
  const before = existsSync(path) ? readFileSync(path, 'utf8') : '';
  if (before.replace(/\r\n/g, '\n') !== out) {
    changed++;
    if (!process.argv.includes('--check')) writeFileSync(path, out, 'utf8');
    console.log(`${process.argv.includes('--check') ? 'would change' : 'wrote'} ${f.file}: ${entries.length} cards`);
  }
}
console.log(`${cards} cards across ${FILES.length} files; ${changed} changed`);
if (process.argv.includes('--check') && changed) process.exit(1);
