/**
 * Advanced Higher, Differentiation: what each card is.
 * The routines are in `../routines/differentiation.ts`, under the same labels.
 */
import type { CardMeta } from '../types';

export const DIFFERENTIATION: readonly CardMeta[] = [
  {
    card: '2026 P1 Q1',
    skill: 'Differentiate a product with a secant, then a quotient with an exponential, simplified.',
    marks: [2, 3],
    route: '2 + 3 - (a) the product rule with one term right, then both terms, the chain rule bringing out the k from sec kx; (b) the quotient rule with the denominator and one term of the numerator right, then the whole numerator, then simplified by taking out the exponential and collecting the numerator. (a) asks for no simplifying, so its mark is for the two terms as they stand.',
    ranges: 'The paper: 3x^4 sec 2x, and e^{5x}/(2x + 1). (a) c x^n sec kx with c from 2 to 5, n from 2 to 5 and k from 2 to 5, always sec, as the paper. (b) e^{px}/(ax + b) with p from 2 to 6, a from 2 to 4, b from 1 to 5, a and b coprime so the denominator is as simple as the paper\'s; the simplified numerator px(a) + (pb - a) keeps a constant term (pb is not a) and its two coefficients share no factor, as 10x + 3 does, so there is one simplest form. All exact: Paper 1.',
  },
  {
    card: '2026 P2 Q1',
    skill: 'Differentiate a multiple of an inverse sine of a multiple of x.',
    marks: [2],
    route: 'The derivative of the inverse sine with the coefficient kept in front, c over the root of 1 - (kx)^2; then the chain rule\'s factor k, giving ck over the root of 1 - k^2 x^2. Leaving out the k loses the second mark.',
    ranges: 'The paper: 3 sin^{-1} 7x. c from 2 to 9 and k from 2 to 9, whole numbers as the paper\'s, never 1 (a 1 would drop the first mark\'s coefficient or the chain rule\'s factor). Always the inverse sine: the inverse tangent is another paper\'s card (2016 Q1(a)).',
  },
  {
    card: '2026 P2 Q5',
    skill: 'Differentiate x to the power kx by logarithmic differentiation, the answer in x.',
    marks: [5],
    route: 'Take logs and bring the power down, ln y = kx ln x; the left side as (1/y) dy/dx; the product rule on the right, one term then both, k ln x + kx(1/x); then dy/dx = x^{kx}(k ln x + k), with y replaced so the answer is in x alone, and factorised, k x^{kx}(ln x + 1), as the paper\'s answer also gives it.',
    ranges: 'The paper: y = x^{4x}. k whole from 2 to 12 or a half from 1/2 to 11/2, positive or negative, 34 questions (the owner, 2026-09-29: negative k, "Accept recommendation"; then widened, "Yes to both", with the factorised answer). x^{3x/2} is the same four steps with a fraction coefficient. Nothing else in the power, so no step the paper does not have.',
  },
  {
    card: '2026 P2 Q7',
    skill: 'Differentiate a parametric curve and find its stationary point, one parameter value rejected.',
    marks: [2, 2],
    route: '2 + 2 - (a) dx/dt = ca/(at + b) by the chain rule on the log, then dy/dx = (dy/dt)/(dx/dt) as one simplified fraction, (t0 - t)(at + b)/ca; (b) dy/dx = 0 gives t = t0 or t = -b/a, the negative one rejected because t > 0, and the point (c ln(a t0 + b), t0^2/2).',
    ranges: 'The paper: x = 3 ln(2t + 1), y = t - t^2/2, stationary at t = 1, the point (3 ln 3, 1/2). x = c ln(at + b) with c from 2 to 6, a from 2 to 4, b from 1 to 5 coprime with a, so the rejected root -b/a is negative and the fraction has no common factor to cancel; y = t0 t - t^2/2 with t0 from 1 to 3, keeping the paper\'s half t squared. The point is exact: a log and a half or whole number.',
  },
  {
    card: '2026 P2 Q8',
    skill: 'Related rates: the rate the depth falls from a volume formula and a pumping rate.',
    marks: [4],
    route: 'dV/dt as minus the pumping rate; dV/dh by the chain rule on the bracket, A n (b + h^{1/2})^{n-1} times h^{-1/2}/2; the chain rule linking dh/dt, dh/dV and dV/dt; then dh/dt at the given depth, exact, with its units and "dh/dt =" written.',
    ranges: 'The paper: V = 18(2 + sqrt h)^6 - 1152, 0.6 m^3/s, depth 9. V = A(b + sqrt h)^n - A b^n (the constant makes V zero at zero depth, as 1152 = 18 x 2^6 does) with A from 6 to 24, b 1 or 2, n from 4 to 6; the rate 0.2 to 0.9; the depth a square, 4 to 36, so its root is whole. dV/dh at that depth is a whole number, as 56 250 is, so dh/dt is one fraction.',
  },
  {
    card: '2026 P2 Q10',
    skill: 'Implicit differentiation with a product of x and an exponential in y, then why the derivative is never zero.',
    marks: [4, 1],
    route: '4 + 1 - (a) the product rule on x^2 e^{ky}, one term then both, with dy/dx on the y term; the other terms, 2x and m y^{m-1} dy/dx, and = 0; then dy/dx made the subject, -2x(e^{ky} + 1)/(k x^2 e^{ky} + m y^{m-1}); (b) for x > 0 the numerator is never zero, since -2x is not and e^{ky} + 1 is positive. Talking about the denominator does not earn the mark.',
    ranges: 'The paper: x^2 e^{6y} + x^2 + y^5 = 50. k from 2 to 9, the power m from 3 to 7, never both even (then the answer\'s top and bottom share a 2, and the paper\'s has no common factor), the constant from 20 to 90. The two x^2 terms keep coefficient 1, as the paper, so the numerator factorises as -2x(e^{ky} + 1) and (b)\'s reason is the paper\'s.',
  },
  {
    card: '2026 P2 Q16',
    skill: 'Differentiate ln(cos x); use it to finish an integration by parts, then find the function by parts was done on.',
    marks: [2, 2, 1],
    route: '2 + 2 + 1 - (a) 1/cos x times the derivative of cos x, -tan x, shown; (b)(i) from (a) the integral of m tan kx is -(m/k) ln(cos kx), then the limits in, exact; (b)(ii) comparing with the parts formula, v = m tan kx is what was integrated, so g(x) = mk sec^2 kx.',
    ranges: 'The paper: 2x tan 2x - integral of 2 tan 2x, from 0 to pi/6, g(x) = 4 sec^2 2x. k from 2 to 4 and m = k or 2k, so the log\'s coefficient m/k stays whole (the paper\'s is 1); the upper limit makes kx pi/3 (the paper), pi/4 or pi/6, the angles with exact tan and cos. (a) is the paper\'s own "show that", unchanged.',
  },
  {
    card: '2025 P1 Q2',
    skill: 'Differentiate a cubic over a linear expression by the quotient rule, and simplify.',
    marks: [3],
    route: 'The quotient rule with the denominator squared and one term of the numerator right; then the whole numerator; then simplified, the numerator expanded and collected. The x terms cancel, so the simplified top is a cubic with no x term, as the paper\'s 8x^3 + 18x^2 + 3.',
    ranges: 'The paper: (2x^3 + x)/(3 + 2x). f(x) = (ax^3 + bx)/(c + dx), in the paper\'s order, with a from 1 to 3, b from ±1 to ±4, c from 1 to 5 and d from 1 to 3; a and b share no factor, nor c and d, as the paper\'s; the top is never zero where the bottom is, so nothing cancels; and the answer\'s numerator has no common factor, as 8, 18 and 3 have none, so it is as simple as the paper\'s. A negative b is a sign, not a step. All exact: Paper 1.',
  },
  {
    card: '2025 P2 Q1',
    skill: 'Differentiate an inverse cosine of a multiple of x.',
    marks: [2],
    route: 'The derivative of the inverse cosine, minus one over the root of 1 - (kx)^2; then the chain rule\'s factor k. Leaving out the k loses the second mark.',
    ranges: 'The paper: cos^{-1} 4x. k from 2 to 9, a whole number as the paper\'s 4, never 1. Always the inverse cosine: a different function is a different card. The paper\'s k alone makes 8 questions, below the floor, so a number in front, c from 1 (the paper) to 3, as 2026 P2 Q1\'s 3 sin^{-1} 7x has: it rides along as a coefficient, not a step. 24 questions.',
  },
  {
    card: '2025 P2 Q2',
    skill: 'Differentiate implicitly with a product of x and an exponential in y, and make dy/dx the subject.',
    marks: [3],
    route: 'The product rule on b x e^{my}, the e^{my} term picking up dy/dx; then every term differentiated and the equation written; then dy/dx made the subject, (c - b e^{my})/(2a y + bm x e^{my}).',
    ranges: 'The paper: 2y^2 + 4xe^{2y} = 3x. a y^2 + b x e^{my} = c x with a from 1 to 4, b from 2 to 6, m from 2 to 5, c from 1 to 9; c, b and 2a share no factor, so the answer has none to cancel, as the paper\'s 3, 4, 4, 8 have none. The shape is the paper\'s: a y^2 term, the product, and a multiple of x on the right.',
  },
  {
    card: '2025 P2 Q5',
    skill: 'Differentiate x to the power a cot x by logarithmic differentiation, the answer in x.',
    marks: [5],
    route: 'Take logs, ln y = a cot x ln x; the left side as (1/y) dy/dx; the product rule on the right, one term then both, -a cosec^2 x ln x + a cot x (1/x); then dy/dx = x^{a cot x}(-a cosec^2 x ln x + a cot x/x), with y replaced so the answer is in x.',
    ranges: 'The paper: y = x^{cot x}. Always cot x in the power: a different function is a different card. A number before it, a from ±1 to ±9 (the paper\'s 1), as the owner widened 2026 P2 Q5\'s x^{4x} with negative and bigger k: a coefficient, not a step. Nothing inside the cot (a k there adds a chain rule the paper does not have). 18 questions.',
  },
  {
    card: '2025 P2 Q7',
    skill: 'A parametric curve\'s first derivative, then its second by the quotient rule and dx/dt.',
    marks: [2, 3],
    route: '2 + 3 - (a) dy/dt, then dy/dx = (dy/dt)/(dx/dt) in t; (b) the quotient rule on (a)\'s answer with the denominator and one term right, then complete, then divided by dx/dt again for d^2y/dx^2. The t-derivative alone is not the second derivative.',
    ranges: 'The paper: x = t^2, y = tan t. x = a t^2 and y = b tan t, a from 1 to 4 and b from 1 to 5, b never a multiple of 2a, so dy/dx keeps a number times t below the line, as the paper\'s 2t, and (b)\'s quotient rule is the paper\'s shape. Always tan t, nothing inside it (a k there adds a chain rule). 16 questions.',
  },
  {
    card: '2025 P2 Q9',
    skill: 'Rectilinear motion: displacement from velocity with its constant, then why the acceleration is positive.',
    marks: [2, 2],
    route: '2 + 2 - (a) v integrated with its constant, then the constant from s = 0 at t = 0 (e^0 = 1) and s stated; (b) the acceleration dv/dt, then the reason: e^{kt} > 0.',
    ranges: 'The paper: v = 2t + e^{5t}. v = a t + e^{kt} with a from 1 to 9 and k from 2 to 9, both positive so the acceleration a + k e^{kt} is always positive, as the paper\'s: (b) is a "show that" and must stay true. The e term keeps coefficient 1, as the paper\'s. 72 questions.',
  },
  {
    card: '2025 P2 Q17',
    skill: 'Related rates: the depth\'s rate of change with water piped in and leaking out.',
    marks: [4],
    route: 'The chain rule linking dh/dt, dh/dV and dV/dt; dV/dh; dV/dt as the rate in minus the leak; then dh/dt at the depth, with its units and "dh/dt =" written.',
    ranges: 'The paper: V = h^3/5, 6 cm^3/s in, sqrt(h)/10 out, h = 400, dh/dt = 1/24000. V = h^3/m with m from 2 to 6; the leak sqrt(h)/L with L 5, 10 (the paper) or 20; the depth h = s^2 with s a multiple of L, so the leak there, s/L, is whole (1 to 4), as the paper\'s 2; the rate in is more than the leak by 1 to 6, so the depth rises, as the paper\'s. dh/dt is one exact fraction, as 1/24000.',
  },
  {
    card: '2024 P1 Q1',
    skill: 'Differentiate a cot of kx, then a multiple of x times the square root of a linear bracket by the product rule.',
    marks: [2, 2],
    route: '2 + 2 - (a) the derivative of cot begun, -cosec^2 kx, then the chain rule\'s k; (b) the product rule with one term right, c(ax + b)^{1/2} or c x times a half times a times (ax + b)^{-1/2}, then both terms, c(ax + b)^{1/2} + (ca/2)x(ax + b)^{-1/2}. The scheme asks for no simplifying, so the answer is the two terms as they stand, as the paper\'s.',
    ranges: 'The paper: cot 3x, and 5x(4x - 7)^{1/2}. (a) k from 2 to 9, always cot: a different function is a different card. (b) c x(ax + b)^{1/2} with c and a from 2 to 6 and b from ±1 to ±9, a and b sharing no factor so the bracket is as plain as 4x - 7, and ca even so the second term\'s number is whole, as 10. The power stays a half. All exact: Paper 1.',
  },
  {
    card: '2024 P1 Q7',
    skill: 'Implicit differentiation of a x^2 y + b x y^2 = c, then the one stationary point with y positive.',
    marks: [3, 3],
    route: '3 + 3 - (a) the product rule on one term, then every term differentiated with the constant going to 0, then dy/dx made the subject, (-2axy - by^2)/(ax^2 + 2bxy); (b) dy/dx set to 0, then the line 2ax + by = 0 from the numerator (y > 0 rules out y = 0), then substituted into the curve to give the point.',
    ranges: 'The paper: x^2 y + 4xy^2 = -32, y > 0, stationary point (-4, 2). Built from the point: x^2 y + b xy^2 = c with b even from ±2 to ±8 (the paper\'s 4) and y0 from 1 to 3, so the line is x = -(b/2)y, whole as x = -2y, and c = -b^2 y0^3/4 is whole and at most 150 in size, as -32. A number in front of x^2 y, or an odd b, puts fractions in the line and the substitution (x = -2y/3), a step the paper does not have. The sign of b is either (the paper\'s positive gives x0 negative); y > 0 always, as the paper, so the point is unique. 20 questions. All exact: Paper 1.',
  },
  {
    card: '2024 P2 Q1',
    skill: 'Differentiate sin kx over c + x^2 by the quotient rule.',
    marks: [2],
    route: 'The quotient rule with the denominator (c + x^2)^2 and one term of the numerator right, k cos kx(c + x^2) or 2x sin kx; then the whole derivative, (k cos kx(c + x^2) - 2x sin kx)/(c + x^2)^2. The scheme asks for no expanding, so the answer stands as the paper\'s.',
    ranges: 'The paper: sin 7x over 1 + x^2. k from 2 to 9, always sin: a different function is a different card. The number in the denominator c from 1 (the paper) to 9: a bigger number, not a step, as the derivative of c + x^2 is still 2x. Nothing before x^2 (a number there changes only 2x, but 1 + x^2 is the paper\'s shape). 72 questions.',
  },
  {
    card: '2024 P2 Q6',
    skill: 'A parametric curve x = a t^2, y = b t ln t: dy/dx, then d^2y/dx^2 by the quotient rule and dx/dt.',
    marks: [3, 3],
    route: '3 + 3 - (a) the product rule on b t ln t with one term right, then dy/dt = b ln t + b, then dy/dx over dx/dt = 2at, simplified to p(ln t + 1)/(st); (b) the quotient rule on (a)\'s answer with one term right, then the whole t-derivative, then divided by dx/dt again and simplified, -(b/4a^2) ln t / t^3. The t-derivative alone is not the second derivative.',
    ranges: 'The paper: x = t^2, y = 4t ln t, t > 0, giving 2(ln t + 1)/t and -ln t/t^3. x = a t^2 with a from 1 to 4 (as 2025 P2 Q7\'s a t^2) and y = b t ln t with b from 2 to 9, so dy/dt = b ln t + b always has a factor to take out, as the paper\'s 4 ln t + 4. Always t ln t: a different function is a different card. 32 questions.',
  },
  {
    card: '2024 P2 Q10',
    skill: 'Related rates: a rod\'s volume V = k pi r^3 grows at a constant rate; dr/dt at a given r.',
    marks: [4],
    route: 'dV/dt = R from the words; the chain rule linking dV/dt, dV/dr and dr/dt; dV/dr = 3k pi r^2; then dr/dt at the radius, exact as a fraction over pi, with its units and "dr/dt =" written.',
    ranges: 'The paper: 12 mm^3 per minute, V = 5 pi r^3, r = 10, dr/dt = 1/(125 pi). k from 2 to 9, the rate R from 2 to 30 and the radius from 2 to 15, so dr/dt = R/(3k pi r^2) is one exact fraction over pi, as the paper\'s. The rod, the units and the wording stay the paper\'s.',
  },
  {
    card: '2023 P1 Q1',
    skill: 'Differentiate a multiple of x times tan kx by the product rule.',
    marks: [2],
    route: 'The product rule with one term right, c tan kx + cx(...) or (...) tan kx + cx times k sec^2 kx; then both terms, c tan kx + ck x sec^2 kx. The product rule gives two terms; one alone earns nothing.',
    ranges: 'The paper: 7x tan 2x, giving 7 tan 2x + 14x sec^2 2x. c from 2 to 9 (the paper\'s 7) and k from 2 to 9 (the paper\'s 2), always tan: a different function is a different card. 64 questions. All exact: Paper 1.',
  },
  {
    card: '2023 P2 Q1',
    skill: 'Differentiate a multiple of an inverse sine of a multiple of x, in the words "the function f is defined by".',
    marks: [2],
    route: 'The inverse sine\'s derivative with the number in front kept, c/sqrt(1 - (kx)^2); then the chain rule\'s k, ck/sqrt(1 - (kx)^2), or with the square worked out. The whole kx is squared under the root.',
    ranges: 'The paper: 2 sin^{-1} 3x, giving 6/sqrt(1 - 9x^2). c from 2 to 9 (the paper\'s 2) and k from 2 to 9 (the paper\'s 3), always sin^{-1}: a different function is a different card. 64 questions. The same question as 2026 P2 Q1 (locked), in this paper\'s words: its own routine, so neither moves the other, and one family label at the port.',
  },
  {
    card: '2023 P2 Q4',
    skill: 'Implicit differentiation with a product term, then the gradient of the tangent at the origin.',
    marks: [3],
    route: 'The product rule on x^2y^2 with one term right, 2xy^2 + ... or ... + 2x^2y dy/dx; then both terms; then the rest of the equation differentiated, p dy/dx and k cos kx, and the gradient at (0, 0), k/p. One term of the product alone loses both product-rule marks.',
    ranges: 'The paper: x^2y^2 - 2y = sin 3x at (0, 0), gradient -3/2. The term in y, py, with p from -6 to 6, never 0 (the paper\'s -2), and sin kx with k from 2 to 7 (the paper\'s 3), so the curve always passes through the origin, as the paper\'s: always sin, since cos 0 is not 0. The product term stays the paper\'s x^2y^2. 72 questions.',
  },
  {
    card: '2023 P2 Q10',
    skill: 'Differentiate x to the power a x^m by logarithmic differentiation, the answer in x.',
    marks: [5],
    route: 'ln y = a x^m ln x; the left side (1/y) dy/dx; the product rule with one term right, then both, am x^{m-1} ln x + a x^m (1/x); then dy/dx = x^{ax^m}(am x^{m-1} ln x + a x^{m-1}), y replaced.',
    ranges: 'The paper: x^{5x^2}, giving x^{5x^2}(10x ln x + 5x). a from 2 to 9 either sign (the paper\'s 5), as the owner kept both signs on 2026 P2 Q5, and m from 2 to 4 (the paper\'s 2): m = 1 is 2026 P2 Q5\'s question, x^{kx}. Always x > 0, as the paper. 48 questions.',
  },
  {
    card: '2023 P2 Q11',
    skill: 'Related rates: a cone\'s volume in terms of the water\'s height by similar triangles, then the rate the height rises from a pumping rate in litres.',
    marks: [1, 5],
    route: '1 + 5 - (a) r in terms of h by similar triangles, substituted into the cone formula, leading to the given V; (b) dV/dh, the chain rule, dV/dt in cm^3 (litres times 1000), dh/dt in terms of h, then its value at the height, exact over pi, with units. Forgetting the litres is the scheme\'s trap.',
    ranges: 'The paper: diameter 180 cm, height 150 cm (radius over height 3/5), V = 3 pi h^3/25, 10 litres a second, h = 125, dh/dt = 16/(9 pi). The height 100, 120, 150, 180 or 200 cm, radius over height one of 1/2, 1/3, 2/3, 3/4, 2/5, 3/5, 4/5 or 5/6 with a whole radius and a diameter from 60 to 240 cm; 2 to 20 litres a second; the height asked a multiple of 5, from two fifths full to 10 cm short of the top, as 125 of 150. dh/dt from 0.1 to 5 cm a second, one exact fraction over pi with top and bottom under 1000, as 16/(9 pi). The figure is drawn to the cone\'s own shape, with the diameter above and the height on the right, as the paper\'s.',
  },
  {
    card: '2022 P1 Q1(a)',
    skill: 'Differentiate a linear expression over x^2 plus a number by the quotient rule, and simplify.',
    marks: [3],
    route: 'The quotient rule with the denominator (x^2 + c)^2 and one term of the numerator right, q(x^2 + c)... or ... - 2x(p + qx); then the whole numerator; then simplified, the brackets multiplied out and like terms collected, (-qx^2 - 2px + qc)/(x^2 + c)^2. The last mark needs the expanding and collecting.',
    ranges: 'The paper: (1 - 3x)/(x^2 + 4), giving (3x^2 - 2x - 12)/(x^2 + 4)^2. The top p + qx in the paper\'s order, constant first, with p from 1 to 6 (the paper\'s 1) and q odd from -7 to 7 (the paper\'s -3), q and p sharing no factor, so the simplified top\'s three coefficients share none, as 3, -2 and -12, and there is one simplest form. The bottom x^2 + c with c from 1 to 9 (the paper\'s 4), which never factorises, so nothing cancels. A positive q is a sign, not a step. All exact: Paper 1.',
  },
  {
    card: '2022 P1 Q1(b)',
    skill: 'Differentiate cosec of a multiple of x.',
    marks: [2],
    route: 'The standard derivative begun, -cosec kx cot kx; then the chain rule\'s factor k, -k cosec kx cot kx. Leaving out the k loses the second mark.',
    ranges: 'The paper: cosec 5x. k from 2 to 9, a whole number as the paper\'s 5, never 1. Always cosec: a different function is a different card. The paper\'s k alone makes 8 questions, below the floor, so a number in front, c from 1 (the paper) to 3, as the owner kept on 2025 P2 Q1\'s inverse cosine: it rides along as a coefficient, not a step. 24 questions.',
  },
  {
    card: '2022 P1 Q4',
    skill: 'Implicit differentiation of y^3 + ay = bxy + c, the gradient at a given y, then show there is no stationary point.',
    marks: [3, 1, 2],
    route: '3 + 1 + 2 - (a) the chain rule on y^3 or the product rule on bxy, one right; then every term, 3y^2 dy/dx + a dy/dx = by + bx dy/dx; then dy/dx = by/(3y^2 + a - bx); (b) x from the curve at the given y, then the gradient; (c) dy/dx = 0 gives y = 0, and y = 0 in the curve\'s equation gives 0 = c, inconsistent. (c) needs the value put back into the curve\'s equation, not only y = 0.',
    ranges: 'The paper: y^3 + 4y = 2xy + 1, at y = -1 (so x = 3), gradient -2. a from 1 to 6 (the paper\'s 4), b from 1 to 4 (the paper\'s 2; a negative b prints "= -3xy - 5", which no paper writes), c from -6 to 6 never 0 (the paper\'s 1, and never 0 or (c) has nothing to show), y from -2 to 2 never 0 (the paper\'s -1). Only the curves where x is whole and not 0 at that y and the gradient is a whole number, not 0, as the paper\'s; listed, 76 of them. A negative c is a sign, not a step. All exact: Paper 1.',
  },
  {
    card: '2022 P2 Q8',
    skill: 'Differentiate x ln x - x, then hence solve a first-order linear equation whose integrating factor needs the integral of ln x.',
    marks: [2, 4],
    route: '2 + 4 - (a) the product rule with one term right, then ln x; (b) the integrating factor as e to the integral of k ln x; by (a), e^{kx ln x - kx}; the equation as an integral equation; the right side simplified to a multiple of e^{-kx}, integrated, and y made the subject. Separating the variables earns nothing in (b).',
    ranges: 'The paper: (a) x ln x - x; (b) dy/dx + y ln x = x^{-x}, y = (-e^{-x} + c)/(x^x e^{-x}). (a) is the paper\'s on every draw. (b): a number k in front of y ln x, from 1 (the paper) to 4, and the right side jk x^{-kx}, j from 1 (the paper) to 6 (the owner, "Widen j to 6", 2026-10-01), so the integrating factor x^{kx}e^{-kx} cancels the x^{-kx}, as the paper\'s cancels x^{-x}, and the answer\'s coefficient is a whole -j, as the paper\'s -1. The paper\'s k = 1 and j = 1 alone is one question: a number in front is a bigger number, not a step (the owner kept them on 2025 P2). 24 questions.',
  },
  {
    card: '2022 P2 Q11',
    skill: 'From x and dy/dx given in terms of t, find dy/dt and integrate for y in terms of t.',
    marks: [4],
    route: 'dx/dt for x = tan^{-1} kt, k/(1 + (kt)^2); dy/dx = (dy/dt)/(dx/dt) set equal to the given expression; dy/dt simplified to mkt; integrated, the constant from the condition. Integrating the given dy/dx with respect to t earns nothing.',
    ranges: 'The paper: x = tan^{-1} 2t, dy/dx = 6t(1 + 4t^2), y = 5 when t = 1, y = 6t^2 - 1. k from 2 to 5 (the paper\'s 2), m from 1 to 9 (the paper\'s 6) with mk even, so y\'s coefficient mk/2 is whole, as 6, and mk at most 30; t from 1 to 3 (the paper\'s 1); the constant from ±1 to ±9 (the paper\'s -1), so the value of y is whole, never 0 and within 60. Always tan^{-1} and dy/dx = m t(1 + k^2 t^2), so dy/dt is a multiple of t, as the paper\'s 12t.',
  },
  {
    card: '2022 P2 Q13',
    skill: 'A spotlight turning at a steady rate: its angular speed, the speed along a fence by the chain rule, 1 + tan^2 = sec^2, then the speed at a given distance.',
    marks: [1, 4, 1, 3],
    route: '1 + 4 + 1 + 3 - (a)(i) 2π over the period; (a)(ii) dx/dt = dx/dθ × dθ/dt, x = d tan θ from the triangle, dx/dθ = d sec^2 θ, then substituted and simplified; (b) tan θ as sin θ/cos θ, over one denominator, to sec^2 θ; (c) tan θ = s/d, sec^2 θ = 1 + (s/d)^2, then substituted, exactly, with units.',
    ranges: 'The paper: 10 m from the fence, one turn every 12 s, π/6, (5π/3) sec^2 θ, and 25π/12 m/s at 5 m from G. The distance d from 5 to 20 m, the period one of 6, 8, 9, 10, 12 (the paper), 15, 16, 18, 20, 24, 30 s, and the distance from G from 1 to d m (the paper\'s 5 of 10). Every answer is an exact multiple of π, as the paper\'s. The figure is drawn as the paper\'s, not to scale: only its d m label changes. (b) is the paper\'s on every draw.',
  },
  {
    card: '2021 P1 Q1(a)',
    skill: 'Differentiate a power of x times an exponential by the product rule.',
    marks: [2],
    route: 'The product rule begun, one term right: nx^{n-1}(...) + ... or ... + ke^{kx}(...); then the whole derivative, nx^{n-1}e^{kx} + kx^ne^{kx}. The chain rule\'s k on e^{kx} is the second mark.',
    ranges: 'The paper: x^3e^{5x}, giving 3x^2e^{5x} + 5x^3e^{5x}. The power n from 2 to 4 (the paper\'s 3) and k from 2 to 6 either sign (the paper\'s 5), never ±1, so the chain rule always brings a number out. Always x^n times e^{kx} with no number in front, as the paper\'s. A negative k is a sign, not a step. 30 questions. All exact: Paper 1.',
  },
  {
    card: '2021 P1 Q1(b)',
    skill: 'Differentiate tan x over a power of x plus a number by the quotient rule.',
    marks: [2],
    route: 'The quotient rule with the denominator (x^n + c)^2 and one term of the numerator right, (x^n + c)sec^2 x - ... or ... - nx^{n-1}tan x; then the whole numerator. The scheme leaves the answer unsimplified, and so does the card.',
    ranges: 'The paper: tan x/(x^6 + 1). The power n from 2 to 8 (the paper\'s 6) and c from 1 to 5 (the paper\'s 1), so the bottom never factorises and nothing cancels. Always tan x on top, with no number inside: a coefficient inside the tan is a chain rule, a step the paper does not have. 35 questions. All exact: Paper 1.',
  },
  {
    card: '2021 P1 Q6',
    skill: 'From a velocity in t, find the displacement by integrating with zero displacement at t = 0, then the acceleration at t = 0.',
    marks: [2, 2],
    route: '2 + 2 - (a) the integration begun, m t^3 ... or ... - (B/(-k))e^{-kt}; then the constant from zero displacement at t = 0, the expression m t^3 + (B/k)e^{-kt} - B/k; (b) dv/dt, 6m t + Bke^{-kt}; then its value at t = 0, Bk, with units. e^0 = 1 is the scheme\'s trap.',
    ranges: 'The paper: v = 3t^2 - e^{-2t}, s = t^3 + (1/2)e^{-2t} - 1/2, a = 2 ms^{-2}. The t^2 coefficient a multiple of 3 from 3 to 12 (the paper\'s 3), so the cube\'s coefficient is whole, as the paper\'s 1; e^{-kt} with k from 2 to 5 (the paper\'s 2), always decaying and always subtracted, as the paper\'s; a number B from 1 (the paper) to 3 in front of it, a bigger number, not a step. Always t = 0, where e^0 = 1 keeps (b) exact. 48 questions. All exact: Paper 1.',
  },
  {
    card: '2021 P2 Q1',
    skill: 'Differentiate c sec kx and find the exact value of the derivative at a given multiple of pi.',
    marks: [2],
    route: 'The derivative with the chain rule, c sec kx tan kx × k; then evaluated exactly at the given x, where kx is pi/6, pi/4 or pi/3, with the exact values of sec and tan.',
    ranges: 'The paper: 3 sec 2x at x = pi/8, giving 6√2. c from 1 to 5 (the paper\'s 3), k from 2 to 6 (the paper\'s 2), and x = pi/(km) so that kx is pi/6, pi/4 (the paper\'s) or pi/3, the three angles whose sec and tan are exact: the answer is ck√2, 2ck√3 or 2ck/3. Always sec: a different function is a different card. 75 questions.',
  },
  {
    card: '2021 P2 Q4',
    skill: 'Differentiate an inverse sine and an inverse tangent given parametrically, then the tangent at t = 0.',
    marks: [3, 2],
    route: '3 + 2 - (a) the derivative of inverse sine begun, 1/√(1 - (kt)^2), then the chain rule\'s k, then dy/dt = b/(1 + t^2); (b) the point (0, 0) or dy/dx = b/(ak) at t = 0, dy/dt over dx/dt, then the tangent y = (b/(ak))x.',
    ranges: 'The paper: x = sin^{-1} 2t, y = tan^{-1} t, tangent y = x/2. k from 2 to 5 inside the inverse sine (the paper\'s 2); a number in front of each, a for x and b for y, from 1 (the paper) to 3, since the paper\'s k alone makes 4 questions, below the floor: a number in front is a bigger number, not a step. No number inside the inverse tangent, which would add a chain rule the paper does not have. Always t = 0, where the point is the origin, as the paper\'s. 36 questions.',
  },
  {
    card: '2021 P2 Q8',
    skill: 'Implicit differentiation of x^2y^3 + e^{ky} = N, then show there is only one stationary point.',
    marks: [4, 3],
    route: '4 + 3 - (a) the product rule on x^2y^3 with one term right, then both terms, then the e^{ky} term and 0, then dy/dx = -2xy^3/(3x^2y^2 + ke^{ky}); (b) dy/dx = 0, then x = 0 and y = 0, then x = 0 gives y = (1/k) ln N while y = 0 gives 1 = N, no solution.',
    ranges: 'The paper: x^2y^3 + e^{2y} = 5, the point (0, (1/2) ln 5). k from 1 to 4 (the paper\'s 2) and N from 2 to 10 (the paper\'s 5), never 1, so y = 0 always fails; never a perfect k-th power, so (1/k) ln N has one simplest form (1/2 ln 4 is ln 2). Always x^2y^3, the paper\'s powers. 30 questions.',
  },
  {
    card: '2019 Q1(a)',
    skill: 'Differentiate a power of x times cot kx by the product rule.',
    marks: [2],
    route: 'The product rule with one term right, n x^{n-1} cot kx or -k x^n cosec^2 kx; then both, the chain rule bringing out the k. The question asks for no simplifying, so the second mark is for the two terms as they stand.',
    ranges: 'The paper: x^6 cot 5x. n from 2 to 8 (the paper\'s 6) and k from 2 to 7 (the paper\'s 5), never 1, so the chain rule always brings a number out. Always cot, and nothing in front, as the paper. 42 questions.',
  },
  {
    card: '2019 Q1(b)',
    skill: 'Differentiate (ax^n + b)/(x^n + c) by the quotient rule, and simplify.',
    marks: [3],
    route: 'The quotient rule with the denominator and one term of the numerator right; then the whole numerator, na x^{n-1}(x^n + c) - (ax^n + b)(n x^{n-1}); then simplified, the x^n terms cancelling to n(ac - b)x^{n-1} over (x^n + c)^2. The last mark needs the brackets multiplied out and collected.',
    ranges: 'The paper: (2x^3 + 1)/(x^3 - 4), answer -27x^2/(x^3 - 4)^2. The same power top and bottom, n from 2 to 4 (the paper\'s 3), so the numerator collects to one term, as the paper\'s does; a from 2 to 5 (the paper\'s 2), b from -9 to 9 and c from -6 to 6, never 0 (the paper\'s 1 and -4); never ac = b, which would make y a constant. The bottom has no number in front of x^n, as the paper\'s.',
  },
  {
    card: '2019 Q1(c)',
    skill: 'Differentiate an inverse cosine of a multiple of x, and evaluate it at an exact value.',
    marks: [3],
    route: 'The derivative of the inverse cosine begun, -1/√(1 - (kx)^2); then the chain rule\'s factor k; then x substituted and evaluated exactly.',
    ranges: 'The paper: cos^{-1} 2x at x = √3/4, where 2x is √3/2 and the answer is -4. k from 2 to 6 (the paper\'s 2), and x where kx is one of the three exact values whose root comes out: √3/2 (the paper\'s, answer -2k), 1/√2 (x = √2/(2k), answer -k√2) or 1/2 (x = 1/(2k), answer -2k/√3, rationalised). The paper\'s value alone makes 5 questions, below the floor; the three make 15. Always the inverse cosine, nothing in front.',
  },
  {
    card: '2019 Q5',
    skill: 'A parametric curve x = ln(at + b), y = ct^2: dy/dx, then d^2y/dx^2 from its t-derivative and dx/dt.',
    marks: [2, 2],
    route: '2 + 2 - (a) dx/dt = a/(at + b), then dy/dx = dy/dt ÷ dx/dt, simplified to 2ct^2 + (2cb/a)t; (b) dy/dx differentiated with respect to t and the strategy shown, (4ct + 2cb/a) × …, then d^2y/dx^2 = that ÷ dx/dt, (2c/a^2)(at + b)(2at + b). Dividing by dx/dt a second time is the scheme\'s point: the t-derivative alone earns only its mark.',
    ranges: 'The paper: x = ln(2t + 7), y = t^2, answers 2t^2 + 7t and (1/2)(2t + 7)(4t + 7). a is 1 or 2 (the paper\'s 2), so dy/dx has whole coefficients, as the paper\'s; b from 1 to 9 (the paper\'s 7), sharing no factor with a; a number in front of t^2, c from 1 (the paper) to 3, since a and b alone make 14 and a number in front is a bigger number, not a step. 42 questions.',
  },
  {
    card: '2019 Q6',
    skill: 'Related rates: a spherical balloon deflating at a constant rate; dr/dt at a given radius.',
    marks: [3],
    route: 'dV/dr = 4πr^2 and the chain rule linking dV/dt, dV/dr and dr/dt; then the rate substituted as negative with r, -R = 4π r^2 dr/dt; then dr/dt = -R/(4πr^2) exactly, with units. A positive rate loses the last mark: the balloon is shrinking.',
    ranges: 'The paper: 60 cm^3 s^{-1} at r = 3, answer -5/(3π) cm s^{-1}. R a multiple of 10 from 10 to 120 (the paper\'s 60) and r from 2 to 8 (the paper\'s 3), the answer an exact fraction over π, as the paper\'s. Always deflating, as the paper. A near relation of 2024 P2 Q10 (locked), the rod with V = kπr^3: its own routine. 84 questions.',
  },
  {
    card: '2019 Q10',
    skill: 'Implicit differentiation of ax^2 + y^2 = bxy + N, then the two vertical tangents x = k.',
    marks: [3, 2],
    route: '3 + 2 - (a) the chain rule on y^2 or the product rule on bxy, then every term, then dy/dx = (by - 2ax)/(2y - bx); (b) a vertical tangent, so the denominator is zero, 2y - bx = 0; then y = bx/2 substituted into the curve, x^2 = K^2 and k = ±K.',
    ranges: 'The paper: x^2 + y^2 = xy + 12, k = ±4. A number in front of x^2, a from 1 to 3, and of xy, b from 1 to b^2 < 4a, so the points are real (the paper\'s a = b = 1, which alone makes 3 questions); N chosen so x^2 is a whole square K^2, K from 2 to 6 (the paper\'s 4), N at most 100 (the paper\'s 12). A number in front is a bigger number, not a step. y^2 alone, as the paper. 22 questions.',
  },
  {
    card: '2018 Q1(a)',
    skill: 'Differentiate a sin^{-1} kx with the chain rule.',
    marks: [2],
    route: 'The standard derivative of sin^{-1} started, a/√(1 - (kx)^2) × …; then the chain rule completing it, ak/√(1 - k^2x^2). The answer is left as the paper leaves it.',
    ranges: 'The paper: sin^{-1} 3x, answer 3/√(1 - 9x^2). k from 2 to 9 (the paper\'s 3), never 1, so the chain rule always brings a number out; k alone makes 8, so a number in front, a from 1 (the paper) to 4, as the owner allowed on 2021 P2 Q10 ("Do number in front up to 4"). Always sin^{-1}, as the paper. 32 questions.',
  },
  {
    card: '2018 Q1(b)',
    skill: 'Differentiate e^{ax}/(bx + c) by the quotient rule.',
    marks: [2],
    route: 'The quotient rule with the denominator and one term of the numerator right, a(bx + c)e^{ax} … or … - be^{ax} over (bx + c)^2; then the whole numerator. The paper asks for no simplifying, and its answer is unsimplified.',
    ranges: 'The paper: e^{5x}/(7x + 1). a from 2 to 6 (the paper\'s 5), never 1, so the chain rule on e^{ax} always brings a number out; b from 2 to 9 (the paper\'s 7) and c from 1 to 9 (the paper\'s 1), both positive and sharing no factor, as the paper\'s (never 4x + 2). Over 200 questions.',
  },
  {
    card: '2018 Q1(c)',
    skill: 'Implicit differentiation of y cos x + by^2 = kx.',
    marks: [4],
    route: 'The product rule on y cos x with one term right, dy/dx cos x or -y sin x; then both; then the remaining terms, + 2by dy/dx = k; then dy/dx = (k + y sin x)/(cos x + 2by). One product term alone loses both product-rule marks.',
    ranges: 'The paper: y cos x + y^2 = 6x, answer (6 + y sin x)/(cos x + 2y). k from 2 to 12 (the paper\'s 6) and a number in front of y^2, b from 1 (the paper) to 3: k alone makes 11. Always y cos x, as the paper: y sin x would be a second question. 33 questions.',
  },
  {
    card: '2018 Q6',
    skill: 'A parametric curve x = t^2 + c, y = ln(at + b): the tangent at a given t.',
    marks: [5],
    route: 'dy/dt = a/(at + b); dx/dt = 2t and dy/dx = (dy/dt)/(dx/dt); the gradient at t₀; the point (x₀, 0); the tangent y = mx + k, rearranged. Leaving it as y - 0 = … loses the last mark.',
    ranges: 'The paper: x = t^2 + 1, y = ln(3t + 2) at t = -1/3, answer y = -9/2 x + 5. t₀ = (1 - b)/a, so at + b = 1 and y = ln 1 = 0 at the point, as the paper\'s; b - 1 from 1 to 8 (the paper\'s 1) sharing no factor with a, so t₀ is a fraction, as the paper\'s, and b sharing none with a either, so the log is never ln(2t + 4); that leaves a = 3 (the paper), 5 or 7 (15 pairs). c from 1 (the paper) to 5. The gradient and the intercept are fractions or whole, as the paper\'s are. 75 questions.',
  },
  {
    card: '2018 Q13',
    skill: 'Related rates: a rhombus of side L whose horizontal diagonal x shrinks; h = √(4L^2 - x^2), then dh/dt at x = X.',
    marks: [1, 5],
    route: '1 + 5 - (a) Pythagoras on a quarter of the rhombus, (x/2)^2 + (h/2)^2 = L^2, so h = √(4L^2 - x^2); (b) dx/dt = -R (decreasing); dh/dx = -2x · ½(4L^2 - x^2)^{-1/2}; dh/dt = dh/dx · dx/dt; dh/dt = Rx/√(4L^2 - x^2); evaluated at x = X, with units, or the last mark goes.',
    ranges: 'The paper: side 25 cm, 0.3 cm per second, x = 30, answer 9/40 cm s^{-1}. (X/2, h/2, L) a Pythagorean triple with L from 10 to 30 cm (the paper\'s 15, 20, 25), either half-diagonal across, so h is whole at x = X, as the paper\'s 40; R from 0.1 to 0.5 cm per second (the paper\'s 0.3). The answer exact, with its decimal, as the paper\'s. The figure is the paper\'s rhombus, not to scale, as the paper\'s; the paper\'s drawing of the device is not drawn. 100 questions.',
  },
  {
    card: '2017 Q3',
    skill: 'Differentiate e^u/u with u = x^n + c by the quotient rule, and simplify.',
    marks: [3],
    route: 'The quotient rule with one term of the numerator right, u\'e^u(u) - …, the top\'s derivative by the chain rule; the whole derivative over u^2; then the common factor u\'e^u taken out and the numerator simplified to u - 1, as the paper\'s (x^2 - 1) - 1 = x^2 - 2. Leaving (u) - 1 unsimplified loses the last mark.',
    ranges: 'The paper: e^{x^2 - 1}/(x^2 - 1), answer 2xe^{x^2 - 1}(x^2 - 2)/(x^2 - 1)^2. u = x^n + c, the same u in the power and underneath, as the paper; n 2 (the paper) or 3, c from -9 to 9 (the paper\'s -1), never 0 and never 1, where u - 1 would be x^n alone and the answer would simplify further than the paper\'s. 34 questions.',
  },
  {
    card: '2017 Q11',
    skill: 'Differentiate x^{ax^n + b} by logarithmic differentiation.',
    marks: [5],
    route: 'Logs of both sides with the power brought down, ln y = (ax^n + b) ln x; the left side, (1/y) dy/dx; the product rule on the right with one term right; both terms; then dy/dx = x^{ax^n + b}(anx^{n-1} ln x + (ax^n + b)/x), in terms of x. Without the product rule the middle marks go.',
    ranges: 'The paper: x^{2x^3 + 1}, answer x^{2x^3 + 1}(6x^2 ln x + (2x^3 + 1)/x). The power ax^n + b: a from 1 to 4 (the paper\'s 2), n from 2 to 4 (the paper\'s 3), b from -6 to 6, never 0 (the paper\'s 1), a and b sharing no factor, as 2 and 1 (a paper never prints x^{2x^3 + 4}). Always x to a power of x, as the paper. 96 questions.',
  },
  {
    card: '2017 Q18',
    skill: 'The speed of a particle on the spiral x = kt cos t, y = kt sin t, then at a point A where it crosses an axis, read from the diagram.',
    marks: [5, 2],
    route: '5 + 2 - (a) the product rule on x or y with one term right; dx/dt = k(cos t - t sin t); dy/dt = k(sin t + t cos t); the speed formula, the root of the sum of the squared derivatives; expanded and simplified to k√(1 + t^2); (b) the axis condition (y = 0, t sin t = 0, or x = 0) with its solutions; the crossing A is, from the diagram, and the speed there.',
    ranges: 'The paper: x = t cos t, y = t sin t, A the second crossing of the negative x-axis, t = 3π, speed √(1 + 9π^2). A number in front, k from 1 (the paper) to 4, the same on both, so the speed is k√(1 + t^2); A at any of the six axis crossings from t = π to 7π/2 (the paper\'s 3π), each named on the diagram by its dot. The spiral is drawn to just past 4π, as the paper\'s. The answer exact, as the paper\'s. 24 questions.',
  },
  {
    card: '2016 Q1(a)',
    skill: 'Differentiate ax tan^{-1} kx by the product rule.',
    marks: [3],
    route: 'The product rule set up, (…) tan^{-1} kx + ax(…); one term right, a tan^{-1} kx or ax · 1/(1 + (kx)^2) · k; then both, a tan^{-1} kx + akx/(1 + k^2x^2).',
    ranges: 'The paper: x tan^{-1} 2x, answer tan^{-1} 2x + 2x/(1 + 4x^2). k from 2 to 9 (the paper\'s 2), never 1, so the chain rule always brings a number out; k alone makes 8, so a number in front, a from 1 (the paper) to 4, as the owner allowed on 2021 P2 Q10 ("Do number in front up to 4") and kept on 2018 Q1(a). Always x times an inverse tangent, as the paper. 32 questions.',
  },
  {
    card: '2016 Q1(b)',
    skill: 'Differentiate (a - bx^2)/(c + dx^2) by the quotient rule, and simplify.',
    marks: [3],
    route: 'The quotient rule over (c + dx^2)^2 with one term of the numerator right, (-2bx)(c + dx^2) - …; the whole numerator, … - (a - bx^2) · 2dx; then multiplied out, the x^3 terms cancelling, to -2(bc + ad)x/(c + dx^2)^2. An error after a correct answer loses the last mark.',
    ranges: 'The paper: (1 - x^2)/(1 + 4x^2), answer -10x/(1 + 4x^2)^2. a from 1 to 4 and b 1 or 2 (the paper\'s 1 and 1), c from 1 to 3 and d from 2 to 5 (the paper\'s 1 and 4), the top and the bottom each sharing no factor, as the paper\'s (never 2 - 4x^2). Always a minus on top and a plus underneath, as the paper, so the x^3 terms cancel and the answer is a multiple of x over the square. 54 questions.',
  },
  {
    card: '2016 Q1(c)',
    skill: 'A parametric curve x = at, y = b - c cos t: dy/dx in terms of t.',
    marks: [2],
    route: 'Both derivatives, dx/dt = a and dy/dt = c sin t; then dy/dx = (dy/dt)/(dx/dt) = (c/a) sin t.',
    ranges: 'The paper: x = 6t, y = 1 - cos t, answer (1/6) sin t. a from 2 to 9 (the paper\'s 6), b from 1 (the paper) to 4, and a number in front of the cosine, c from 1 (the paper) to 3, less than a, so the answer is a fraction of sin t, as the paper\'s. Always a cosine in y, as the paper: a sine would give a cosine, another answer. 84 questions.',
  },
  {
    card: '2016 Q11',
    skill: 'Related rates: a cube whose height grows at a constant rate; dV/dt at a given height.',
    marks: [4],
    route: 'dh/dt = R; the chain rule dV/dt = dV/dh · dh/dt with V = h^3; dV/dh = 3h^2; then 3H^2 × R with units, cm^3 s^{-1}.',
    ranges: 'The paper: 5 cm s^{-1} at a height of 3 cm, answer 135 cm^3 s^{-1}. R and H whole, from 2 to 9 (the paper\'s 5 and 3). Always a cube, as the paper. 64 questions.',
  },
];
