/**
 * Advanced Higher, Integration: what each card is.
 * The routines are in `../routines/integration.ts`, under the same labels.
 */
import type { CardMeta } from '../types';

export const INTEGRATION: readonly CardMeta[] = [
  {
    card: '2021 P2 Q3',
    skill: 'Integrate a linear expression times $\\cos kx$ by parts.',
    marks: [3],
    route: 'Integration by parts with u the bracket, begun: (1/k)(ax + b) sin kx - ...; then the integral left, ∫ (a/k) sin kx dx; then integrated, + (a/k^2) cos kx + c, with the constant.',
    ranges: 'The paper: (2x + 3) cos 4x, giving (1/4)(2x + 3) sin 4x + (1/8) cos 4x + c. a from 1 to 5 (the paper\'s 2), b from -9 to 9 never 0 (the paper\'s 3), the bracket sharing no factor, so it is not taken out first; k from 2 to 6 (the paper\'s 4). Always cos: a different function is a different card.',
  },
  {
    card: '2021 P1 Q3',
    skill: 'Integrate a number times $\\cos\\theta\\sin^{n}\\theta$ with the substitution $u = \\sin\\theta$, the answer in $\\theta.$',
    marks: [2],
    route: 'The integral rewritten in u, a u^n du; then integrated and written back in θ, a/(n + 1) sin^{n+1} θ, with the constant of integration, which the second mark needs.',
    ranges: 'The paper: cos θ sin^3 θ, giving (1/4)sin^4 θ + c. The power n from 2 to 7 (the paper\'s 3), and a number a from 1 (the paper) to 5 in front, a bigger number, not a step (the owner kept a number in front on 2022 P1 Q1(b)), so the answer\'s fraction a/(n + 1) is in lowest terms, sometimes whole. Always u = sin θ with cos θ the derivative beside it: cos θ with a power, u = cos θ, puts a minus in, a different card. 30 questions. All exact: Paper 1.',
  },
  {
    card: '2021 P1 Q5',
    skill: 'The volume when $y = c\\sqrt{x}$ between two values of $x$ is rotated about the $x$-axis, exactly.',
    marks: [2],
    route: 'The volume integral in the right form, π∫ y^2 dx with the limits; then y^2 = c^2 x integrated and evaluated, exactly, a multiple of π.',
    ranges: 'The paper: y = 2√x from x = 3 to 5, volume 32π. c from 1 to 4 (the paper\'s 2), the limits whole from 1 to 7 with the lower below the upper (the paper\'s 3 and 5). Only the solids whose volume c^2(b^2 - a^2)π/2 is a whole multiple of π, as the paper\'s 32π, and with no product bigger than the paper\'s biggest, 2 × 25 = 50 at the top limit (the owner on 2023 P1: "biggest should be no larger than paper"); listed, 21 solids. All exact: Paper 1.',
  },
  {
    card: '2022 P2 Q2',
    skill: 'A definite integral whose top is a multiple of the bottom\'s derivative, as an exact log.',
    marks: [2],
    route: 'Integrated as a multiple of ln(ax + 1); the coefficient right, the limits put in and ln 1 = 0 used, m ln(au + 1).',
    ranges: 'The paper: the integral from 0 to 3 of 4/(2x + 1), 2 ln 7. The bottom ax + 1 with a from 2 to 5 (the paper\'s 2), the top m times a with m from 2 to 4 (the paper\'s 4 = 2 x 2), so the answer is a whole number times a log, as 2 ln 7; the lower limit 0, so ln 1 comes out as the paper\'s does, and the upper limit from 1 to 6. au + 1 is never a power (4, 8, 9, 16, 25, 27): m ln 9 would simplify to 2m ln 3, a step the paper does not have.',
  },
  {
    card: '2022 P2 Q4',
    skill: 'Integrate a linear factor times the square root of another by parts.',
    marks: [3],
    route: 'u = x + p and dv/dx the bracket to the power 1/2: the uv part, (2/3a)(x + p)(ax + b)^{3/2}; the integral left, of (2/3a)(ax + b)^{3/2}; integrated by the chain rule in reverse, with + c. Differentiating the bracket instead gets stuck.',
    ranges: 'The paper: (x + 2)(2x + 7)^{1/2}, giving (1/3)(x + 2)(2x + 7)^{3/2} - (1/15)(2x + 7)^{5/2} + c. a from 2 to 4 (the paper\'s 2; a = 1 leaves no chain rule in reverse), p from 1 to 6 and b from 1 to 9 (the paper\'s 2 and 7), all positive as the paper\'s; ax + b in lowest terms, and never a multiple of x + p. Always the power 1/2.',
  },
  {
    card: '2022 P1 Q7',
    skill: 'A definite integral by the substitution $u = y^{2} + 1$, the area of a symmetrical cross-section from it, a fraction split, then a volume of revolution about the $y$-axis with an inverse tangent.',
    marks: [4, 1, 1, 4],
    route: '4 + 1 + 1 + 4 - (a) du = 2y dy; the new limits, 1 to m^2 + 1; the integral in u, (k/2) times the integral of 1/sqrt(u); integrated and evaluated, k(sqrt(m^2 + 1) - 1); (b) twice (a), by the symmetry; (c) 1 - 1/(y^2 + 1); (d) pi times the integral of x^2 dy with its limits; k^2 pi times the integral of (c); the inverse tangent; then k^2 pi(m - tan^{-1} m). Rotating about the y-axis is pi x^2 with respect to y.',
    ranges: 'The paper: x = 4y/sqrt(y^2 + 1), 0 <= y <= 5, giving 4(sqrt 26 - 1), 8(sqrt 26 - 1), 1 - 1/(y^2 + 1) and 16 pi(5 - tan^{-1} 5). k from 2 to 6 (the paper\'s 4; an odd k puts a half before the integral in u, 3/2 in place of the paper\'s 2, and every answer stays whole); m from 2 to 9 but not 7, whose sqrt 50 simplifies to 5 sqrt 2, a step the paper does not have, and not 1, whose tan^{-1} is pi/4. Always y^2 + 1: y^2 + a^2 would put 1/a inside and outside the inverse tangent, a step the paper does not have. (c) is the paper\'s on every draw. 35 questions. The figure is drawn as the paper\'s, the height m marked and the curve scaled to a fixed width. All exact: Paper 1.',
  },
  {
    card: '2026 P1 Q6',
    skill: 'Integrate by a given substitution, then use it for an exact volume of revolution.',
    marks: [3, 4],
    route: '3 + 4 - (a) differentiate the substitution; rewrite the integral in u and expand; integrate and substitute back; (b) the volume integral with its limits and dx; y squared to match (a)\'s integrand; (a)\'s result with the limits; evaluated exactly. The limits and the dx must be written or the fourth mark goes.',
    ranges: 'The paper: (a) the integral of x(x - 1)^4 with u = x - 1; (b) y = 2√x(x - 1)^2 from x = 0 to 1, volume 2π/15. The card: x(x - k)^n with u = x - k, and y = c√x(x - k)^{n/2}, so that y² = c²x(x - k)^n is c² times (a)\'s integrand, as the paper arranges; limits 0 to k, where the curve meets the axis, as the paper\'s. n is even, so y is defined on [0, k]: the paper\'s 4 in two draws of three (k 1 or 2), and 6 in the third (k 1 only, V = c²π/56), since the paper\'s n alone makes too few questions; the owner chose the power up over the power down, and no coefficient inside the bracket, which would add a step ("Don\'t make it slightly harder", 2026-09-29). k is kept to a non-calculator size (3^6 = 729 is not). c from 1 to 5. 15 questions. The volume is c²k^{n+2}π/((n + 1)(n + 2)), exact: Paper 1.',
  },
  {
    card: '2026 P2 Q11',
    skill: 'Integrate $\\frac{2x + q}{x^{2} + a^{2}}$ by splitting it into a logarithm and an inverse tangent.',
    marks: [4],
    route: 'The integrand split into two fractions over x^2 + a^2; the first integrated as a log (its top is the bottom\'s derivative); the second begun as an inverse tangent of x/a; both coefficients right and the constant added.',
    ranges: 'The paper: (2x + 4)/(x^2 + 4), giving ln(x^2 + 4) + 2 tan^{-1}(x/2). The top keeps 2x, the bottom\'s derivative, as the paper\'s ladder says; a from 2 to 6 and q = ma with m from 1 to 4, so the inverse tangent\'s coefficient is whole, as the paper\'s 2 is. a = 1 is left out: tan^{-1} x has no x/a to find.',
  },
  {
    card: '2025 P1 Q5',
    skill: 'Integrate a number over 1 plus a square of $kx$, as an inverse tangent.',
    marks: [2],
    route: 'Start the integration as an inverse tangent of kx; then the coefficient right for the kx inside, and the constant. A logarithm earns nothing.',
    ranges: 'The paper: 1/(1 + 4x^2), giving (1/2) tan^{-1} 2x + c. k from 2 to 10, so 1 + k^2 x^2 is 1 plus a square, as 4x^2 is (2x)^2. The paper\'s numerator 1 alone makes 9 questions, below the floor, so the numerator is 1, 2 or 3, never a multiple of k, so the coefficient a/k is a fraction as the paper\'s 1/2 is: a number on the top is a coefficient, not a step. All exact: Paper 1.',
  },
  {
    card: '2025 P2 Q16',
    skill: 'Integrate an exponential times a sine by parts twice, the integral reappearing.',
    marks: [5],
    route: 'The first application begun (u = e^{px}, the sine integrated), then completed; the second application begun with the same choice, then carried until the original integral reappears; then collected and solved, with the constant. Swapping the choice in the second application undoes the first.',
    ranges: 'The paper: e^{2x} sin 5x, giving (2/29)e^{2x} sin 5x - (5/29)e^{2x} cos 5x + c. e^{px} sin qx with p from 1 to 5 and q from 2 to 7, p not q. Always the sine, as the paper\'s. 26 questions.',
  },
  {
    card: '2025 P2 Q11',
    skill: 'Integrate $xe^{-kx^{2}}$ by substitution, then use it for an exact volume of revolution.',
    marks: [2, 3],
    route: '2 + 3 - (a) du/dx from the substitution; the integral in u and back in x, with the constant; (b) the volume integral with its limits (stated or implied); y^2 simplified to a multiple of (a)\'s integrand; integrated with the limits and evaluated exactly. The limits must be written or that mark goes.',
    ranges: 'The paper: (a) x e^{-2x^2} with u = 2x^2; (b) y = 4 sqrt(x)/e^{x^2} from 0 to 1, volume 4 pi (1 - e^{-2}). y = c sqrt(x)/e^{m x^2} with c from 2 to 7 (the paper\'s 4) and m from 1 (the paper) to 3, so y^2 = c^2 x e^{-2m x^2} is c^2 times (a)\'s integrand, as the paper arranges; the limits stay 0 to 1, as the figure marks them. The volume is (c^2/4m) pi (1 - e^{-2m}), exact. The figure is drawn from the curve: axes, 0 and 1, the curve and a dashed line at x = 1, as the paper\'s, with no y scale, so only m changes its shape. 18 questions.',
  },
  {
    card: '2024 P1 Q8',
    skill: 'Evaluate a definite integral of a root of $\\tan kx$ over $\\cos^{2} kx$ by the substitution $u = \\tan kx.$',
    marks: [4],
    route: 'du = k sec^2 kx dx; the new limits 0 and 1 with the integral begun in u; the integrand in u alone, (c/k) sqrt(u); then integrated and evaluated, 2c/(3k). Keeping the x limits loses the second mark.',
    ranges: 'The paper: the integral of sqrt(tan 2x)/cos^2 2x from 0 to pi/8, answer 1/3. k from 2 to 6 (the paper\'s 2; never 1, which drops the 1/k the third mark is for), the upper limit pi/(4k), so u runs from 0 to 1 and every value is exact, as the paper\'s; a whole number c from 1 (the paper) to 5 in front of the root. Always the square root. The answer 2c/(3k), in lowest terms. 25 questions.',
  },
  {
    card: '2024 P2 Q8',
    skill: 'A volume of revolution that integrates to an inverse tangent, set equal to a given volume to find the upper limit.',
    marks: [5],
    route: 'The volume integral of pi y^2 with its limits 0 and a and dx; y squared and substituted, pi k^2/(1 + x^2); integrated, tan^{-1} x; the limits in and set equal to the volume, tan^{-1} a = pi/n; then a. The integral needs its limits and dx written.',
    ranges: 'The paper: y = 1/sqrt(1 + x^2), volume pi^2/3, a = sqrt(3). The numerator k from 1 (the paper) to 6, a number, as the owner kept a numerator of 2 or 3 on 2025 P1 Q5: y^2 = k^2/(1 + x^2) is the same standard integral. The volume k^2 pi times pi/3 (the paper), pi/4 or pi/6, so a is sqrt(3), 1 or 1/sqrt(3), each exact, as the paper\'s. Always 1 + x^2 underneath: a number before x^2 puts a coefficient in the inverse tangent, a step the paper does not have. 18 questions.',
  },
  {
    card: '2023 P1 Q4',
    skill: 'Integrate a power of $x$ times $\\ln x$ by parts.',
    marks: [3],
    route: 'u = ln x and the power integrated, giving the "uv -" part, (a/m)x^m ln x - ...; ln x differentiated, giving the integral left, (a/m) times the integral of x^m times 1/x; then integrated, with the constant. Integrating ln x instead does not work.',
    ranges: 'The paper: x^4 ln x, giving (1/5)x^5 ln x - x^5/25 + c. The power n from 1 to 7 (the paper\'s 4), always ln x: a coefficient inside the log is a step. The paper\'s power alone makes 7 questions, below the floor, so a number in front, 1 (the paper), 2 or 3, as the owner kept a numerator of 2 or 3 on 2025 P1 Q5: a coefficient, not a step. 21 questions. All exact: Paper 1.',
  },
  {
    card: '2023 P2 Q2',
    skill: 'Integrate a power of $x$ over a polynomial whose derivative it is a multiple of, as a logarithm.',
    marks: [2],
    route: 'The integral of f\'(x)/f(x) recognised, k ln|x^n + c|; then the coefficient 1/n, with the constant of integration.',
    ranges: 'The paper: x^2/(x^3 + 10), giving (1/3) ln|x^3 + 10| + c. The bottom x^n + c with n from 2 to 5 (the paper\'s 3) and the top x^{n-1}, so the top is always the bottom\'s derivative over n, as the paper\'s; c from 1 to 20 either sign (the paper\'s 10), the modulus written as the paper\'s. 160 questions.',
  },
  {
    card: '2019 Q16',
    skill: 'A definite integral of a squared linear factor times an exponential by parts twice, then the volume of revolution it gives.',
    marks: [5, 3],
    route: '5 + 3 - (a) the first application begun, e^{mx}/m times the quadratic; then completed, less the integral of its derivative times e^{mx}/m; the second application; the whole integral with its limits; evaluated exactly; (b) the volume as π times the integral of y^2 with limits and dx; y^2 written as c^2 times (a)\'s integrand; then c^2π times (a).',
    ranges: 'The paper: the integral of (x^2 - 2x + 1)e^{4x} from 0 to 1, (1/32)(e^4 - 13); y = 4(x - 1)e^{2x} from 0 to 1, (π/2)(e^4 - 13). The quadratic is always the square of x - p, written out as the paper\'s, from 0 to p, so (b)\'s y^2 is c^2 times (a)\'s integrand, as the paper\'s 16: p 1 (the paper) or 2, the exponent m 2, 4 (the paper) or 6, so y has e^{(m/2)x} with a whole number, and c from 2 to 5 (the paper\'s 4). The answers exact and in the paper\'s form, (1/D)(e^{mp} - L). 24 questions.',
  },
  {
    card: '2018 Q8',
    skill: 'A definite integral of $A\\sin^{n}\\theta\\cos\\theta$ by the substitution $u = \\sin\\theta.$',
    marks: [4],
    route: 'du/dθ = cos θ; the limits in u, 1/2 and 1; the integral rewritten, A∫ u^n du from 1/2 to 1; integrated and evaluated, A/(n + 1) × (1 - 1/2^{n+1}). An integral with both u and θ in it cannot be done.',
    ranges: 'The paper: 2 sin^4 θ cos θ from π/6 to π/2, 31/80. n from 2 to 6 (the paper\'s 4) and A from 1 to 6 (the paper\'s 2); always π/6 to π/2, as the paper, so the lower limit in u is 1/2. The answer an exact fraction. 30 questions.',
  },
  {
    card: '2018 Q15',
    skill: 'By parts, $\\int x\\sin kx\\,dx$; then $\\frac{dy}{dx} - \\frac{m}{x}y = x^{m + 1}\\sin kx$ with an integrating factor, using it.',
    marks: [3, 7],
    route: '3 + 7 - (a) by parts with u = x, -(x/k) cos kx - …; the integral left, ∫ -(1/k) cos kx dx; completed, + (1/k^2) sin kx + c; (b) the integrating factor as e^{∫ -m/x dx}; simplified, 1/x^m; the left side the derivative of (1/x^m)y; the integral equation; (a) used; c from y = 0 at x = π, c = (π/k)(-1)^k; y made the subject.',
    ranges: 'The paper: x sin 3x, dy/dx - (2/x)y = x^3 sin 3x, y = 0 at x = π, c = -π/3. k from 2 to 6 (the paper\'s 3) and m from 1 to 3 (the paper\'s 2), so x^{m+1} over x^m is always x and (b)\'s integral is always (a)\'s, as the paper\'s "Hence"; always x = π, as the paper. 15 questions.',
  },
  {
    card: '2017 Q6',
    skill: 'A definite integral of $\\frac{ax}{\\sqrt{1 - k^{2}x^{4}}}$ by the substitution $u = kx^{2}$, as an inverse sine.',
    marks: [6],
    route: 'du = 2kx dx; the limits in u, 0 and 1/2; x dx replaced by (1/2k) du; the integrand in u, 1/√(1 - u^2); integrated, (a/2k)[sin^{-1} u]; evaluated, aπ/(12k). An integral with both u and x in it cannot be done.',
    ranges: 'The paper: u = 5x^2, x/√(1 - 25x^4) from 0 to 1/√10, π/60. k from 2 to 9 (the paper\'s 5), the upper limit 1/√(2k), so u runs from 0 to 1/2 and sin^{-1} gives π/6, as the paper\'s (1/2 at k = 2 and 1/4 at k = 8, where 2k is a square); k alone makes 8, so a number in front, a from 1 (the paper) to 4, as the owner allowed on 2021 P2 Q10. Always sin^{-1}, as the paper. 32 questions.',
  },
  {
    card: '2017 Q16',
    skill: 'The volume when a quarter of the ellipse $Ax^{2} + By^{2} = C$ is rotated about the $y$-axis (or the $x$-axis), exactly.',
    marks: [5],
    route: 'V = π∫ x^2 dy (about the x-axis, π∫ y^2 dx); x^2 (or y^2) from the curve\'s equation, substituted; the limits, 0 and the end of the section on that axis; integrated; evaluated exactly, (2/3)πX^2Y (or (2/3)πXY^2). Integrating with respect to the wrong variable earns nothing after the first mark.',
    ranges: 'The paper: 4x^2 + 9y^2 = 36, the section from y = 0 to 2, V = 12π. Built from the semi-axes, X across and Y up, different (a circle would be a sphere) from 1 to 6 (the paper\'s 3 and 2), the longer at most three times the shorter, so the section is a shape like the paper\'s and never a sliver; the equation Y^2x^2 + X^2y^2 = X^2Y^2 over any common factor, as 4x^2 + 9y^2 = 36. The figure is the paper\'s: the shaded quarter on arrowed axes, to scale, with no numbers. On the owner\'s comment on the 2017 sheet, "Could we extend so that half the time it is rotated about the x-axis instead?", half the draws rotate about the x-axis: X and Y always differ, so the two axes never give the same volume. 48 questions.',
  },
  {
    card: '2016 Q9',
    skill: 'Integrate a power of $x$ times $(\\ln x)^{2}$ by parts twice.',
    marks: [6],
    route: 'By parts, the power of x integrated and (ln x)^2 differentiated, the uv part begun; the integral left written; (ln x)^2 differentiated by the chain rule, 2 ln x/x, and the integral simplified; by parts again, the power integrated; the second application completed; then simplified, with + c.',
    ranges: 'The paper: x^7(ln x)^2, answer (1/8)x^8(ln x)^2 - (1/32)x^8 ln x + (1/256)x^8 + c. The power n from 1 to 9 (the paper\'s 7); n alone makes 9, so a number in front, a from 1 (the paper) to 4, as the owner allowed on 2021 P2 Q10, a bigger number, not a step. Always (ln x)^2, as the paper. 36 questions. A near relation of 2023 P2 Q2 (locked), once by parts with ln x.',
  },
];
