export const higherPastPaper2019 = {
  year: 2019,
  papers: [
    {
      paperNumber: 1,
      questions: [
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q1</span></strong></small><br>Find the x-coordinates of the stationary points on the curve with equation<br>\\(y=\\frac{1}{2}x^{4}-2x^{3}+6.\\)`,
          answer: `\\(x=0\\) and \\(x=3\\)`,
          videoId: "I8WkRoWL8as",
          timestamp: "0s",
          topics: ["Find stationary points and determine nature"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q2</span></strong></small><br>The equation \\(x^{2}+(k-5)x+1=0\\) has equal roots.<br>Determine the possible values of \\(k.\\)`,
          answer: `\\(k=3\\), \\(k=7\\)`,
          videoId: "I8WkRoWL8as",
          timestamp: "58s",
          topics: ["Discriminant and Quadratics"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q3</span></strong></small><br>Circle \\(C_{1}\\) has equation<br>\\(x^{2}+y^{2}-6x-2y-26=0\\)<br>Circle \\(C_{2}\\) has centre \\((4,-2)\\).<br>The radius of \\(C_{2}\\) is equal to the radius of \\(C_{1}\\).<br>Find the equation of circle \\(C_{2}\\).`,
          answer: `\\((x-4)^{2}+(y+2)^{2}=36\\)`,
          videoId: "I8WkRoWL8as",
          timestamp: "145s",
          topics: ["Circle equation from radius/centre or vice versa"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q4</span></strong></small><p>A sequence is generated by the recurrence relation \\(u_{n+1}=mu_{n}+c\\), where the first three terms of the sequence are 6, 9 and 11.<br><br><b>(a)</b>&nbsp;&nbsp;Find the values of \\(m\\) and \\(c.\\)<br><b>(b)</b>&nbsp;&nbsp;Hence, calculate the fourth term of the sequence.</p>`,
          answer: `(a) \\(m=\\frac{2}{3}\\), \\(c=5\\)<br>(b) \\(u_{4}=\\frac{37}{3}\\) (or \\(12\\frac{1}{3}\\))`,
          videoId: "I8WkRoWL8as",
          timestamp: "240s",
          topics: ["Go backwards to find recurrence relation when terms known"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q5</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Show that the points \\(A(1,5,-3)\\), \\(B(4,-1,0)\\) and \\(C(8,-9,4)\\) are collinear.<br><b>(b)</b>&nbsp;&nbsp;State the ratio in which B divides AC.</p>`,
          answer: `(a) Proof (showing vectors are parallel and share a common point)<br>(b) 3:4`,
          videoId: "I8WkRoWL8as",
          timestamp: "349s",
          topics: ["Collinearity (in 3d or 2d)", "Ratio in which one point divides two others"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q6</span></strong></small><br>Given that<br>\\(y=\\frac{1}{(1-3x)^{5}}\\), \\(x\\ne\\frac{1}{3}\\)<br>find \\(\\frac{dy}{dx}.\\)`,
          answer: `\\(15(1-3x)^{-6}\\) or \\(\\frac{15}{(1-3x)^{6}}\\)`,
          videoId: "I8WkRoWL8as",
          timestamp: "504s",
          topics: ["Differentiate or evaluate derivative: composite function"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q7</span></strong></small><br>The line, L, makes an angle of \\(30^{\\circ}\\) with the positive direction of the x-axis.<br>Find the equation of the line perpendicular to L, passing through \\((0,-4)\\).`,
          answer: `\\(y=-\\sqrt{3}x-4\\)`,
          videoId: "I8WkRoWL8as",
          timestamp: "549s",
          topics: ["Perpendicular and parallel lines", "Angles and straight lines: m = tanθ"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q8</span></strong></small><p>The graphs of \\(y=x^{2}+2x+3\\) and \\(y=2x^{2}+x+1\\) are shown below. The graphs intersect at the points where \\(x=-1\\) and \\(x=2\\).</p><img src="/img/Higher_Past_Papers/2019/2019_P1_Q8.png" alt="Graphs of two parabolas intersecting"><p><b>(a)</b>&nbsp;&nbsp;Express the shaded area, enclosed between the curves, as an integral.<br><b>(b)</b>&nbsp;&nbsp;Evaluate the shaded area.</p>`,
          answer: `(a) \\(\\int_{-1}^{2}(-x^{2}+x+2)dx\\)<br>(b) \\(\\frac{9}{2}\\)`,
          videoId: "I8WkRoWL8as",
          timestamp: "599s",
          topics: ["Areas using integration"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q9</span></strong></small><p>Vectors \\(\\mathbf{u}\\) and \\(\\mathbf{v}\\) have components<br>\\(\\begin{pmatrix}p\\\\-2\\\\4\\end{pmatrix}\\) and \\(\\begin{pmatrix}2p+16\\\\-3\\\\6\\end{pmatrix}\\)<br>\\(p\\in\\mathbb{R}.\\)<br><br><b>(a)</b>&nbsp;&nbsp;(i) Find an expression for \\(\\mathbf{u}\\cdot\\mathbf{v}.\\)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ii) Determine the values of \\(p\\) for which \\(\\mathbf{u}\\) and \\(\\mathbf{v}\\) are perpendicular.<br><b>(b)</b>&nbsp;&nbsp;Determine the value of \\(p\\) for which \\(\\mathbf{u}\\) and \\(\\mathbf{v}\\) are parallel.</p>`,
          answer: `(a)(i) \\(2p^{2}+16p+30\\)<br>(a)(ii) \\(p=-5\\), \\(p=-3\\)<br>(b) \\(p=-32\\)`,
          videoId: "I8WkRoWL8as",
          timestamp: "831s",
          topics: ["Perpendicular vectors and the scalar product"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q10</span></strong></small><p>The diagram shows the graphs with equations \\(y=f(x)\\) and \\(y=kf(x)+a.\\)</p><img src="/img/Higher_Past_Papers/2019/2019_P1_Q10.png" alt="Graphs of f(x) and transformed function kf(x)+a"><p><b>(a)</b>&nbsp;&nbsp;State the value of \\(a.\\)<br><b>(b)</b>&nbsp;&nbsp;Find the value of \\(k.\\)</p>`,
          answer: `(a) \\(a=3\\)<br>(b) \\(k=-2\\)`,
          videoId: "I8WkRoWL8as",
          timestamp: "1022s",
          topics: ["Identifying/sketching graphs of related functions (non-trigonometric)"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q11</span></strong></small><br>Evaluate<br>\\(\\int_{0}^{\\frac{\\pi}{9}}\\cos(3x-\\frac{\\pi}{6})dx.\\)`,
          answer: `\\(\\frac{1}{3}\\)`,
          videoId: "I8WkRoWL8as",
          timestamp: "1101s",
          topics: ["Integrate (definite or indefinite): trigonometric expression"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q12</span></strong></small><p>Functions \\(f\\) and \\(g\\) are defined by<br>\\(f(x)=\\frac{1}{\\sqrt{x}}\\), where \\(x \\gt 0\\)<br>and<br>\\(g(x)=5-x\\), where \\(x\\in\\mathbb{R}.\\)<br><b>(a)</b>&nbsp;&nbsp;Determine an expression for \\(f(g(x)).\\)<br><b>(b)</b>&nbsp;&nbsp;State the range of values of \\(x\\) for which \\(f(g(x))\\) is undefined.</p>`,
          answer: `(a) \\(\\frac{1}{\\sqrt{5-x}}\\) <br>(b) \\(x\\ge 5\\)`,
          videoId: "I8WkRoWL8as",
          timestamp: "1329s",
          topics: ["Domain and range", "Composite functions"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q13</span></strong></small><p>Triangles ABC and ADE are both right angled. Angles \\(p\\) and \\(q\\) are as shown in the diagram.</p><img src="/img/Higher_Past_Papers/2019/2019_P1_Q13.png" alt="Right angled triangles ABC and ADE with angles p and q"><p><b>(a)</b>&nbsp;&nbsp;Determine the value of:<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(i) \\(\\cos p\\)<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ii) \\(\\cos q\\)<br><b>(b)</b>&nbsp;&nbsp;Hence determine the value of \\(\\sin(p+q).\\)</p>`,
          answer: `(a)(i) \\(\\frac{2}{\\sqrt{5}}\\), (ii) \\(\\frac{3}{\\sqrt{10}}\\) <br>(b) \\(\\frac{1}{\\sqrt{2}}\\) (or \\(\\frac{\\sqrt{2}}{2}\\))`,
          videoId: "I8WkRoWL8as",
          timestamp: "1406s",
          topics: ["Apply compound angle formula to simplify or evaluate"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q14</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Evaluate<br>\\(\\log_{10}4+2\\log_{10}5.\\)<br><br><b>(b)</b>&nbsp;&nbsp;Solve<br>\\(\\log_{2}(7x-2)-\\log_{2}3=5\\)<br>\\(x \\ge 1.\\)</p>`,
          answer: `(a) 2<br>(b) \\(x=14\\)`,
          videoId: "I8WkRoWL8as",
          timestamp: "1589s",
          topics: ["Simplify numerical expression involving logs/exponentials", "Solving equations containing a logarithm"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q15</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Solve the equation<br>\\(\\sin 2x^{\\circ}+6\\cos x^{\\circ}=0\\)<br>for \\(0\\le x \\lt 360.\\)<br><b>(b)</b>&nbsp;&nbsp;Hence solve<br>\\(\\sin 4x^{\\circ}+6\\cos 2x^{\\circ}=0\\)<br>for \\(0\\le x \\lt 360.\\)</p>`,
          answer: `(a) 90, 270, no solutions<br>(b) 45, 135, 225, 315`,
          videoId: "I8WkRoWL8as",
          timestamp: "1706s",
          topics: ["Solving a trigonometric equation using formula for sin(2x)"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q16</span></strong></small><p>The point P has coordinates \\((4,k)\\). \\(C\\) is the centre of the circle with equation<br>\\((x-1)^{2}+(y+2)^{2}=25\\)<br><b>(a)</b>&nbsp;&nbsp;Show that the distance between the points P and C is given by \\(\\sqrt{k^{2}+4k+13}.\\)<br><b>(b)</b>&nbsp;&nbsp;Hence, or otherwise, find the range of values of \\(k\\) such that P lies outside the circle.</p>`,
          answer: `(a) Proof<br>(b) \\(k \\lt -6\\) or \\(k \\gt 2\\)`,
          videoId: "I8WkRoWL8as",
          timestamp: "1905s",
          topics: ["Quadratic inequations"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P1 Q17</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Express \\((\\sin x-\\cos x)^{2}\\) in the form \\(p+q\\sin rx\\) where \\(p,q\\) and \\(r\\) are integers.<br><b>(b)</b>&nbsp;&nbsp;Hence, find \\(\\int(\\sin x-\\cos x)^{2}dx.\\)</p>`,
          answer: `(a) \\(1-\\sin 2x\\)<br>(b) \\(x+\\frac{1}{2}\\cos 2x+c\\)`,
          videoId: "I8WkRoWL8as",
          timestamp: "2089s",
          topics: ["Proving a trigonometric identity"]
        }
      ]
    },
    {
      paperNumber: 2,
      questions: [
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q1</span></strong></small><p>Triangle ABC has vertices \\(A(-5,-12)\\), \\(B(11,-8)\\) and \\(C(-3,6)\\).</p><img src="/img/Higher_Past_Papers/2019/2019_P2_Q1.png" alt="Triangle ABC with median BD and altitude AE"><p><b>(a)</b>&nbsp;&nbsp;Find the equation of the median BD.<br><b>(b)</b>&nbsp;&nbsp;Find the equation of the altitude AE.<br><b>(c)</b>&nbsp;&nbsp;Find the coordinates of the point of intersection of BD and AE.</p>`,
          answer: `(a) \\(x+3y+13=0\\)<br>(b) \\(y=x-7\\) (or \\(x-y-7=0\\))<br>(c) \\((2,-5)\\)`,
          videoId: "Enrov8kIzeQ",
          timestamp: "0s",
          topics: ["Altitudes, medians, perpendicular bisectors", "Intersection of straight lines"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q2</span></strong></small><br>Find<br>\\(\\int(6\\sqrt{x}-4x^{-3}+5)dx.\\)`,
          answer: `\\(4x^{\\frac{3}{2}}+2x^{-2}+5x+c\\)`,
          videoId: "Enrov8kIzeQ",
          timestamp: "316s",
          topics: ["Integrate (definite or indefinite): polynomial"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q3</span></strong></small><p>E,ABCD is a rectangular based pyramid. \\(\\vec{AB}=\\mathbf{p}\\), \\(\\vec{AD}=\\mathbf{q}\\) and \\(\\vec{AE}=\\mathbf{r}.\\)</p><img src="/img/Higher_Past_Papers/2019/2019_P2_Q3.png" alt="Rectangular based pyramid E,ABCD"><p><b>(a)</b>&nbsp;&nbsp;Express \\(\\vec{BE}\\) in terms of \\(\\mathbf{p}\\) and \\(\\mathbf{r}.\\)<br>Point F divides BC in the ratio 3:1.<br><b>(b)</b>&nbsp;&nbsp;Express vector \\(\\vec{EF}\\) in terms of \\(\\mathbf{p}, \\mathbf{q}\\) and \\(\\mathbf{r}.\\)</p>`,
          answer: `(a) \\(\\mathbf{r}-\\mathbf{p}\\)<br>(b) \\(\\mathbf{p}-\\mathbf{r}+\\frac{3}{4}\\mathbf{q}\\)`,
          videoId: "Enrov8kIzeQ",
          timestamp: "417s",
          topics: ["Ratio in which one point divides two others", "Basic vector paths (now in N5 maths)", "Vector pathways in geometric diagrams"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q4</span></strong></small><p>In a forest, the population of a species of mouse is falling by 2·7% each year. To increase the population scientists plan to release 30 mice into the forest at the end of March each year.<br><b>(a)</b>&nbsp;&nbsp;\\(u_{n}\\) is the estimated population of mice at the start of April, \\(n\\) years after the population was first estimated. It is known that \\(u_{n}\\) and \\(u_{n+1}\\) satisfy the recurrence relation \\(u_{n+1}=au_{n}+b\\). State the values of \\(a\\) and \\(b.\\)<br>The scientists continue to release this species of mouse each year.<br><b>(b)</b>&nbsp;&nbsp;(i) Explain why the estimated population of mice will stabilise in the long term.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ii) Calculate the long term population to the nearest hundred.</p>`,
          answer: `(a) \\(a=0.973\\), \\(b=30\\)<br>(b)(i) Limit exists because \\(-1 \\lt 0.973 \\lt 1\\)<br>(b)(ii) 1100`,
          videoId: "Enrov8kIzeQ",
          timestamp: "512s",
          topics: ["Write a recurrence relation formula from a real-life situation", "Limits of recurrence relations"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q5</span></strong></small><p>The diagram below shows the graph of a cubic function \\(y=g(x)\\), with stationary points at \\(x=-2\\) and \\(x=4.\\)</p><img src="/img/Higher_Past_Papers/2019/2019_P2_Q5.png" alt="Graph of cubic function g(x)"><p>On the diagram in your answer booklet, sketch the graph of \\(y=g^{\\prime}(x).\\)</p>`,
          answer: `Sketch of a upward opening parabola (U Shape) crossing x-axis at -2 and 4.`,
          videoId: "Enrov8kIzeQ",
          timestamp: "635s",
          topics: ["The graph of the derived function"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q6</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Express \\(2\\cos x^{\\circ}-3\\sin x^{\\circ}\\) in the form \\(k\\cos(x+a)^{\\circ}\\) where \\(k \\gt 0\\) and \\(0\\le a \\lt 360.\\)<br><b>(b)</b>&nbsp;&nbsp;Hence solve<br>\\(2\\cos x^{\\circ}-3\\sin x^{\\circ}=3\\)<br>for \\(0\\le x \\lt 360.\\)</p>`,
          answer: `(a) \\(\\sqrt{13}\\cos(x+56.3)^{\\circ}\\)<br>(b) \\(x=270\\), \\(x=337.4\\)`,
          videoId: "Enrov8kIzeQ",
          timestamp: "741s",
          topics: ["Wave function (y = asin x ± bcosx)", "Trig equation involving compound angle"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q7</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Express \\(-6x^{2}+24x-25\\) in the form \\(p(x+q)^{2}+r.\\)<br><b>(b)</b>&nbsp;&nbsp;Given that<br>\\(f(x)=-2x^{3}+12x^{2}-25x+9\\)<br>show that \\(f(x)\\) is strictly decreasing for all \\(x\\in\\mathbb{R}.\\)</p>`,
          answer: `(a) \\(-6(x-2)^{2}-1\\)<br>(b) \\(f^{\\prime}(x) = -6(x-2)^{2}-1\\), which is always negative (since square term is non-negative and multiplied by -6, then subtract 1).`,
          videoId: "Enrov8kIzeQ",
          timestamp: "1049s",
          topics: ["Completing the square", "Increasing/decreasing: show that, or find values for which"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q8</span></strong></small><p>A function, \\(f\\), is given by<br>\\(f(x)=\\sqrt[3]{x}+8\\)<br>The domain of \\(f\\) is \\(1\\le x\\le1000\\), \\(x\\in\\mathbb{R}\\). The inverse function, \\(f^{-1}\\), exists.<br><b>(a)</b>&nbsp;&nbsp;Find \\(f^{-1}(x).\\)<br><b>(b)</b>&nbsp;&nbsp;State the domain of \\(f^{-1}.\\)</p>`,
          answer: `(a) \\(f^{-1}(x)=(x-8)^{3}\\)<br>(b) \\(9\\le x\\le18\\)`,
          videoId: "Enrov8kIzeQ",
          timestamp: "1235s",
          topics: ["Inverse functions", "Domain and range"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q9</span></strong></small><p>Electricity on a spacecraft can be produced by a type of nuclear generator. The electrical power produced by this generator can be modelled by<br>\\(P_{t}=120e^{-0.0079t}\\)<br>where \\(P_{t}\\) is the electrical power produced, in watts, after \\(t\\) years.<br><b>(a)</b>&nbsp;&nbsp;Determine the electrical power initially produced by the generator.<br><b>(b)</b>&nbsp;&nbsp;Calculate how long it takes for the electrical power produced by the generator to reduce by 15%.</p>`,
          answer: `(a) 120 watts<br>(b) 20.6 years`,
          videoId: "Enrov8kIzeQ",
          timestamp: "1356s",
          topics: ["Solving equations where the unknown is in the exponent"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q10</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Show that \\((x+3)\\) is a factor of<br>\\(3x^{4}+10x^{3}+x^{2}-8x-6\\)<br><b>(b)</b>&nbsp;&nbsp;Hence, or otherwise, factorise \\(3x^{4}+10x^{3}+x^{2}-8x-6\\) fully.</p>`,
          answer: `(a) Proof (Remainder = 0)<br>(b) \\((x+3)(x-1)(3x^{2}+4x+2)\\)`,
          videoId: "Enrov8kIzeQ",
          timestamp: "1539s",
          topics: ["Cubic/quartic expressions/equations: factorise or solve"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q11</span></strong></small><p>A manufacturer of chocolates is launching a new product in novelty shaped cardboard boxes. The box is a cuboid with a cuboid shaped tunnel through it.</p><img src="/img/Higher_Past_Papers/2019/2019_P2_Q11_1.png" alt="Box with tunnel"><p>&bull;&nbsp;&nbsp;The height of the box is \\(h\\) centimetres<br>&bull;&nbsp;&nbsp;The top of the box is a square of side \\(3x\\) centimetres<br>&bull;&nbsp;&nbsp;The end of the tunnel is a square of side \\(x\\) centimetres<br>&bull;&nbsp;&nbsp;The volume of the box is \\(2000\\text{ cm}^{3}\\)</p><img src="/img/Higher_Past_Papers/2019/2019_P2_Q11_2.png" alt="Dimensions of the box"><p><b>(a)</b>&nbsp;&nbsp;Show that the total surface area, \\(A\\text{ cm}^{2}\\), of the box is given by<br>\\(A=16x^{2}+\\frac{4000}{x}\\)<br><b>(b)</b>&nbsp;&nbsp;To minimise the cost of production, the surface area, \\(A\\), of the box should be as small as possible. Find the minimum value of \\(A.\\)</p>`,
          answer: `(a) Proof<br>(b) 1200`,
          videoId: "Enrov8kIzeQ",
          timestamp: "1730s",
          topics: ["Optimisation"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q12</span></strong></small><p>Two variables, \\(x\\) and \\(y\\), are connected by the equation \\(y=ab^{x}\\). The graph of \\(\\log_{4}y\\) against \\(x\\) is a straight line as shown.</p><img src="/img/Higher_Past_Papers/2019/2019_P2_Q12.png" alt="Graph of log4y against x"><p>Find the values of \\(a\\) and \\(b.\\)</p>`,
          answer: `\\(a=\\frac{1}{4}\\), \\(b=64\\)`,
          videoId: "Enrov8kIzeQ",
          timestamp: "2188s",
          topics: ["Deriving relationship y = ab^x or y = ax^b from straight line"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q13</span></strong></small><p>For a function, \\(f\\), defined on the set of real numbers, \\(\\mathbb{R}\\), it is known that:<br>&bull;&nbsp;&nbsp;the rate of change of \\(f\\) with respect to \\(x\\) is given by \\(3x^{2}-16x+11\\)<br>&bull;&nbsp;&nbsp;the graph with equation \\(y=f(x)\\) crosses the x-axis at \\((7,0).\\)<br>Express \\(f(x)\\) in terms of \\(x.\\)</p>`,
          answer: `\\(f(x)=x^{3}-8x^{2}+11x-28\\)`,
          videoId: "Enrov8kIzeQ",
          timestamp: "2376s",
          topics: ["Differential equation"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q14</span></strong></small><p>The vectors \\(\\mathbf{u}\\) and \\(\\mathbf{v}\\) are such that \\(|\\mathbf{u}|=4\\), \\(|\\mathbf{v}|=5\\) and \\(\\mathbf{u}\\cdot(\\mathbf{u}+\\mathbf{v})=21.\\)<br>Determine the size of the angle between the vectors \\(\\mathbf{u}\\) and \\(\\mathbf{v}.\\)</p>`,
          answer: `\\(75.5^{\\circ}\\)`,
          videoId: "Enrov8kIzeQ",
          timestamp: "2538s",
          topics: ["Using the distributive law with the scalar product", "Calculating an angle using the scalar product"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2019 P2 Q15</span></strong></small><p>A circle has centre \\(C(8,12)\\). The point \\(P(5,13)\\) lies on the circle as shown.</p><img src="/img/Higher_Past_Papers/2019/2019_P2_Q15.png" alt="Circle with centre C and point P"><p><b>(a)</b>&nbsp;&nbsp;Find the equation of the tangent at P.<br>The tangent from P meets the y-axis at the point T.<br><b>(b)</b>&nbsp;&nbsp;(i) State the coordinates of T.<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ii) Find the equation of the circle that passes through the points C, P and T.</p>`,
          answer: `(a) \\(y=3x-2\\)<br>(b)(i) \\((0,-2)\\), (ii) \\((x-4)^{2}+(y-5)^{2}=65\\)`,
          videoId: "Enrov8kIzeQ",
          timestamp: "2651s",
          topics: ["Equation of a tangent to a circle at a point", "Circle equation from radius/centre or vice versa"]
        }
      ]
    }
  ]
};