export const higherPastPaper2017 = {
  year: 2017,
  papers: [
    {
      paperNumber: 1,
      questions: [
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q1</span></strong></small><br>Functions \\(f\\) and \\(g\\) are defined on suitable domains by<br>\\(f(x)=5x\\)<br>and<br>\\(g(x)=2 \\cos x\\)<br><br><b>(a)</b>&nbsp;&nbsp;Evaluate \\(f(g(0))\\).<br><b>(b)</b>&nbsp;&nbsp;Find an expression for \\(g(f(x))\\).`,
          answer: `(a) 10<br>(b) \\(2 \\cos(5x)\\)`,
          videoId: "-2Gcx6LHREc",
          timestamp: "0s",
          topics: ["Composite functions"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q2</span></strong></small><br>The point \\(P(-2,1)\\) lies on the circle<br>\\(x^{2}+y^{2}-8x-6y-15=0\\)<br>Find the equation of the tangent to the circle at P.`,
          answer: `\\(y=-3x-5\\)`,
          videoId: "-2Gcx6LHREc",
          timestamp: "84s",
          topics: ["Equation of a tangent to a circle at a point"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q3</span></strong></small><br>Given \\(y=(4x-1)^{12}\\), find \\(\\frac{dy}{dx}\\).`,
          answer: `\\(48(4x-1)^{11}\\)`,
          videoId: "-2Gcx6LHREc",
          timestamp: "195s",
          topics: ["Differentiate or evaluate derivative: composite function"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q4</span></strong></small><br>Find the value of \\(k\\) for which the equation<br>\\(x^{2}+4x+(k-5)=0\\)<br>has equal roots.`,
          answer: `\\(k=9\\)`,
          videoId: "-2Gcx6LHREc",
          timestamp: "221s",
          topics: ["Discriminant and Quadratics"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q5</span></strong></small><p>Vectors \\(\\mathbf{u}\\) and \\(\\mathbf{v}\\) are<br>\\(\\begin{pmatrix}5\\\\1\\\\-1\\end{pmatrix}\\) and \\(\\begin{pmatrix}3\\\\-8\\\\6\\end{pmatrix}\\)<br>respectively.</p><img src="/img/Higher_Past_Papers/2017/2017_P1_Q5.png" alt="Vector diagram"><p><b>(a)</b>&nbsp;&nbsp;Evaluate \\(\\mathbf{u}\\cdot\\mathbf{v}\\).<br><b>(b)</b>&nbsp;&nbsp;Vector \\(\\mathbf{w}\\) makes an angle of \\(\\frac{\\pi}{3}\\) with \\(\\mathbf{u}\\) and \\(|\\mathbf{w}|=\\sqrt{3}\\).<br>Calculate \\(\\mathbf{u}\\cdot\\mathbf{w}\\).</p>`,
          answer: `(a) 1<br>(b) 4.5`,
          videoId: "-2Gcx6LHREc",
          timestamp: "289s",
          topics: ["Scalar product"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q6</span></strong></small><br>A function, \\(h\\), is defined by<br>\\(h(x)=x^{3}+7\\)<br>where \\(x\\in\\mathbb{R}\\).<br>Determine an expression for \\(h^{-1}(x).\\)`,
          answer: `\\(h^{-1}(x)=\\sqrt[3]{x-7}\\)`,
          videoId: "-2Gcx6LHREc",
          timestamp: "453s",
          topics: ["Inverse functions"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q7</span></strong></small><br>\\(A(-3,5)\\), \\(B(7, 9)\\) and \\(C(2,11)\\) are the vertices of a triangle.<br>Find the equation of the median through C.`,
          answer: `\\(x=2\\)`,
          videoId: "-2Gcx6LHREc",
          timestamp: "498s",
          topics: ["Altitudes, medians, perpendicular bisectors"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q8</span></strong></small><br>Calculate the rate of change of<br>\\(d(t)=\\frac{1}{2t}\\), \\(t\\ne0\\)<br>when \\(t=5.\\)`,
          answer: `\\(-\\frac{1}{50}\\)`,
          videoId: "-2Gcx6LHREc",
          timestamp: "618s",
          topics: ["Differentiate or evaluate derivative: polynomial"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q9</span></strong></small><p>A sequence is generated by the recurrence relation<br>\\(u_{n+1}=mu_{n}+6\\)<br>where \\(m\\) is a constant.<br><br><b>(a)</b>&nbsp;&nbsp;Given \\(u_{1}=28\\) and \\(u_{2}=13\\), find the value of \\(m\\).<br><b>(b)</b>&nbsp;&nbsp;(i) Explain why this sequence approaches a limit as \\(n\\rightarrow\\infty\\).<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(ii) Calculate this limit.</p>`,
          answer: `(a) \\(m=\\frac{1}{4}\\)<br>(b) Limit is 8`,
          videoId: "-2Gcx6LHREc",
          timestamp: "680s",
          topics: ["Limits of recurrence relations", "Go backwards to find recurrence relation when terms known"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q10</span></strong></small><p>Two curves with equations<br>\\(y=x^{3}-4x^{2}+3x+1\\)<br>and<br>\\(y=x^{2}-3x+1\\)<br>intersect as shown in the diagram.</p><img src="/img/Higher_Past_Papers/2017/2017_P1_Q10_1.png" alt="Intersecting curves"><p><b>(a)</b>&nbsp;&nbsp;Calculate the shaded area.<br><br>The line passing through the points of intersection of the curves has equation \\(y=1-x\\).</p><img src="/img/Higher_Past_Papers/2017/2017_P1_Q10_2.png" alt="Curves with line y=1-x"><p><b>(b)</b>&nbsp;&nbsp;Determine the fraction of the shaded area which lies below the line \\(y=1-x\\).</p>`,
          answer: `(a) \\(\\frac{8}{3}\\)<br>(b) \\(\\frac{1}{2}\\)`,
          videoId: "-2Gcx6LHREc",
          timestamp: "780s",
          topics: ["Areas using integration"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q11</span></strong></small><br>A and B are the points \\((-7, 2)\\) and \\((5, a)\\).<br>AB is parallel to the line with equation<br>\\(3y-2x=4\\)<br>Determine the value of \\(a\\).`,
          answer: `\\(a=10\\)`,
          videoId: "-2Gcx6LHREc",
          timestamp: "1087s",
          topics: ["Perpendicular and parallel lines"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q12</span></strong></small><br>Given that<br>\\(\\log_{a}36-\\log_{a}4=\\frac{1}{2}\\)<br>find the value of \\(a\\).`,
          answer: `\\(a=81\\)`,
          videoId: "-2Gcx6LHREc",
          timestamp: "1156s",
          topics: ["Solving equations containing a logarithm"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q13</span></strong></small><br>Find<br>\\(\\int\\frac{1}{(5-4x)^{\\frac{1}{2}}}dx\\), \\(x \\lt \\frac{5}{4}.\\)`,
          answer: `\\(-\\frac{1}{2}(5-4x)^{\\frac{1}{2}}+c\\)`,
          videoId: "-2Gcx6LHREc",
          timestamp: "1201s",
          topics: ["Integrate (definite or indefinite): (px + q)^n"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q14</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Express<br>\\(\\sqrt{3}\\sin x^{\\circ}-\\cos x^{\\circ}\\)<br>in the form \\(k\\sin(x-a)^{\\circ}\\) where \\(k \\gt 0\\) and \\(0 \\lt a \\lt 360\\).<br><b>(b)</b>&nbsp;&nbsp;Hence, or otherwise, sketch the graph with equation<br>\\(y=\\sqrt{3}\\sin x^{\\circ}-\\cos x^{\\circ}\\)<br>for \\(0\\le x\\le360\\).</p>`,
          answer: `(a) \\(2\\sin(x-30)^{\\circ}\\)<br>(b) Sketch of sine wave with amplitude 2, shifted 30 degrees to the right.`,
          videoId: "-2Gcx6LHREc",
          timestamp: "1270s",
          topics: ["Wave function (y = asin x ± bcosx)", "Identifying/sketching graphs of related functions (trigonometric)"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P1 Q15</span></strong></small><p>A quadratic function, \\(f\\), is defined on \\(\\mathbb{R}\\), the set of real numbers.<br>Diagram 1 shows part of the graph with equation \\(y=f(x)\\). The turning point is \\((2, 3)\\).<br>Diagram 2 shows part of the graph with equation \\(y=h(x)\\). The turning point is \\((7, 6)\\).</p><img src="/img/Higher_Past_Papers/2017/2017_P1_Q15.png" alt="Diagram 1 and 2: Graphs of y=f(x) and y=h(x)"><p><b>(a)</b>&nbsp;&nbsp;Given that \\(h(x)=f(x+a)+b\\). Write down the values of \\(a\\) and \\(b\\).<br><b>(b)</b>&nbsp;&nbsp;It is known that \\(\\int_{1}^{3}f(x)dx=4\\). Determine the value of \\(\\int_{6}^{8}h(x)dx\\).<br><b>(c)</b>&nbsp;&nbsp;Given \\(f'(1)=6\\) state the value of \\(h'(8)\\).</p>`,
          answer: `(a) \\(a=-5, b=3\\)<br>(b) 10<br>(c) -6`,
          videoId: "-2Gcx6LHREc",
          timestamp: "1514s",
          topics: ["Identifying/sketching graphs of related functions (non-trigonometric)"]
        }
      ]
    },
    {
      paperNumber: 2,
      questions: [
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q1</span></strong></small><p>Triangle ABC is shown in the diagram below. The coordinates of B are \\((3,0)\\) and the coordinates of C are \\((9,-2)\\). The broken line is the perpendicular bisector of BC.</p><img src="/img/Higher_Past_Papers/2017/2017_P2_Q1.png" alt="Triangle ABC with perpendicular bisector"><p><b>(a)</b>&nbsp;&nbsp;Find the equation of the perpendicular bisector of BC.<br><b>(b)</b>&nbsp;&nbsp;The line AB makes an angle of \\(45^{\\circ}\\) with the positive direction of the x-axis. Find the equation of AB.<br><b>(c)</b>&nbsp;&nbsp;Find the coordinates of the point of intersection of AB and the perpendicular bisector of BC.</p>`,
          answer: `(a) \\(y=3x-19\\)<br>(b) \\(y=x-3\\)<br>(c) \\((8, 5)\\)`,
          videoId: "VhgnQl6gh14",
          timestamp: "0s",
          topics: ["Altitudes, medians, perpendicular bisectors", "Angles and straight lines: m = tanθ", "Intersection of straight lines"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q2</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Show that \\((x-1)\\) is a factor of<br>\\(f(x)=2x^{3}-5x^{2}+x+2\\)<br><b>(b)</b>&nbsp;&nbsp;Hence, or otherwise, solve \\(f(x)=0\\).</p>`,
          answer: `(a) Proof (Remainder is 0)<br>(b) \\(x=-\\frac{1}{2}, 1, 2\\)`,
          videoId: "VhgnQl6gh14",
          timestamp: "196s",
          topics: ["Cubic/quartic expressions/equations: factorise or solve"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q3</span></strong></small><p>The line \\(y=3x\\) intersects the circle with equation<br>\\((x-2)^{2}+(y-1)^{2}=25\\)</p><img src="/img/Higher_Past_Papers/2017/2017_P2_Q3.png" alt="Line y=3x intersecting circle"><p>Find the coordinates of the points of intersection.</p>`,
          answer: `\\((2, 6)\\) and \\((-1, -3)\\)`,
          videoId: "VhgnQl6gh14",
          timestamp: "317s",
          topics: ["Intersections of lines and circles (including showing tangency)"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q4</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Express \\(3x^{2}+24x+50\\) in the form \\(a(x+b)^{2}+c\\).<br><b>(b)</b>&nbsp;&nbsp;Given that<br>\\(f(x)=x^{3}+12x^{2}+50x-11\\)<br>find \\(f'(x)\\).<br><b>(c)</b>&nbsp;&nbsp;Hence, or otherwise, explain why the curve with equation \\(y=f(x)\\) is strictly increasing for all values of \\(x\\).</p>`,
          answer: `(a) \\(3(x+4)^{2}+2\\)<br>(b) \\(3x^{2}+24x+50\\)<br>(c) \\(f'(x)=3(x+4)^{2}+2\\), which is always \\(\\ge 2\\) (positive), so strictly increasing.`,
          videoId: "VhgnQl6gh14",
          timestamp: "451s",
          topics: ["Completing the square", "Differentiate or evaluate derivative: polynomial", "Increasing/decreasing: show that, or find values for which"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q5</span></strong></small><p>In the diagram, \\(\\vec{PR}=9\\mathbf{i}+5\\mathbf{j}+2\\mathbf{k}\\) and \\(\\vec{RQ}=-12\\mathbf{i}-9\\mathbf{j}+3\\mathbf{k}\\).</p><img src="/img/Higher_Past_Papers/2017/2017_P2_Q5.png" alt="Triangle PQR with point S"><p><b>(a)</b>&nbsp;&nbsp;Express \\(\\vec{PQ}\\) in terms of \\(\\mathbf{i}, \\mathbf{j}\\) and \\(\\mathbf{k}\\).<br>The point S divides QR in the ratio 1:2.<br><b>(b)</b>&nbsp;&nbsp;Show that \\(\\vec{PS}=\\mathbf{i}-\\mathbf{j}+4\\mathbf{k}\\).<br><b>(c)</b>&nbsp;&nbsp;Hence, find the size of angle QPS.</p>`,
          answer: `(a) \\(-3\\mathbf{i}-4\\mathbf{j}+5\\mathbf{k}\\)<br>(b) Proof<br>(c) \\(45.6^{\\circ}\\) (or 0.795 rad)`,
          videoId: "VhgnQl6gh14",
          timestamp: "638s",
          topics: ["Ratio in which one point divides two others", "Calculating an angle using the scalar product", "Vector pathways in geometric diagrams"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q6</span></strong></small><br>Solve<br>\\(5\\sin x-4=2\\cos 2x\\)<br>for \\(0\\le x \\lt 2\\pi\\).`,
          answer: `\\(x=0.85, 2.29\\) radians`,
          videoId: "VhgnQl6gh14",
          timestamp: "930s",
          topics: ["Solving a trigonometric equation using formula for cos(2x)"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q7</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Find the x-coordinate of the stationary point on the curve with equation<br>\\(y=6x-2\\sqrt{x^{3}}\\)<br><b>(b)</b>&nbsp;&nbsp;Hence, determine the greatest and least values of \\(y\\) in the interval \\(1\\le x\\le9\\).</p>`,
          answer: `(a) \\(x=4\\)<br>(b) Greatest value 8, least value 0`,
          videoId: "VhgnQl6gh14",
          timestamp: "1145s",
          topics: ["Find stationary points and determine nature", "Optimisation on a closed interval"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q8</span></strong></small><p>Sequences may be generated by recurrence relations of the form<br>\\(u_{n+1}=ku_{n}-20\\), \\(u_{0}=5\\)<br>where \\(k\\in\\mathbb{R}\\).<br><b>(a)</b>&nbsp;&nbsp;Show that \\(u_{2}=5k^{2}-20k-20.\\)<br><b>(b)</b>&nbsp;&nbsp;Determine the range of values of \\(k\\) for which \\(u_{2} \\lt u_{0}.\\)</p>`,
          answer: `(a) Proof<br>(b) \\(-1 \\lt k \\lt 5\\)`,
          videoId: "VhgnQl6gh14",
          timestamp: "1330s",
          topics: ["Find a specific term of a recurrence relation", "Quadratic inequations"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q9</span></strong></small><p>Two variables, \\(x\\) and \\(y\\), are connected by the equation \\(y=kx^{n}\\). The graph of \\(\\log_{2}y\\) against \\(\\log_{2}x\\) is a straight line as shown.</p><img src="/img/Higher_Past_Papers/2017/2017_P2_Q9.png" alt="Graph of log2y against log2x"><p>Find the values of \\(k\\) and \\(n\\).</p>`,
          answer: `\\(k=8, n=\\frac{1}{4}\\)`,
          videoId: "VhgnQl6gh14",
          timestamp: "1538s",
          topics: ["Deriving relationship y = ab^x or y = ax^b from straight line"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q10</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Show that the points \\(A(-7,-2)\\), \\(B(2,1)\\) and \\(C(17,6)\\) are collinear.<br>Three circles with centres A, B and C are drawn inside a circle with centre D as shown.</p><img src="/img/Higher_Past_Papers/2017/2017_P2_Q10.png" alt="Circles inside a larger circle"><p>The circles with centres A, B and C have radii \\(r_{A}, r_{B}\\) and \\(r_{C}\\) respectively.<br>\\(r_{A}=\\sqrt{10}\\), \\(r_{B}=2r_{A}\\), \\(r_{C}=r_{A}+r_{B}\\).<br><b>(b)</b>&nbsp;&nbsp;Determine the equation of the circle with centre D.</p>`,
          answer: `(a) Proof (Gradients AB and BC are equal)<br>(b) \\((x-8)^{2}+(y-3)^{2}=360\\)`,
          videoId: "VhgnQl6gh14",
          timestamp: "1686s",
          topics: ["Collinearity (in 3d or 2d)", "Circle equation from radius/centre or vice versa"]
        },
        {
          question: `<small><strong><span style="white-space: nowrap;">2017 P2 Q11</span></strong></small><p><b>(a)</b>&nbsp;&nbsp;Show that<br>\\(\\frac{\\sin 2x}{2\\cos x}-\\sin x \\cos^{2}x=\\sin^{3}x\\)<br>where \\(0 \\lt x \\lt \\frac{\\pi}{2}.\\)<br><b>(b)</b>&nbsp;&nbsp;Hence, differentiate<br>\\(\\frac{\\sin 2x}{2\\cos x}-\\sin x \\cos^{2}x\\)<br>where \\(0 \\lt x \\lt \\frac{\\pi}{2}.\\)</p>`,
          answer: `(a) Proof<br>(b) \\(3\\sin^{2}x \\cos x\\)`,
          videoId: "VhgnQl6gh14",
          timestamp: "2013s",
          topics: ["Proving a trigonometric identity", "Integrate or differentiate non-standard function using given facts"]
        }
      ]
    }
  ]
};